### ISSUE TITLE
Support for intellij-2018.2.*

### ISSUE THREAD

**Issue by petroseskinder** [bazelbuild/intellij#420] opened 2018-09-26 13:39 UTC
The current release of the plugin only supports 2018.1.*
A few internal users at Two Sigma have requested we upgrade to 2018.2.5 due to various UI fixes.
We are currently unable to do so without building and packaging our own version of the plugin.

**Comment by brendandouglas** [comment] 2018-09-26 14:18
Closing as a dupe of #375. The next release will support 2018.2

**Closed by brendandouglas** 2018-09-26 14:18 UTC
