### ISSUE TITLE
Getting Internal Error after recent update

### ISSUE THREAD

**Issue by orreksu** [bazelbuild/intellij#3565] opened 2022-05-03 13:52 UTC
**Bazel Plugin Version:** 2022.04.20.0.2-api-version-213

**Bazel Problems:** 
```
Error:Internal error: The specified parameters not match any of the following constructors: 
for interface com.google.idea.blaze.java.libraries.JarRepackager [Plugin: com.google.idea.bazel.ijwb]
```

**stacktrace.txt**
```
com.intellij.diagnostic.PluginException: The specified parameters not match any of the following constructors: 
for interface com.google.idea.blaze.java.libraries.JarRepackager [Plugin: com.google.idea.bazel.ijwb]
	at com.intellij.serviceContainer.ConstructorInjectionKt.getGreediestSatisfiableConstructor(constructorInjection.kt:183)
	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:38)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:876)
	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:47)
	at com.intellij.serviceContainer.ServiceComponentAdapter.access$createAndInitialize(ServiceComponentAdapter.kt:12)
	at com.intellij.serviceContainer.ServiceComponentAdapter$doCreateInstance$1.compute(ServiceComponentAdapter.kt:41)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:698)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:646)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeInNonCancelableSection(CoreProgressManager.java:237)
	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:40)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:113)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:67)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:60)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:595)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:569)
	at com.intellij.openapi.client.ClientAwareComponentManager.getFromSelfOrCurrentSession(ClientAwareComponentManager.kt:37)
	at com.intellij.openapi.client.ClientAwareComponentManager.getService(ClientAwareComponentManager.kt:22)
	at com.google.idea.blaze.java.libraries.JarRepackager.getInstance(JarRepackager.java:25)
	at com.google.idea.blaze.java.libraries.JarCache.copyAndRepackageLocally(JarCache.java:296)
	at com.google.idea.blaze.java.libraries.JarCache.refresh(JarCache.java:224)
	at com.google.idea.blaze.java.libraries.JarCache.onSync(JarCache.java:159)
	at com.google.idea.blaze.java.libraries.JarCache.access$000(JarCache.java:80)
	at com.google.idea.blaze.java.libraries.JarCache$FileCacheAdapter.onSync(JarCache.java:485)
	at com.google.idea.blaze.base.filecache.FileCaches.lambda$onSync$0(FileCaches.java:50)
	at com.google.idea.blaze.base.scope.Scope.push(Scope.java:57)
	at com.google.idea.blaze.base.filecache.FileCaches.onSync(FileCaches.java:45)
	at com.google.idea.blaze.base.sync.ProjectUpdateSyncTask.run(ProjectUpdateSyncTask.java:217)
	at com.google.idea.blaze.base.sync.ProjectUpdateSyncTask.runProjectUpdatePhase(ProjectUpdateSyncTask.java:122)
	at com.google.idea.blaze.base.sync.SyncPhaseCoordinator.lambda$updateProjectAndFinishSync$8(SyncPhaseCoordinator.java:531)
	at com.google.idea.blaze.base.sync.SyncScope.lambda$runWithTiming$1(SyncScope.java:67)
	at com.google.idea.blaze.base.sync.SyncScope.lambda$push$2(SyncScope.java:80)
	at com.google.idea.blaze.base.sync.SyncScope.push(SyncScope.java:95)
	at com.google.idea.blaze.base.sync.SyncScope.push(SyncScope.java:77)
	at com.google.idea.blaze.base.sync.SyncScope.runWithTiming(SyncScope.java:69)
	at com.google.idea.blaze.base.sync.SyncPhaseCoordinator.updateProjectAndFinishSync(SyncPhaseCoordinator.java:522)
	at com.google.idea.blaze.base.sync.SyncPhaseCoordinator.runSync(SyncPhaseCoordinator.java:438)
	at com.google.idea.blaze.base.sync.SyncPhaseCoordinator.lambda$syncProject$0(SyncPhaseCoordinator.java:246)
	at com.google.idea.blaze.base.scope.Scope.push(Scope.java:57)
	at com.google.idea.blaze.base.sync.SyncPhaseCoordinator.lambda$syncProject$1(SyncPhaseCoordinator.java:231)
	at com.google.idea.blaze.base.async.executor.ProgressiveTaskWithProgressIndicator.lambda$submitTask$0(ProgressiveTaskWithProgressIndicator.java:79)
	at com.google.idea.blaze.base.async.executor.ProgressiveTaskWithProgressIndicator.lambda$submitTaskWithResult$4(ProgressiveTaskWithProgressIndicator.java:127)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:57)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:624)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:698)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:646)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:623)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:57)
	at com.google.idea.blaze.base.async.executor.ProgressiveTaskWithProgressIndicator.lambda$submitTaskWithResult$5(ProgressiveTaskWithProgressIndicator.java:127)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by alice-ks** [comment] 2022-05-04 16:52
Thanks for the report. This is a duplicate of #3533.

**Closed by alice-ks** 2022-05-04 16:52 UTC
