### ISSUE TITLE
Exception when exporting run configurations

### ISSUE THREAD

**Issue by niclaslockner** [bazelbuild/intellij#121] opened 2017-08-09 09:09 UTC
I get the following stack trace when I try to export my Bazel run configurations using the menu Bazel -> Export Run Configurations

IntelliJ: 2017.2.1
Bazel plugin: 2017.07.05.0.2

```
com.intellij.execution.impl.RunManagerImpl.getSettings(Lcom/intellij/execution/configurations/RunConfiguration;)Lcom/intellij/execution/RunnerAndConfigurationSettings;
java.lang.NoSuchMethodError: com.intellij.execution.impl.RunManagerImpl.getSettings(Lcom/intellij/execution/configurations/RunConfiguration;)Lcom/intellij/execution/RunnerAndConfigurationSettings;
	at com.google.idea.blaze.base.run.exporter.RunConfigurationSerializer.writeToXml(RunConfigurationSerializer.java:42)
	at com.google.idea.blaze.base.run.exporter.ExportRunConfigurationDialog.writeConfiguration(ExportRunConfigurationDialog.java:221)
	at com.google.idea.blaze.base.run.exporter.ExportRunConfigurationDialog.doOKAction(ExportRunConfigurationDialog.java:211)
	at com.intellij.openapi.ui.DialogWrapper$OkAction.doAction(DialogWrapper.java:1867)
	at com.intellij.openapi.ui.DialogWrapper$DialogWrapperAction.actionPerformed(DialogWrapper.java:1828)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
```

**Comment by niclaslockner** [comment] 2017-08-09 10:30
From https://github.com/bazelbuild/intellij/issues/112:

This is caused by a plugin API change in 2017.2, which we don't yet support.

**Comment by brendandouglas** [comment] 2017-08-09 13:08
The next plugin release will be built against 2017.2, and so fixes this issue. For now closing as a duplicate of the other issue.

**Closed by brendandouglas** 2017-08-09 13:08 UTC
