### ISSUE TITLE
Fatal error initializing Bazel plugin

### ISSUE THREAD

**Issue by kgignatyev-inspur** [bazelbuild/intellij#298] opened 2018-04-25 17:27 UTC
Trying to open BUILD file or import project into causes Fatal error
IntelliJ IDEA 2018.1.2 (Ultimate Edition)
Build #IU-181.4668.68, built on April 24, 2018
JRE: 1.8.0_152-release-1136-b29 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.4

Steps to reproduce: get kubernetes sources (https://github.com/kubernetes/kubernetes ) and try to import this project

**Comment by chaoren** [comment] 2018-04-25 19:39
Can you share the exact project view (bazelproject file)? 
What's the exact error you're getting?
What version of the bazel plugin are you using?

**Comment by chaoren** [comment] 2018-04-25 21:31
> setup project (no bazel plugin installed) and all was OK

Are you actually using bazel to build? You don't need the bazel plugin if you're not building with bazel.

> After IJ restart the project would not open with Fatal error. 

What is the error? Copy and paste the exact error text / stacktrace please.

**Comment by kgignatyev-inspur** [comment] 2018-04-26 17:36
![image](https://user-images.githubusercontent.com/27866311/39321966-4df837ee-493d-11e8-96f8-299fb05c1e3c.png)

2018-04-26 10:32:41,005 [   4880]   INFO - llij.ide.plugins.PluginManager - Loaded bundled plugins: Android Support (10.3.0), Ant Support (1.0), AspectJ Support (1.2), CSS Support (181.4668.68), CVS Integration (11), Copyright (8.1), Coverage (181.4668.68), DSM Analysis (1.0.0), Database Tools and SQL (181.4668.68), Eclipse Integration (3.0), EditorConfig (181.4668.68), Gherkin (999.999), Git Integration (8.1), GitHub (181.4668.68), Gradle (181.4668.68), Groovy (9.0), Guice (8.0), HTML Tools (2.0), HTTP Client (181.4668.68), Haml (181.4668.68), I18n for Java (181.4668.68), IDE Settings Sync (181.4668.68), IDEA CORE (181.4668.68), IntelliLang (8.0), JUnit (1.0), Java Bytecode Decompiler (181.4668.68), Java EE: EJB, JPA, Servlets (1.0), Java Server Pages (JSP) Integration (1.0), Java Stream Debugger (181.4668.68), JavaScript Debugger (1.0), JavaScript Support (1.0), Kotlin (1.2.31-release-IJ2018.1-1), Less support (181.4668.68), Markdown support (181.4668.68), Maven Integration (181.4668.68), Maven Integration Extension (181.4668.68), Persistence Frameworks Support (1.0), Properties Support (181.4668.68), QuirksMode (181.4668.68), Reactor framework support (1.0), Refactor-X (2.01), Sass support (181.4668.68), Settings Repository (181.4668.68), Smali Support (1.0), Spring AOP/@AspectJ (1.0), Spring Batch (1.0), Spring Boot (1.0), Spring MVC (1.0), Spring Support (1.0), Stylus support (999.999), Subversion Integration (1.1), Task Management (1.0), Terminal (0.1), TestNG-J (8.0), Time Tracking (1.0), Velocity support (1.0), W3C Validators (2.0), YAML (181.4668.68), ZKM-Unscramble (1.0) 
2018-04-26 10:32:41,005 [   4880]   INFO - llij.ide.plugins.PluginManager - Loaded custom plugins: .ignore (2.6.1), Angular Material 2, Flex layout 1, Teradata Covalent 1 & Material icon live templates (0.11.0), AsciiDoc (0.20.2), BashSupport (1.6.13.181), Bazel (2018.01.02.0.1), CSV Plugin (1.6.0), Docker integration (181.4203.550), Go (181.4445.53.182), Handlebars/Mustache (181.3741.1), HashiCorp Terraform / HCL language support (0.6.10), Ini4Idea (181.3741.23), Kubernetes and OpenShift Resource Support (0.9), Lua (1.0.112), Python (2018.1.181.4445.78), Scala (2018.1.9), YAML/Ansible support (0.9.5), nginx Support (0.1.6) 
2018-04-26 10:32:41,005 [   4880]   INFO - llij.ide.plugins.PluginManager - Disabled plugins: ASP (0.1), AngularJS (181.4668.68), Application Servers View (0.2.0), Bytecode Viewer (0.1), CFML Support (3.53), Cloud Foundry integration (1.0), CloudBees integration (1.0), CoffeeScript (181.4668.68), Cucumber for Groovy (181.4668.68), Cucumber for Java (181.4668.68), Emma (181.4668.68), Flash/Flex Support (181.4668.68), FreeMarker support (1.0), GWT Support (1.0), Geronimo Integration (1.0), GlassFish Integration (1.0), Google App Engine Integration (1.1.4), Grails (9.0), Heroku integration (181.4668.68), Hibernate Support (1.0), J2ME (1.0), JBoss Arquillian Support (1.0), JBoss Drools Support (1.0), JBoss Frameworks Base Support (1.0), JBoss Integration (1.0), JBoss Seam Pageflow Support (1.0), JBoss Seam Pages Support (1.0), JBoss Seam Support (1.0), JBoss jBPM (2.0.0), JSR45 Integration (1.0), Java EE: Batch Applications (1.0), Java EE: Bean Validation Support (1.1), Java EE: Contexts and Dependency Injection (1.1), Java EE: JMS, JSON Processing, Concurrency, Transaction  (1.0), Java EE: Java Server Faces (2.2.X.), Java EE: RESTful Web Services (JAX-RS) (1.0), Java EE: Web Services (JAX-WS) (1.9), Java EE: WebSockets (1.0), JavaFX (1.0), JavaScript Intention Power Pack (0.9.4), Jetty Integration (1.0), Mercurial Integration (10.0), OpenShift integration (1.0), Osmorc (1.4.11), Perforce Integration (2.0), Playframework Support (1.0), Plugin DevKit (1.0), Remote Hosts Access (0.1), Resin Integration (8.1), SSH Remote Run (0.1), Spring Data (1.0), Spring Integration Patterns (1.0), Spring OSGi (1.0), Spring Security (1.0), Spring Web Flow (1.0), Spring Web Services (1.0), Spring WebSocket (1.0), Spy-js (181.4668.68), Struts 1.x (2.0), Struts 2 (1.0), TFS Integration (999.999), Tapestry support (1.0), Thymeleaf (1.0), Tomcat and TomEE Integration (1.0), UI Designer (181.4668.68), UML Support (1.0), Vaadin Support (1.0), WebLogic Integration (1.0), WebSphere Integration (1.0), XPathView + XSLT Support (4), XSLT-Debugger (1.4), dmServer Support (0.9.5), tslint (181.4668.68) 
2018-04-26 10:32:42,245 [   6120]   INFO - cloudConfig.CloudConfigManager - === Exit: JBA_NOT_FOUND === 
2018-04-26 10:32:42,314 [   6189]   INFO - ellij.util.io.PagedFileStorage - lower=100; upper=500; buffer=10; max=705 
2018-04-26 10:32:42,442 [   6317]   INFO - pl.local.NativeFileWatcherImpl - Starting file watcher: /Applications/IntelliJ IDEA.app/Contents/bin/fsnotifier 
2018-04-26 10:32:42,451 [   6326]   INFO - pl.local.NativeFileWatcherImpl - Native file watcher is operational. 
2018-04-26 10:32:42,623 [   6498]   INFO - pi.util.registry.RegistryState - Registry values changed by user: 
2018-04-26 10:32:42,623 [   6498]   INFO - pi.util.registry.RegistryState -   SBT.system.in.process = true 
2018-04-26 10:32:42,623 [   6498]   INFO - pi.util.registry.RegistryState -   ide.windowSystem.autoShowProcessPopup = true 
2018-04-26 10:32:43,515 [   7390]   INFO - com.intellij.ide.ui.UISettings - Loaded: fontSize=16, fontScale=0.0; restored: fontSize=16, fontScale=1.0 
2018-04-26 10:32:43,624 [   7499]   WARN - nSystem.impl.ActionManagerImpl - keymap "Xcode" not found [Plugin: Git4Idea] 
2018-04-26 10:32:43,880 [   7755]   INFO -     #com.intellij.util.ui.JBUI - User scale factor: 1.25 
2018-04-26 10:32:43,933 [   7808]   INFO - .openapi.application.Preloader - Finished preloading com.intellij.ide.ui.OptionsTopHitProvider$Activity@6f10d777 
2018-04-26 10:32:44,019 [   7894]   INFO - til.net.ssl.CertificateManager - Default SSL context initialized 
2018-04-26 10:32:44,032 [   7907]   INFO - lij.diagnostic.DebugLogManager - Set DEBUG for the following categories:  
2018-04-26 10:32:44,058 [   7933]   INFO - rains.ide.BuiltInServerManager - built-in server started, port 63342 
2018-04-26 10:32:44,125 [   8000]   INFO - gs.impl.UpdateCheckerComponent - channel: release 
2018-04-26 10:32:44,393 [   8268]   INFO - il.indexing.FileBasedIndexImpl - Index exts enumerated:213, number of extensions:63 
2018-04-26 10:32:44,398 [   8273]   INFO - il.indexing.FileBasedIndexImpl - Index scheduled:4 
2018-04-26 10:32:44,436 [   8311]   INFO - il.indexing.FileBasedIndexImpl - Version has changed for index filetypes. The index will be rebuilt. 
2018-04-26 10:32:44,457 [   8332]   INFO - tellij.psi.stubs.StubIndexImpl - All stub exts enumerated:54, number of extensions:146 
2018-04-26 10:32:44,459 [   8334]   INFO - tellij.psi.stubs.StubIndexImpl - stub exts update scheduled:1 
2018-04-26 10:32:44,759 [   8634]   INFO - ndex.PrebuiltIndexProviderBase - Prebuilt id-index indices are missing for Python 
2018-04-26 10:32:44,876 [   8751]   INFO - il.indexing.FileBasedIndexImpl - Version has changed for index IdIndex. The index will be rebuilt. 
2018-04-26 10:32:45,013 [   8888]   INFO - pi.util.registry.RegistryValue - Registry value 'SBT.system.in.process' has changed to 'true" 
2018-04-26 10:32:45,319 [   9194]   INFO -            PyTestLegacyInterop - Disabling com.jetbrains.python.testing.unittestLegacy.PythonUnitTestConfigurationProducer@1f896cff 
2018-04-26 10:32:45,321 [   9196]   INFO -            PyTestLegacyInterop - Disabling com.jetbrains.python.testing.pytestLegacy.PyTestConfigurationProducer@c16efd0 
2018-04-26 10:32:45,322 [   9197]   INFO -            PyTestLegacyInterop - Disabling com.jetbrains.python.testing.nosetestLegacy.PythonNoseTestConfigurationProducer@b797e09 
2018-04-26 10:32:45,323 [   9198]   INFO - plication.impl.ApplicationImpl - 125 application components initialized in 5626ms 
2018-04-26 10:32:45,426 [   9301]   INFO - .intellij.idea.IdeaApplication - App initialization took 10052 ms 
2018-04-26 10:32:45,490 [   9365]   INFO - ij.psi.stubs.StubUpdatingIndex - requesting complete stub index rebuild due to changes: added file types:BUILD,projectview; 
2018-04-26 10:32:45,491 [   9366]   INFO - il.indexing.FileBasedIndexImpl -  
java.io.IOException
	at com.intellij.psi.stubs.StubVersionMap.updateState(StubVersionMap.java:127)
	at com.intellij.psi.stubs.StubVersionMap.<init>(StubVersionMap.java:69)
	at com.intellij.psi.stubs.StubUpdatingIndex$MyIndex.<init>(StubUpdatingIndex.java:427)
	at com.intellij.psi.stubs.StubUpdatingIndex.createIndexImplementation(StubUpdatingIndex.java:367)
	at com.intellij.util.indexing.FileBasedIndexImpl.createIndex(FileBasedIndexImpl.java:483)
	at com.intellij.util.indexing.FileBasedIndexImpl.initIndexStorage(FileBasedIndexImpl.java:415)
	at com.intellij.util.indexing.FileBasedIndexImpl.registerIndexer(FileBasedIndexImpl.java:376)
	at com.intellij.util.indexing.FileBasedIndexImpl.access$5200(FileBasedIndexImpl.java:117)
	at com.intellij.util.indexing.FileBasedIndexImpl$FileIndexDataInitialization.lambda$new$1(FileBasedIndexImpl.java:2362)
	at com.intellij.util.indexing.IndexInfrastructure$DataInitialization.executeNestedInitializationTask(IndexInfrastructure.java:214)
	at com.intellij.util.indexing.IndexInfrastructure$DataInitialization.runParallelNestedInitializationTasks(IndexInfrastructure.java:202)
	at com.intellij.util.indexing.IndexInfrastructure$DataInitialization.call(IndexInfrastructure.java:165)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2018-04-26 10:32:45,659 [   9534]   INFO - com.intellij.ide.ui.UISettings - Loaded: fontSize=12, fontScale=1.0; restored: fontSize=12, fontScale=1.0 
2018-04-26 10:32:45,703 [   9578]   INFO - com.intellij.ide.ui.UISettings - Loaded: fontSize=20, fontScale=null; restored: fontSize=20, fontScale=1.0 
2018-04-26 10:32:45,703 [   9578]   INFO - com.intellij.ide.ui.UISettings - Loaded: fontSize=18, fontScale=null; restored: fontSize=18, fontScale=1.0 
2018-04-26 10:32:45,711 [   9586]   INFO - ij.psi.stubs.StubUpdatingIndex - Following new file types will be indexed:Bash,Less,XML,Handlebars/Mustache,Groovy,Kotlin,JAVA,Jinja2,Markdown,JSX Harmony,CLASS,Mako,SCSS,Ini,JavaScript,TypeScript JSX,ECMAScript 6,Play2,kotlin_builtins,spring.factories,Go,Flow,Sass,BUILD,projectview,KJSM,HTML,CSS,ActionScript,Scala,Stylus,AspectJ,Properties,PythonStub,SQL,Python,TypeScript,Lua,Cython,sbt,JSP,Go template 
2018-04-26 10:32:45,959 [   9834]   INFO - pl$FileIndexDataInitialization - Initialization done:1560 
2018-04-26 10:32:46,197 [  10072]   INFO - exImpl$StubIndexInitialization - Initialization done:238 
2018-04-26 10:32:46,781 [  10656]   INFO - j.ide.ui.OptionsTopHitProvider - 773 ms spent to cache options in application 
2018-04-26 10:32:46,946 [  10821]   INFO - .openapi.application.Preloader - Finished preloading com.intellij.openapi.actionSystem.impl.ActionPreloader@30e7b116 
2018-04-26 10:32:48,267 [  12142]   INFO - .openapi.application.Preloader - Finished preloading com.intellij.ide.ui.search.SearchableOptionPreloader@5ae65bc4 
2018-04-26 10:32:49,117 [  12992]   INFO - .openapi.application.Preloader - Finished preloading com.intellij.codeInsight.completion.CompletionPreloader@ba00500 
2018-04-26 10:32:49,132 [  13007]   INFO - .openapi.application.Preloader - Finished preloading com.intellij.ide.actions.GotoClassPresentationUpdater@491125f 
2018-04-26 10:32:50,703 [  14578]   INFO - ellij.project.impl.ProjectImpl - 26 project components initialized in 230 ms 
2018-04-26 10:33:33,200 [  57075]   INFO - roject.impl.ProjectManagerImpl - Fatal error initializing plugin com.google.idea.bazel.ijwb 
com.intellij.ide.plugins.PluginManager$StartupAbortedException: Fatal error initializing plugin com.google.idea.bazel.ijwb
	at com.intellij.ide.plugins.PluginManager.handleComponentError(PluginManager.java:252)
	at com.intellij.openapi.components.impl.PlatformComponentManagerImpl.handleInitComponentError(PlatformComponentManagerImpl.java:43)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.registerComponents(ComponentManagerImpl.java:388)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:83)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:77)
	at com.intellij.openapi.project.impl.ProjectImpl.init(ProjectImpl.java:262)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.initProject(ProjectManagerImpl.java:274)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.newProject(ProjectManagerImpl.java:190)
	at com.intellij.openapi.project.ex.ProjectManagerEx.createProject(ProjectManagerEx.java:74)
	at com.intellij.ide.util.projectWizard.ProjectBuilder.createProject(ProjectBuilder.java:77)
	at com.intellij.ide.impl.NewProjectUtil.a(NewProjectUtil.java:110)
	at com.intellij.ide.impl.NewProjectUtil.createFromWizard(NewProjectUtil.java:76)
	at com.google.idea.blaze.java.wizard2.BlazeImportProjectAction.actionPerformed(BlazeImportProjectAction.java:33)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.invokeAction(ActionUtil.java:337)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.invokeAction(ActionUtil.java:324)
	at com.intellij.ui.components.labels.ActionLink$1.linkSelected(ActionLink.java:60)
	at com.intellij.ui.components.labels.LinkLabel.doClick(LinkLabel.java:142)
	at com.intellij.ui.components.labels.ActionLink.doClick(ActionLink.java:69)
	at com.intellij.ui.components.labels.LinkLabel$MyMouseHandler.mouseReleased(LinkLabel.java:319)
	at java.awt.Component.processMouseEvent(Component.java:6541)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3325)
	at java.awt.Component.processEvent(Component.java:6306)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4897)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:779)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:716)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:395)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: com.intellij.diagnostic.PluginException: com/goide/runconfig/application/GoApplicationRunConfigurationProducer [Plugin: com.google.idea.bazel.ijwb]
	... 53 more
Caused by: java.lang.NoClassDefFoundError: com/goide/runconfig/application/GoApplicationRunConfigurationProducer
	at com.google.idea.blaze.golang.run.producers.NonBlazeProducerSuppressor.<clinit>(NonBlazeProducerSuppressor.java:30)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.registerComponents(ComponentManagerImpl.java:369)
	... 50 more
Caused by: java.lang.ClassNotFoundException: com.goide.runconfig.application.GoApplicationRunConfigurationProducer PluginClassLoader[com.google.idea.bazel.ijwb, 2018.01.02.0.1] com.intellij.ide.plugins.cl.PluginClassLoader@3c1a8602
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:63)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 54 more

**Comment by brendandouglas** [comment] 2018-04-26 17:47
We don't yet support 2018.1 -- closing as a dupe of https://github.com/bazelbuild/intellij/issues/290.

Until we release a plugin version compatible with 2018.1, the workaround is to downgrade to 2017.3.

**Closed by brendandouglas** 2018-04-26 17:47 UTC
