### ISSUE TITLE
TEST_SRCDIR is not set on environment when debugging C++

### ISSUE THREAD

**Issue by jwnimmer-tri** [bazelbuild/intellij#256] opened 2018-03-13 17:58 UTC
(This is similar to #193, which has a bit more exposition.  I'm fine if you want to close this as a duplicate and generalize that issue to be for all languages.)

Ideally, `$TEST_SRCDIR` should always be set for tests according to [test-encyclopedia.html](https://docs.bazel.build/versions/master/test-encyclopedia.html#initial-conditions).

I have C++ unit tests with `data = []` resources that we want to load from our runfiles.  Running the tests as normal works, but in `Debug...` the `$TEST_SRCDIR` is not set and we explode.

I understand the worry of brittle duplication of the entire encyclopedia of variables within this plug-in.  However, within the list of `required` only a few are unique to Bazel (versus overriding OS defaults for hermeticity), and `$TEST_SRCDIR` stands out as a unique exception because of the key piece it plays.  (Even `$TEST_TMPDIR` isn't critical, because we can fall-back to other helpers instead.)

So I'd guess I'd like to advocate for fixing this one variable sooner rather than later, without implying that the plug-in has to support all of them until a new debugging architecture can land.

**Comment by jin** [comment] 2019-04-24 20:55
Closing this as a dupe of #193, and generalized that issue's title.

**Closed by jin** 2019-04-24 20:55 UTC
