### ISSUE TITLE
Intellij with Bazel plugin changes variable names / types in debug mode

### ISSUE THREAD

**Issue by IanWoods1993** [bazelbuild/intellij#93] opened 2017-05-31 19:56 UTC
Output of running `bazel version` on command line:
```
Build label: 0.4.5-homebrew
Build target: bazel-out/local-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Mar 16 13:37:54 2017 (1489671474)
Build timestamp: 1489671474
Build timestamp as int: 1489671474
```

IntelliJ version 2017.1.2

When debugging some code using the Bazel with IntelliJ plugin, I found that variable names are sometimes lost:

(All screenshots were taken while the program was paused in the exact same place)

![screen shot 2017-05-31 at 12 49 12 pm](https://cloud.githubusercontent.com/assets/2335115/26650940/f98e07e2-45ff-11e7-9ca0-7ad04eeb6ed5.png)

Here you can see that some variables are just referred to as "slot_n". This makes debugging tough because it's not always clear which variable is in which slot.

![screen shot 2017-05-31 at 12 48 52 pm](https://cloud.githubusercontent.com/assets/2335115/26650919/e8049dce-45ff-11e7-9782-3c5ea1385279.png)

Here you can see, in conjunction with the above image, that data types are changed for debug mode. The variable "name" is a String, and one line later, it has changed to a TextNode (from the Jackson library (com.fasterxml.jackson.databind.node). The actual running process does not alter its type, but the debugger has.

Changing data types are perhaps an even bigger impediment to debugging than disappearing names - conditional breakpoints and expression evaluation no longer reflect the actual state of the code. 

Let me know if any of this is unclear / you need additional information. Thanks.

**Comment by brendandouglas** [comment] 2017-05-31 20:06
Try the workaround in #78 -- add these lines to your .bazelproject file:
```
build_flags:
  --javacopt="-g"
```

Closing as a dupe of #78. A better fix will have to wait for bazelbuild/bazel#2859.

**Closed by brendandouglas** 2017-05-31 20:06 UTC

**Comment by IanWoods1993** [comment] 2017-05-31 20:40
Sorry I didn't check for duplicates. That was dumb. Thanks a bunch for the quick response.

**Comment by brendandouglas** [comment] 2017-05-31 23:24
No worries at all. I already knew there was a dupe and it still took a couple of searches to find it!
