### ISSUE TITLE
Fail to import projects

### ISSUE THREAD

**Issue by SalzzZ** [bazelbuild/intellij#18] opened 2016-09-09 07:49 UTC
When trying to import ijwb/.bazelproject or a simple project + creating .bazelproject from scratch (1 source file + 1 "java_library" target), in intellij idea ultimate 2016.2.3 and plugin version 1.8.3, 
I get the error "Error:Could not get Bazel roots". Here's the stacktrace. What should I check? Running `bazel info` from the CLI works flawlessly

```
    com.google.idea.blaze.base.command.info.BlazeInfoException: blaze info failed with exit code: 37 and error stream: .
    Server finished RPC without an explicit exit code
    java.util.concurrent.ExecutionException: com.google.idea.blaze.base.command.info.BlazeInfoException: blaze info failed with exit code: 37 and error stream: Server finished RPC without an explicit exit code
        at com.google.common.util.concurrent.AbstractFuture$Sync.getValue(AbstractFuture.java:299)
        at com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:286)
        at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:116)
        at com.google.idea.blaze.base.async.FutureUtil$Builder.lambda$run$0(FutureUtil.java:89)
        at com.google.idea.blaze.base.scope.Scope.push(Scope.java:44)
        at com.google.idea.blaze.base.async.FutureUtil$Builder.run(FutureUtil.java:81)
        at com.google.idea.blaze.base.sync.BlazeSyncTask.doSyncProject(BlazeSyncTask.java:206)
        at com.google.idea.blaze.base.sync.BlazeSyncTask.syncProject(BlazeSyncTask.java:157)
        at com.google.idea.blaze.base.sync.BlazeSyncTask.lambda$run$0(BlazeSyncTask.java:144)
        at com.google.idea.blaze.base.scope.Scope.push(Scope.java:72)
        at com.google.idea.blaze.base.scope.Scope.root(Scope.java:61)
        at com.google.idea.blaze.base.sync.BlazeSyncTask.run(BlazeSyncTask.java:117)
        at com.google.idea.blaze.base.async.executor.BlazeExecutor$2.run(BlazeExecutor.java:109)
        at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:170)
        at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:494)
        at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
        at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
        at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:155)
        at com.google.idea.blaze.base.async.executor.BlazeExecutor$3.call(BlazeExecutor.java:115)
        at com.google.idea.blaze.base.async.executor.BlazeExecutor$3.call(BlazeExecutor.java:112)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
    Caused by: com.google.idea.blaze.base.command.info.BlazeInfoException: blaze info failed with exit code: 37 and error stream: .
    Server finished RPC without an explicit exit code
        at com.google.idea.blaze.base.command.info.BlazeInfoImpl.runBlazeInfo(BlazeInfoImpl.java:85)
        at com.google.idea.blaze.base.command.info.BlazeInfoImpl.lambda$runBlazeInfo$2(BlazeInfoImpl.java:60)
        ... 4 more
```

**Comment by brendandouglas** [comment] 2016-09-09 15:27
Hi SalzzZ, which version of the plugin are you using? If it's prior to v1.8, could you please update (unfortunately we had to change the plugin ID, so if you're on a version prior to 1.8, you'll need to uninstall the existing plugin before updating)

**Comment by brendandouglas** [comment] 2016-09-12 14:25
Could you paste the bazel command that shows up in the 'Bazel Console' window when you sync?
(it should look something like "/path/to/bazel info --tool_tag=ijwb:IDEA:ultimate --")

**Comment by SalzzZ** [comment] 2016-09-14 03:01
Hi @brendandouglas, the plugin version is 1.8.3, here's the output on bazel console:
```
Syncing project...
Command: /home/salvian/bazel/output/bazel info --tool_tag=ijwb:IDEA:ultimate --

Running Bazel info...
Sync failed

==== TIMING REPORT ====

Sync: 2.9s (282ms)
    BazelRoots: 2.6s
``` 
I'm using compiled-from-source bazel, with the repository cloned to `/home/salvian/bazel`

**Comment by brendandouglas** [comment] 2016-09-15 14:28
I haven't been able to reproduce this yet, but if the same command is working outside IntelliJ it's likely caused by differing environment variables (e.g. $JAVA_HOME or similar).

Does the same command succeed when run from the terminal window inside IJ (View > Tool Windows > Terminal)?

**Comment by SalzzZ** [comment] 2016-09-16 03:36
in intellij terminal, the command fails the first time
but then I realized it's run in the project-data directory, not in the workspace directory
when I `cd` to workspace dir, it succeed.
```
workspace dir: `/home/salvian/project`
project-data dir: `/home/salvian/project-00`
(project-data term and directory are from the bazel plugin; what's this directory for, btw?) 
```

**Comment by mmm444** [comment] 2016-09-30 18:07
After some struggling I have found that the reason for me is that the plugin invokes bazel client with a corrupted environment. In my case one of the entries in the `char **environ` available in the bazel client array contains only one char `'\x05'` and no equals sign. The client passes this information to the bazel server and it fails.

I don't know how the corruption can happen. I will try to investigate more. It may be a JVM bug near the `Process` class or something. I run Ubuntu Linux 16.04.1 on x86_64 with 4.4.0-36-generic kernel and IDEA Ultimate 2016.2.4 on Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode) with plugin version 1.8.3.

It is trivial to filter out the bad environment entries in the client and the problem goes away. Shall I submit a patch to bazel? Or would you rather see it fixed here on the plugin side?

**Comment by SalzzZ** [comment] 2016-10-03 00:11
+1, would be great if plugin-side fix is possible
thanks

**Comment by brendandouglas** [comment] 2016-10-03 13:48
Thanks for tracking down the cause @mmm444.

The plugin itself isn't modifying the environment in these cases. We could try to remove any existing corruption via ProcessBuilder::enviroment, but that looks potentially problematic.

Unless there's a way to remove the corruption prior to loading IntelliJ, a bazel-side patch might be the best option.

**Comment by mmm444** [comment] 2016-10-11 14:50
I have put some more time into this but had no luck. I found out that `ProcessBuilder.evironment()` contains no corruption by the time the plugin launches the bazel subprocess. Also `/proc/<pid>/environ` is fine for the IDEA process. When I replaced bazel binary with a stub that only reports the corruption it was _most of the times_ there. I tried looking into how the JRE launches subprocesses and it is pretty complicated. I assume the bug is somewhere there but I am not sure. I cannot replicate this behavior outside of IDEA in a standalone test.

I will try to submit a workaround to bazel.

**Comment by SalzzZ** [comment] 2016-10-13 06:26
We've got other 2 workarounds to try:
- Open idea with JAVA_HOME set (instead of custom jre bundled with newer version of idea). This worked for my coworker
- [Using Bazel custom API repository](https://www.bazel.io/versions/master/docs/install.html#using-bazel-custom-api-repository-recommended) instead of compiling from source. This worked for me

My coworker also found a problem related to the proto_deps.jar not being compatible with the latest version of bazel.

Btw the plugin seems to be tied to a specific version of intellij (2016.2.1, and the link in WORKSPACE is broken). Can it be decoupled so we can use any idea version?

**Comment by brendandouglas** [comment] 2016-10-13 13:23
Thank you @mmm444 for investigating this, and @SalzzZ for the workarounds. Interesting that the problem doesn't occur using on older version of bazel.

I haven't been using the JDK bundled with IJ, which might explain the difficulty reproducing.

Could you raise a separate issue for the proto_deps compatibility bug, with some extra details? The intention has been to make proto changes which are both forwards and backwards compatible, though we can't always achieve that.

For the IJ versioning -- the IJ plugin API changes between versions, so we're tied to a narrow range of versions. Supporting multiple legacy versions from HEAD would involve too much additional code complexity. You can still use this plugin with older versions, by installing it from the JetBrains plugin repo (which will only serve compatible plugin versions).

We're in the process of upgrading to 2016.2.4, and will update the links in this repository, in the next code drop.

**Comment by brendandouglas** [comment] 2017-03-03 13:55
I don't believe there's a practical plugin-side fix here, so closing this for bug hygiene reasons.

**Closed by brendandouglas** 2017-03-03 13:55 UTC
