### ISSUE TITLE
Bazel incompatible flags

### ISSUE THREAD

**Issue by brown** [bazelbuild/intellij#625] opened 2019-04-08 14:35 UTC
I recently removed all the incompatible Bazel flags from my employer's bazelrc file and set all_incompatible_changes to true, so I could track down and fix any local uses of deprecated features.  After I committed the changes I discovered that the IntelliJ Bazel plugin relies on several features that have been deprecated for some time.

It would make life easier for users of the plugin if uses of deprecated Bazel features were removed from the plugin code in a more timely manner.

**Comment by brown** [comment] 2019-04-08 14:40
Alternatively, perhaps the plugin could invoke Bazel with all the incompatible flags it needs, so that setting all_incompatible_changes to true in a bazelrc would not cause the plugin trouble.

**Comment by brendandouglas** [comment] 2019-04-08 17:14
Closing as a dupe of https://github.com/bazelbuild/intellij/issues/529

**Closed by brendandouglas** 2019-04-08 17:14 UTC
