### ISSUE TITLE
Cannot find "\bin\bash" when debugging with IntelliJ

### ISSUE THREAD

**Issue by jojenki** [bazelbuild/intellij#229] opened 2018-02-04 01:55 UTC
I have an app that runs locally. There is some bug, so I want to run it using the debugger. However, when I click debug, I get the following error:

```
Error running 'Bazel run client:Test'
Cannot run program "\bin\bash" (in directory "<directory_to_my_project>"): CreateProcess error=2, The system cannot find the file specified
```

I'm guessing that someone (me or Bazel's install) forgot to set some environment variable somewhere and that command ("\bin\bash") should be prefaced with something. I have been digging a little but aren't coming up with anything. Thoughts?

**Comment by brendandouglas** [comment] 2018-02-05 12:44
Which environment, OS are you running in?

**Comment by jojenki** [comment] 2018-02-06 04:11
Windows 10 (not 10.1), and I have the latest updates
IntelliJ Community 2017.3

It _runs_ just fine both in the command line and IntelliJ, but IntelliJ's debugger throws that error.

**Comment by brendandouglas** [comment] 2018-02-06 13:30
We don't yet support Windows (I suspect project sync won't work either). It's something we plan to eventually do, but we have no concrete timeline.

I'll close this as a dupe of https://github.com/bazelbuild/intellij/issues/113

**Closed by brendandouglas** 2018-02-06 13:30 UTC

**Comment by jesseschalken** [comment] 2021-04-06 06:55
Reading the code, it seems it only needs `/bin/bash` if hot swapping is enabled, and can be controlled via an "experiment" called `java.hotswapping.enabled` which defaults to `true`.

If you open "Help > Edit Custom Properties..." and add

```
blaze.experiment.java.hotswapping.enabled=0
```

it will turn hot swapping off, and debugging on Windows seems to work.

According to the code, you can also try adding `java.hotswapping.enabled=0` to `~/.intellij-experiments`, but I haven't tested it.
