### ISSUE TITLE
Allow setting bazel binary path externally (without UI interactions)

### ISSUE THREAD

**Issue by talya** [bazelbuild/intellij#405] opened 2018-09-04 11:20 UTC
Our use case:
To allow developing from the IDE on a mac OSx, with bazel running inside a local docker container.

In order to make this work we change the bazel binary to a local shim wrapper. 
We would like to make this step automated, preferably without modifying the `blaze.user.settings.xml`?

@brendandouglas wdyt?

**Comment by brendandouglas** [comment] 2018-09-04 12:28
We already default to using the path mappings set when launching the IDE -- would it be enough to just set the $bazel path mapping before launching?

There's also the option of syncing user settings between IDE instances, which seems like it would useful for this purpose.

**Comment by talya** [comment] 2018-09-05 13:57
We'd prefer not to change the bazel on user's PATH, in order to allow ppl to still run with native bazel if they so wish.

Using synced shared settings sounds interesting but still requires manual steps to configure.

Wdyt about adding an environment variable such as `IDEA_BAZEL_BINARY`, which if set would take priority? Perhaps with an additional checkbox in the UI to allow overriding with the env var?

This ties in nicely with one other feature [request](407) we opened and would result in 2 similar behaving env variables.

@hmemcpy

**Comment by hmemcpy** [comment] 2018-09-05 14:38
Just curious, @jgavris, do you build a custom bazel version?

We initially thought about using a `.bazelproj`, but we didn't want to put an additional burden on our users having to re-import projects, and hoped our "installer" script could handle everything. An environment variable seems least intrusive and doesn't require modifying physical setting files on the user's machine.

Together with another environment variable for setting up BEP (as outlined in #407), we will have a good solution of running a completely customized bazel (in our case, inside a docker on mac)

**Comment by jgavris** [comment] 2018-09-05 14:43
It's not a custom version, it's just a submodule in our repo so we can have 100% reproducible builds without relying on a system package manager to pin. It would expensive for our users and CI to have to run the system package manager if there was a bazel version bump when they changed branches / revisions.

In general, we've been trying to move away from environment variables as they are a burden to less technical users. They also require users to launch Android Studio (or Xcode for example) from the shell, or to go into their config and explicitly set them up. Having these inside the repository in the project file in a declarative manner seems ideal to me.

**Comment by brendandouglas** [comment] 2018-09-12 15:28
Note, you can use nested .bazelproject files.

Having a shim.bazelproject containing all the settings for that particular environment seems the best solution here.

Otherwise, why don't you want to modify the settings xml file?

**Comment by brendandouglas** [comment] 2018-09-13 18:50
In this case, you'd have a custom .bazelproject file importing the standard one, adding whatever custom settings were required.

**Comment by talya** [comment] 2018-09-14 11:40
So it sounds like a custom .bazelproject file would still put an additional burden on our users by having to re-import projects and manually so for every new project.

How about having a .bazelpluginrc in the user home folder, similar to .bashrc files?
This would be ideal for our use case as we could handle this in our automated installer.

Or another direction - have a file named .default.bazelproject in the workspace root that would automatically be added/imported for the project if it exists.

**Comment by talya** [comment] 2018-09-16 08:08
So, after trying this out to see the import behaviour, we're ok with having a checked in .bazelproject file that will contain this bazel_binary setting (and the bep file path mentioned in #407 ).
This would allow us to centrally manage it and still allow ppl to locally add any other properties they need (and we'd probably add the local `.project/.bazelproject` to gitignore to be on the safe side)

I would like to suggest one thing that would greatly improve the UX of this -  If a default file exists (based on some convention, perhaps a `.default.bazelproject` in the workspace root, or a `.bazelproject` under an ijwb folder etc.) - then the import ui dialog would automatically suggest to import this default file (currently it doesn't even display it in the dropdownlist).

wdyt?

(@ittaiz fyi)

**Comment by ittaiz** [comment] 2018-09-28 09:14
@brendandouglas how can we move forward? It would really help us to be able to configure the two properties from the .bazelproject (hopefully alongside changing the default like @talya mentioned)

**Comment by ittaiz** [comment] 2018-10-06 08:46
@brendandouglas ping? We're blocked with manual error-prone processes now...

**Comment by brendandouglas** [comment] 2018-10-08 15:37
For the suggested defaults change, the dropdown list is currently just recently selected .bazelproject files. Would you be interested in taking a look at this, and opening a pull request?

For the change to the bazel binary (optionally specifying it in the project view file), this should probably hook in to BazelBuildSystemProvider#getBinaryPath. I've added this upstream, and it will be available in the next release (scheduled for next Friday).

**Comment by hmemcpy** [comment] 2018-10-09 08:11
Would this mean, ideally, adding a custom section in the `.buildproject`?

**Comment by hmemcpy** [comment] 2018-11-28 09:57
I believe we can close this, since `bazel_binary` is now a configurable option in `.bazejproject`. 
We'd like to discuss a PR to allow pre-populating a default `.bazelproject` file in the import dialog, to make the UX easier. But, this is a separate issue.
Agreed, @talya?

**Closed** 2018-11-28 15:11 UTC
