### ISSUE TITLE
[Bazel CI] Error in label_list: Illegal argument: element in 'providers' is of unexpected type


### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/intellij#7078] opened 2024-11-29 04:26 UTC
CI: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4299#0193761a-8742-4c74-ba52-e0de8d16c875

 Platform: Ubuntu, Windows, MacOS

 Logs: 
```
ERROR: Traceback (most recent call last):
	File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/87020f10bfd322927fd655fa30af34a6/external/io_bazel_rules_scala/scala/private/common_attributes.bzl", line 18, column 28, in <toplevel>
		"deps": attr.label_list(
Error in label_list: Illegal argument: element in 'providers' is of unexpected type. Either all elements should be providers, or all elements should be lists of providers, but got list with an element of type NoneType.
ERROR: error loading package '': at /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/87020f10bfd322927fd655fa30af34a6/external/io_bazel_rules_scala/scala/scala.bzl:16:5: at /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/87020f10bfd322927fd655fa30af34a6/external/io_bazel_rules_scala/scala/private/rules/scala_binary.bzl:5:5: initialization of module 'scala/private/common_attributes.bzl' failed
Traceback (most recent call last):
  File "bazelci.py", line 4496, in <module>
    sys.exit(main())
  File "bazelci.py", line 4474, in main
    bazel_version=task_config.get("bazel") or configs.get("bazel"),
  File "bazelci.py", line 1214, in execute_commands
    bazel_version = print_bazel_version_info(bazel_binary, platform)
  File "bazelci.py", line 1512, in print_bazel_version_info
    [bazel_binary] + common_startup_flags() + ["--nosystem_rc", "--nohome_rc", "info"]
  File "bazelci.py", line 2656, in execute_command
    subprocess.PIPE if capture_stderr else None
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['bazel', '--nosystem_rc', '--nohome_rc', 'info']' returned non-zero exit status 1.
🚨 Error: The command exited with status 1
``` 

 CC Greenteam @comius

**Comment by sgowroji** [comment] 2024-11-29 04:30
CLion Plugin (CLion Linux OSS Oldest Stable ): https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4299#0193761a-6fe9-4771-aeb9-e54d5a4ea2a3

IntelliJ Plugin (IntelliJ CE OSS Latest Stable  : https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4299#0193761a-afb8-4783-b9cd-a8d2dabb0a0e

IntelliJ UE Plugin (Querysync Library) : https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4299#0193761a-bcff-415f-8531-278b7d1398a0

IntelliJ Plugin Aspect Google (Aspect Tests for IJ OSS Latest Stable ) : https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4299#0193761a-cc3d-4414-a9b8-9f32443ffe77

**Comment by tpasternak** [comment] 2024-11-29 08:42
Duplicate of https://github.com/bazelbuild/intellij/issues/7058

**Closed** 2024-12-11 22:22 UTC
Labels: type: bug, product: Android Studio, product: CLion, product: IntelliJ, awaiting-maintainer
