### ISSUE TITLE
Golang test files (*_test.go) are always unsynced

### ISSUE THREAD

**Issue by edposinitckii-hf** [bazelbuild/intellij#3527] opened 2022-04-26 18:26 UTC
#### Description of the issue. Please be specific.
All the go test files (`*_test.go`) are always marked as "unsynced" (when using bazel project view). Re-starting IDE,
cleaning cache, re-syncing, re-importing bazel project doesn't solve the issue.

Presumably, also by this reason it is not possible to run individual go tests from within the IDE sidebar context menu,
it shows "Nothing here" when clicking on the "play button" next to test case.

It is possible though to run full package test from the BUILD file sidebar context menu.

#### What's the simplest set of steps to reproduce this issue? Please provide an example project, if possible.
Simple reproducible case can be found in this repo: https://github.com/edposinitckii-hf/bazel-gotest-unsynced

#### Version information
IdeaUltimate: 2021.3.3
Platform: Mac OS X 12.1
Bazel plugin: 2022.03.22.0.5-api-version-213
Bazel: 4.2.1

----

#### Screenshots

<img width="818" alt="Screenshot 2022-04-26 at 20 08 12" src="https://user-images.githubusercontent.com/85237338/165367086-bf281bdc-8eac-4554-bb64-e34d9003d20f.png">
<img width="656" alt="Screenshot 2022-04-26 at 20 10 05" src="https://user-images.githubusercontent.com/85237338/165367118-80996df9-579c-4cac-9314-61b66cb7a290.png">

**Comment by sgowroji** [comment] 2022-11-17 08:29
Dupe of https://github.com/bazelbuild/intellij/issues/1265

**Comment by blorente** [comment] 2023-06-01 10:09
Hello @edposinitckii-hf 
I've had a chance to look at the issue, and it looks like it's related to the `rules_go` version you're using. Upgrading Bazel and the `rules_go` versions to the latest (or even Bazel 5.4.0) fixes the issue.
I'll close the issue, but feel free to reopen if it's not solved when you upgrade.

**Closed by blorente** 2023-06-01 10:09 UTC
Labels: type: bug, P2, lang: go, product: IntelliJ, topic: sync, topic: testing
