### ISSUE TITLE
Bazel sync error in  ONOS project: Error:Invalid aspect '@@intellij_aspect//:intellij_info_bundled.bzl%intellij_info_aspect': invalid repository name '@@intellij_aspect': repo names may contain only A-Z, a-z, 0-9, '-', '_' and '.': invalid repository name '@@intellij_aspect': repo names may contain only A-Z, a-z, 0-9, '-', '_' and '.'

### ISSUE THREAD

**Issue by RecyclableWaste** [bazelbuild/intellij#6475] opened 2024-06-08 05:45 UTC
### Description of the bug:

Error:Invalid aspect '@@intellij_aspect//:intellij_info_bundled.bzl%intellij_info_aspect': invalid repository name '@@intellij_aspect': repo names may contain only A-Z, a-z, 0-9, '-', '_' and '.': invalid repository name '@@intellij_aspect': repo names may contain only A-Z, a-z, 0-9, '-', '_' and '.'

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

import onos and click "Partially Sync onos/...all"

### Which Intellij IDE are you using? Please provide the specific version.

IntelliJIdea2024.1 Ultimate on ubuntu 24.01

### What programming languages and tools are you using? Please provide specific versions.

java,jdk11,bazel-6.0.0-pre.20220421.3, 

### What Bazel plugin version are you using?

 2024.05.07.0.1-api-version-241

### Have you found anything relevant by searching the web?

https://github.com/bazelbuild/bazel/issues/17809

### Any other information, logs, or outputs that you want to share?

Command: bazel build --tool_tag=ijwb:IDEA:ultimate --keep_going --build_event_binary_file=/tmp/intellij-bep-278a6367-56e5-4956-8945-0d1b3539a5ad --nobuild_event_binary_file_path_conversion --curses=no --color=yes --progress_in_terminal_title=no --noexperimental_run_validations --aspects=@@intellij_aspect//:intellij_info_bundled.bzl%intellij_info_aspect --override_repository=intellij_aspect=/home/aspas/.local/share/JetBrains/IntelliJIdea2024.1/ijwb/aspect --output_groups=intellij-resolve-java,intellij-info-generic,intellij-info-java -- //...:all
Loading: 
Loading: 0 packages loaded
ERROR: Invalid aspect '@@intellij_aspect//:intellij_info_bundled.bzl%intellij_info_aspect': invalid repository name '@@intellij_aspect': repo names may contain only A-Z, a-z, 0-9, '-', '_' and '.': invalid repository name '@@intellij_aspect': repo names may contain only A-Z, a-z, 0-9, '-', '_' and '.'
INFO: Elapsed time: 0.340s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
INFO: Build Event Protocol files produced successfully.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)

**Comment by tpasternak** [comment] 2024-06-10 11:54
Duplicate of #6474

**Closed by tpasternak** 2024-06-10 11:54 UTC
Labels: type: bug, product: IntelliJ, lang: java, topic: sync, awaiting-maintainer
