### ISSUE TITLE
ASwB import: "Project view validation failed, but we couldn't find an error message."

### ISSUE THREAD

**Issue by fis** [bazelbuild/intellij#47] opened 2017-01-24 21:10 UTC
Attempting to import a project gives me the following request:
"Project view validation failed, but we couldn't find an error message. Please report a bug."

I can find the following exception in the terminal Android Studio was started in:

```
[  45762]  ERROR - plication.impl.ApplicationImpl - Expected static method com.android.tools.idea.sdk.IdeSdks.getAndroidSdkPath()Ljava/io/File; 
java.lang.IncompatibleClassChangeError: Expected static method com.android.tools.idea.sdk.IdeSdks.getAndroidSdkPath()Ljava/io/File;
        at com.google.idea.blaze.android.compatibility.Compatibility$IdeSdks.getAndroidSdkPath(Compatibility.java:69)
        at com.google.idea.blaze.android.sync.BlazeAndroidSyncPlugin.installSdks(BlazeAndroidSyncPlugin.java:113)
        at com.google.idea.blaze.base.wizard2.ui.BlazeEditProjectViewControl$ProjectViewValidator.validateProjectView(BlazeEditProjectViewControl.java:381)
        at com.google.idea.blaze.base.scope.Scope.push(Scope.java:36)
        at com.google.idea.blaze.base.scope.Scope.root(Scope.java:28)
        at com.google.idea.blaze.base.wizard2.ui.BlazeEditProjectViewControl$ProjectViewValidator.run(BlazeEditProjectViewControl.java:367)
        at com.intellij.openapi.progress.impl.CoreProgressManager$6.run(CoreProgressManager.java:256)
        at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:635)
        at com.intellij.openapi.progress.impl.CoreProgressManager$9.run(CoreProgressManager.java:384)
        at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:170)
        at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:494)
        at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
        at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
        at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:155)
        at com.intellij.openapi.application.impl.ApplicationImpl.lambda$null$9(ApplicationImpl.java:548)
        at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:307)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[  45771]  ERROR - plication.impl.ApplicationImpl - Android Studio 2.3 Beta 2  Build #AI-162.3616766 
[  45772]  ERROR - plication.impl.ApplicationImpl - JDK: 1.8.0_112-release 
[  45772]  ERROR - plication.impl.ApplicationImpl - VM: OpenJDK 64-Bit Server VM 
[  45772]  ERROR - plication.impl.ApplicationImpl - Vendor: JetBrains s.r.o 
[  45772]  ERROR - plication.impl.ApplicationImpl - OS: Linux 
[  45772]  ERROR - plication.impl.ApplicationImpl - Last Action: EditorBackSpace 
```

This is on Android Studio 2.3b2 (162.3616766), after updating the plugin to version 2017.01.09.1.

Preceding problems:
- Latest stable Android Studio 2.2 + an earlier Bazel plugin (not sure which, but not a date-based version number) was working fine.
- After plugin update to 2017.01.09.1, external dependencies in the workspace stopped resolving in Android Studio. (E.g. all Guava class imports complained about "com.google" package not existing.)
- After updating Android Studio to 2.3b2, Android resource references ("R.id.foo") stopped resolving as well.
- Attempting to re-import the project is giving the above error.

I will try to prune down my project to a standalone test case and put it up as a Gist or something. Filing this early in case that makes things start working again, since the error message explicitly requested a bug.

FWIW, dumping my Android Studio `plugins/android/lib/android.jar:com/android/tools/idea/sdk/IdeSdks.class` indeed shows it has no static `getAndroidSdkPath()` method -- looks like it's `getInstance().getAndroidSdkPath()` now. I can see that the plugin's `aswb/2.3/src/com/google/idea/blaze/android/compatibility/Compatibility.java` file has what looks like correct code for AS 2.3, while that in `aswb/2.2/` contains a call to the static version. (So maybe it's using the wrong one?)

**Comment by brendandouglas** [comment] 2017-01-24 21:26
Hi @fis. Version 2017.01.09.1 is only compatible with Android Studio 2.2. We're currently working on support for 2.3.

That's the cause of all your issues except the external dependencies, which was a separate problem with the latest version.

The external dependencies bug should be fixed now (we've turned off a bazel aspect experiment which was causing the issue). If it's still happening after re-running bazel sync, you can manually disable the experiment by running 'echo "use.skylark.aspect.bazel=0" > ~/.intellij-experiments'

**Comment by fis** [comment] 2017-01-24 21:29
Thanks! I'll try going back to 2.2 + try your suggestion if I still have problems with external dependencies.

Feel free to close this issue or not, depending on whether you want to do something about that "we couldn't find an error message, please file a bug" message.

**Closed** 2017-01-24 21:42 UTC
