### ISSUE TITLE
Cannot install Bazel plugin in Clion IDE

### ISSUE THREAD

**Issue by swang203** [bazelbuild/intellij#369] opened 2018-07-19 21:04 UTC
setting->plugin->Browse repositories and search Bazel can only find "Bazel build formatter" and no "Bazel" package, how should I install it in another way?

Thanks for the help!

**Comment by brendandouglas** [comment] 2018-07-19 21:12
Probably because you're on a version of CLion for which there's no Bazel plugin (either very old, or 2018.2+).

You can see the supported versions here: https://plugins.jetbrains.com/plugin/9554-bazel

**Comment by brendandouglas** [comment] 2018-07-19 21:13
Closing as a dupe of https://github.com/bazelbuild/intellij/issues/320 on the assumption you're on CLion 2018.2

**Closed by brendandouglas** 2018-07-19 21:13 UTC

**Comment by swang203** [comment] 2018-07-19 22:19
thanks a lot!

**Comment by swang203** [comment] 2018-07-19 22:36
Hi, 
Just found that my clion version is 2017.3. It should be in the range of executable list.
Any other idea? Thanks.

**Comment by brendandouglas** [comment] 2018-07-20 13:09
Perhaps you're on a 2017.3 version prior to 173.4301? If not, you might have to manually download a compatible plugin from JetBrains' plugin repo.
