### ISSUE TITLE
Building fails with "Source forest creation failed" because "File exists"

### ISSUE THREAD

**Issue by aleb** [bazelbuild/intellij#135] opened 2017-10-02 15:45 UTC
Steps to reproduce with CLion 2017.1.3 and the Bazel plugin Version: 2017.08.01.0.1:
- git clone https://github.com/danieldanciu/clion-bazel.git
- import the bazel project, build it two times, notice `ERROR: Source forest creation failed: /private/var/tmp/_bazel_ab/fc7ea4530f9bdd4f1119eb797c96880e/execroot/__main__/bazel-clion-bazel (File exists).`

```
Syncing project...
Updating VCS...
Running Bazel info...
Command: /usr/local/bin/bazel info --tool_tag=ijwb:CLion --curses=no --color=no --noexperimental_ui --noprogress_in_terminal_title --


Command: git diff --name-status --no-renames 05ea74a8f7be2ee3e1271f0019f30ee1a705f629


____Loading package: @local_config_xcode//
Computing VCS working set...
  bazel-bin (added)
  bazel-clion-bazel (added)
  bazel-genfiles (added)
  bazel-out (added)
  bazel-testlogs (added)

Sync targets from project view:
  //...:all

Sync targets from working set:
  //:all
  //bazel-clion-bazel:all

Building IDE info files...
Command: /usr/local/bin/bazel build --tool_tag=ijwb:CLion --keep_going --experimental_build_event_binary_file=/var/folders/yd/nc6_vq355v352hm7_q86gfmw0000gn/T/intellij-bep-63b42403-b37b-4573-aced-3ebf948a0395 --noexperimental_build_event_binary_file_path_conversion --curses=no --color=no --noexperimental_ui --noprogress_in_terminal_title --aspects=@intellij_aspect//:intellij_info.bzl%intellij_info_aspect --override_repository=intellij_aspect=/Users/ab/Library/Application Support/CLion2017.1/clwb/aspect --output_groups=intellij-info-cpp,intellij-info-generic -- //...:all //:all //bazel-clion-bazel:all


____Loading package: bazel-clion-bazel
____Loading complete.  Analyzing...
____Loading package: @intellij_aspect//
____Loading package: @bazel_tools//third_party/java/jdk/langtools
____Found 2 targets...
____Building...
____Building complete.
____Elapsed time: 21.309s, Critical Path: 0.03s
____Waiting for build event protocol upload: 0s____Waiting for build event protocol upload: 0s
Total rules: 4, new/changed: 4, removed: 0
Reading IDE info result...
Loaded 4 aspect files, total size 3kB
Building IDE resolve files...
Command: /usr/local/bin/bazel build --tool_tag=ijwb:CLion --keep_going --experimental_build_event_binary_file=/var/folders/yd/nc6_vq355v352hm7_q86gfmw0000gn/T/intellij-bep-b73e5c10-4090-4c3d-8398-63de80f356ee --noexperimental_build_event_binary_file_path_conversion --curses=no --color=no --noexperimental_ui --noprogress_in_terminal_title --aspects=@intellij_aspect//:intellij_info.bzl%intellij_info_aspect --override_repository=intellij_aspect=/Users/ab/Library/Application Support/CLion2017.1/clwb/aspect --output_groups=intellij-resolve-cpp -- //...:all //:all //bazel-clion-bazel:all


____Loading package: @local_config_xcode//
____Loading complete.  Analyzing...
____Found 2 targets...
ERROR: Source forest creation failed: /private/var/tmp/_bazel_ab/fc7ea4530f9bdd4f1119eb797c96880e/execroot/__main__/bazel-clion-bazel (File exists).
____Elapsed time: 20.584s
____Waiting for build event protocol upload: 0s
Sync failed
```

**Comment by brendandouglas** [comment] 2017-10-02 16:58
This error is coming from Bazel. Which version of Bazel are you using?

Do you see the same error running that same bazel invocation from the command line? (how about if you remove the duplicate build targets, and just use '//...:all'?)

**Comment by aleb** [comment] 2017-10-03 09:26
In the command line, it succeeds if `//bazel-clion-bazel:all` is left out.

I was using Bazel  0.5.4-homebrew. I upgraded to 0.6.0 and now I hit #136.

**Comment by aleb** [comment] 2017-10-03 14:35
I get this problem with Bazel 0.6.0-homebrew also:
CLion 2017.1.3, Bazel 0.6.0-homebrew, plugin built from 015973d885a258d9b3921e5c06572bb4e1b30045 like this:
```
$ bazel build clwb:clwb_bazel_zip --define=ij_product=clion-latest
```

I run `bazel clean`, then press Sync, it succeeds, press Sync a second time, it fails:
```
Building IDE info files...
Command: /usr/local/bin/bazel build --tool_tag=ijwb:CLion --keep_going --experimental_build_event_binary_file=/var/folders/yd/nc6_vq355v352hm7_q86gfmw0000gn/T/intellij-bep-adf11386-12d1-4b9a-821f-0bb055d4bdb1 --noexperimental_build_event_binary_file_path_conversion --curses=no --color=no --noexperimental_ui --noprogress_in_terminal_title --aspects=@intellij_aspect//:intellij_info.bzl%intellij_info_aspect --override_repository=intellij_aspect=/Users/ab/Library/Application Support/CLion2017.1/clwb/aspect --output_groups=intellij-info-cpp,intellij-info-generic -- //...:all //:all //bazel-clion-bazel:all


____Loading package: bazel-clion-bazel
____Loading complete.  Analyzing...
____Found 2 targets...
____Building...
____Elapsed time: 25.549s, Critical Path: 0.01s
Total rules: 5, new/changed: 1, removed: 0
Reading IDE info result...
Loaded 1 aspect files, total size 1kB




Building IDE resolve files...
Command: /usr/local/bin/bazel build --tool_tag=ijwb:CLion --keep_going --experimental_build_event_binary_file=/var/folders/yd/nc6_vq355v352hm7_q86gfmw0000gn/T/intellij-bep-500cb595-2586-4516-b831-4745696a87e9 --noexperimental_build_event_binary_file_path_conversion --curses=no --color=no --noexperimental_ui --noprogress_in_terminal_title --aspects=@intellij_aspect//:intellij_info.bzl%intellij_info_aspect --override_repository=intellij_aspect=/Users/ab/Library/Application Support/CLion2017.1/clwb/aspect --output_groups=intellij-resolve-cpp -- //...:all //:all //bazel-clion-bazel:all


____Loading package: @local_config_xcode//
____Loading complete.  Analyzing...
____Found 2 targets...
ERROR: Source forest creation failed: /private/var/tmp/_bazel_ab/fc7ea4530f9bdd4f1119eb797c96880e/execroot/__main__/bazel-clion-bazel (File exists).
____Elapsed time: 25.316s
Sync failed
```

**Comment by brendandouglas** [comment] 2017-10-03 18:59
Closing this one as a duplicate of #136 -- though please open a Bazel-side issue if you think the error is spurious.

**Closed by brendandouglas** 2017-10-03 18:59 UTC

**Comment by aleb** [comment] 2017-10-11 12:57
Filed https://github.com/bazelbuild/bazel/issues/3857
