### ISSUE TITLE
Bazel plugin for IntelliJ IDEA 2020.2.1 (Ultimate Edition)

### ISSUE THREAD

**Issue by achinmishra** [bazelbuild/intellij#2064] opened 2020-08-27 19:49 UTC
Build #IU-202.6948.69, built on August 24, 2020
I do not find the compatibles in the source to compile it from. Also, Jetbrains plugins repository is incompatible. Please advise.

**Comment by sseveran** [comment] 2020-08-29 18:01
You will need to downgrade to 2020.1 at this time.

**Comment by ve6yeq** [comment] 2020-09-05 17:18
@sseveran Is there any notes anywhere on what needs to be done to achieve 2020.2+ compatibility?

**Comment by ve6yeq** [comment] 2020-09-05 17:28
Duplicate of #1998

**Comment by sseveran** [comment] 2020-09-06 22:23
@ve6yeq Not that I know of. I believe we are just waiting for Google's internal tools team to update the plugin and they tend to lag a few months.

**Comment by alice-ks** [comment] 2020-12-04 17:06
Closing this as a duplicate of #1998.

**Closed by alice-ks** 2020-12-04 17:06 UTC
