### ISSUE TITLE
Debug disabled in IntelliJ project with Go plugin

### ISSUE THREAD

**Issue by jessrosenfield** [bazelbuild/intellij#489] opened 2019-01-09 18:29 UTC
I'm unable to launch the debugger with `bazel test` run configurations.

**Comment by chaoren** [comment] 2019-01-18 18:32
Can you share a sample project? I can run and debug a `go_test` target without issue. There's some problems with debugging `go_binary` due to a new way of handling target arguments.

**Comment by chaoren** [comment] 2019-01-18 18:49
Do you get an error about "Failed to parse args in script_path" when you try to debug? If so, then I know what the issue is and it should be fixed soon.

**Comment by devshorts** [comment] 2019-02-25 20:00
I don't seem to get any debug option, is that the same symptom? I can run the test fine though

![image](https://user-images.githubusercontent.com/1799346/53364977-e401a700-38f4-11e9-950f-dcf1a2be6e9e.png)

**Comment by jessrosenfield** [comment] 2019-04-16 23:32
To clarify, I face the same issue. I'm able to run the tests in the editor, but the debug option is disabled/missing for me entirely.

**Comment by chaoren** [comment] 2019-04-17 15:55
I can't reproduce your issue. Please share a sample project.

**Comment by vikasunnava** [comment] 2019-05-01 15:37
I am seeing the same issue as @devshorts.

**Comment by chaoren** [comment] 2019-05-01 17:27
Can either of you share your projects so I can reproduce?
If you can't share your project, could you create a small sample project with the issue?

**Comment by devshorts** [comment] 2019-05-01 17:38
I'd love to, but not sure how much I can expose.  A simple repo looks to debug and work fine, however the one in use at my company has a lot of customized bazel (that I'm not familiar with). Are there any logs I can look at to see if there are options for debugging?

**Comment by dimitarvdimitrov** [comment] 2019-05-02 15:36
We were having the problem where the debug option is greyed-out for all types of targets.

A workaround we found was to have bazel spin up delve and we connect to it from IntelliJ.
* Add a "Go Remote" run configuration to `localhost:2345`

* `bazel run -c dbg --run_under='dlv --listen=:2345 --headless=true --api-version=2 exec' //:build-target`

* Run the Go Remote configuration and use IntelliJ debugger as you would normally

IntelliJ IDEA 2018.3.6 (Ultimate Edition)
Build #IU-183.6156.11, built on March 25, 2019
JRE: 1.8.0_152-release-1343-b28 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.4
Bazel Plugin version: v2019.04.15.0.5
Go Plugin version: v183.6156.11.1638

**Comment by vikasunnava** [comment] 2019-05-07 20:47
@chaoren Here is a test repo: https://gitlab.com/gauntletwizard/bazel-go
There is a test target: //extras/static:go_default_test

The debug mode is broken in this too. Would be helpful if you could take a look.

Bazel version: 0.24.1
GoLand version: 2018.3.6
Bazel PLugin: v2019.04.15.0.5

**Comment by chaoren** [comment] 2019-05-08 18:16
![Screenshot from 2019-05-08 14-14-46](https://user-images.githubusercontent.com/10055601/57397899-b742f900-719b-11e9-914a-5a289d0bb723.png)

I just tried out your project and it works fine for me.
I might have accidentally fixed your issue while fixing something else.
I'll test again on an earlier release.

**Closed** 2019-05-09 16:00 UTC
Labels: topic: go
