### ISSUE TITLE
Debugging are failing in kotlin while executing on kt_jvm_test/binary target in test.lib/BUILD

### ISSUE THREAD

**Issue by tanishktyagii** [bazelbuild/intellij#5944] opened 2024-01-12 09:23 UTC
### Description of the bug:

While performing kotlin debugging  from the IntelliJ examples through test.lib are failing.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. Open any Bazel kotlin project from intelliJ examples
(https://github.com/bazelbuild/intellij)
2.Open test.lib/Build file in that project
3.Click on kt_jvm_test/binary to execute for debugging.

### Which Intellij IDE are you using? Please provide the specific version.

IntelliJ 2023.2.2

### What programming languages and tools are you using? Please provide specific versions.

kotlin

### What Bazel plugin version are you using?

Bazel Plugin v2024.01.02

### Have you found anything relevant by searching the web?

<img width="1728" alt="Screenshot 2024-01-12 at 2 18 03 PM" src="https://github.com/bazelbuild/intellij/assets/144092358/26129c8c-8634-4ef8-8880-80f2a764be6e">

**Comment by mai93** [comment] 2024-01-15 19:19
I cannot reproduce this error, are you adding the breakpoint in the correct `.kt` file?

**Comment by sgowroji** [comment] 2024-01-16 05:49
Yes we are not seeing the above issue while placing the breakpoint in .kt test files. We can close this issue now.

**Closed by sgowroji** 2024-01-16 05:49 UTC
Labels: type: bug, lang: kotlin, product: IntelliJ, topic: debugging, awaiting-maintainer
