### ISSUE TITLE
IDEA - scala tests - not possible to run individual scala test in a class

### ISSUE THREAD

**Issue by InvisibleDev** [bazelbuild/intellij#2413] opened 2021-03-04 11:55 UTC
Currently when attempting to run a single Scala test from a tests class, bazel runs all of them. I checked the Run/Debug configurations and the generated config only has `--test_filter=tests.class.TestClassName` . Can you add support so taht individual tests can be run as well?
Currently I have to put `ignore` on all tests I don't want to run which is inconvenient.
Screenshot below should summarize what I mean:
![image](https://user-images.githubusercontent.com/5623430/109960778-1a8f0b00-7ce1-11eb-92b3-1b5c69685c41.png)

**Comment by sgowroji** [comment] 2022-09-30 06:53
Duplicate of https://github.com/bazelbuild/intellij/issues/3425

**Closed by sgowroji** 2022-09-30 06:53 UTC
Labels: lang: scala, product: IntelliJ
