### ISSUE TITLE
Intellij sync fails when importing Bazel

### ISSUE THREAD

**Issue by dslomov** [bazelbuild/intellij#20] opened 2016-09-15 13:48 UTC
Reposting from  https://github.com/bazelbuild/bazel/issues/1777

**Comment by dslomov** [comment] 2016-09-15 13:48
@abergmeier

**Comment by SalzzZ** [comment] 2016-09-19 02:30
It might be the same as #18

**Comment by abergmeier** [comment] 2016-09-19 13:58
Seems like it - not sure then why not everyone is experiencing it.

**Comment by brendandouglas** [comment] 2016-10-14 21:19
Closing as a dupe of [#18 ](https://github.com/bazelbuild/intellij/issues/18).

**Closed by brendandouglas** 2016-10-14 21:19 UTC
