### ISSUE TITLE
support for clion 2018.2

### ISSUE THREAD

**Issue by nevion** [bazelbuild/intellij#370] opened 2018-07-20 05:16 UTC
Testing out the RC for better refactoring support per clion support, however am unable to get a plugin build going for 2018.2 - how's support coming along?

**Comment by brendandouglas** [comment] 2018-07-20 13:06
We'll likely start looking at CLion 2018.2 support some time after there's a 'stable' release, probably in ~2 months from now.

Closing as a dupe of https://github.com/bazelbuild/intellij/issues/320

**Closed by brendandouglas** 2018-07-20 13:06 UTC
