### ISSUE TITLE
recognize cuda cu and cuh extensions

### ISSUE THREAD

**Issue by nevion** [bazelbuild/intellij#329] opened 2018-06-01 12:24 UTC
at present the bazel plugin cannot deal with cu/cuh file extensions for cuda.  Bazel itself has this problem (I will solve that problem upstream, I have some patches for it) but the intelij plugin also doesn't seem to like it all the way.

Is it possible to fix or outline how to add these file extensions to this plugin?

**Comment by brendandouglas** [comment] 2018-06-01 16:20
CUDA language support (or any language support other than BUILD / Skylark) isn't something that's provided by the Bazel plugin.

This is a feature request for CLion itself -- closing, as it's a dupe of https://youtrack.jetbrains.com/issue/CPP-866.

**Comment by nevion** [comment] 2018-06-01 18:16
@brendandouglas I want to clarify , I did not mean syntax highlighting, for instance, I mean if there are some file extension checks being done for any purposes, that the right things are happening.

Code like this, from blaze/cpp/CFileExtensions.java is a potential source of issue, like in bazel itself:
```
  static final ImmutableSet<String> C_FILE_EXTENSIONS = ImmutableSet.of("c");
  static final ImmutableSet<String> CXX_FILE_EXTENSIONS =
      ImmutableSet.of("cc", "cpp", "cxx", "c++", "C");

  static final ImmutableSet<String> CXX_ONLY_HEADER_EXTENSIONS =
      ImmutableSet.of("hh", "hpp", "hxx");
```

**Comment by brendandouglas** [comment] 2018-06-05 12:47
OK, thanks for clarifying. Reopening.

**Comment by nevion** [comment] 2018-06-14 16:03
The following trivial changes seemed to improve awareness of the files greatly:

```
--- a/cpp/src/com/google/idea/blaze/cpp/CFileExtensions.java
+++ b/cpp/src/com/google/idea/blaze/cpp/CFileExtensions.java
@@ -23,10 +23,10 @@ final class CFileExtensions {
   // See https://bazel.build/versions/master/docs/be/c-cpp.html#cc_binary.srcs
   static final ImmutableSet<String> C_FILE_EXTENSIONS = ImmutableSet.of("c");
   static final ImmutableSet<String> CXX_FILE_EXTENSIONS =
-      ImmutableSet.of("cc", "cpp", "cxx", "c++", "C");
+      ImmutableSet.of("cc", "cpp", "cxx", "c++", "C", "cu");
 
   static final ImmutableSet<String> CXX_ONLY_HEADER_EXTENSIONS =
-      ImmutableSet.of("hh", "hpp", "hxx");
+      ImmutableSet.of("hh", "hpp", "ipp", "hxx", "inl", "cuh", );
   private static final ImmutableSet<String> SHARED_HEADER_EXTENSIONS = ImmutableSet.of("h", "inc");
 
   static final ImmutableSet<String> SOURCE_EXTENSIONS =

```

**Comment by ymd-ponyai** [comment] 2020-12-14 22:57
Hi, CUDA is natively supported by CLion now, could you consider making this change? Thanks!

**Comment by sgowroji** [comment] 2023-01-23 07:07
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.

**Closed by sgowroji** 2023-01-23 07:07 UTC
Labels: product: CLion, lang: c++, type: plugin support requests
