### ISSUE TITLE
Bazel IntelliJ plugin allows no option to create directory 

### ISSUE THREAD

**Issue by tarique-lw** [bazelbuild/intellij#4982] opened 2023-06-14 09:54 UTC
### Description of the bug:

I have a bazel imported project in my IntelliJ IDE. There is no option to create directory under any oof the folders or packages.
On the other hand while I checked the same for my maven project there I could find the option to create directory.

**Bazel project snapshot -**
![image](https://github.com/bazelbuild/intellij/assets/92775528/5f420d08-c00a-4162-bcf8-572f9e7fe7f4)

**Maven project snapshot -**
![image](https://github.com/bazelbuild/intellij/assets/92775528/79e969ac-faa2-41b0-afc3-c7c96a4ae23b)
  

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Import bazel project and look for option to create a new directory .

### Which Intellij IDE are you using? Please provide the specific version.

JetBrains Client 2022.3.1

### What programming languages and tools are you using? Please provide specific versions.

Java

### What Bazel plugin version are you using?

bundled 2023.05.30.0.1-api-version-223

**Comment by tarique-lw** [comment] 2023-06-15 06:27
@mai93 any updates on this issue pls?

**Comment by mai93** [comment] 2023-06-30 20:51
I think the problem here is that for maven the `New->Package` is renamed to `New->Directory`. I think they are controlled by the same action in IntelliJ (https://github.com/JetBrains/intellij-community/blob/master/platform/lang-impl/src/com/intellij/ide/actions/CreateDirectoryOrPackageAction.java#L90), @tpasternak do you know if this is WAI or a bug?  

Also if this is right then @tarique-lw you can use `New->Package` to add a new directory while using the Bazel plugin.

**Comment by tarique-lw** [comment] 2023-07-06 16:09
@mai93 I can create Package but the point is when there is option explicitly to create a directory under folders other than source or test folders then why not here.
I have checked this with maven structure and is not the case there.
I have found something related to this but not sure if this was resolved correctly - https://github.com/bazelbuild/intellij/issues/198

**Comment by mai93** [comment] 2023-07-06 19:06
I see, I think this comment explains the reason (https://github.com/bazelbuild/intellij/issues/198#issuecomment-356104837). I'm not sure what are the implications of changing that though. If someone has the time to look into it, we can review and merge a PR that fixes this.

**Comment by nvachhar** [comment] 2023-08-21 23:52
@mai93 's comment was the root cause for the case @tarique-lw was worried about. I think it is safe to close this.

**Closed** 2023-08-22 15:09 UTC
Labels: type: bug, P3, product: IntelliJ, lang: java
