### ISSUE TITLE
Ability to overwrite projectview

### ISSUE THREAD

**Issue by agluszak** [bazelbuild/intellij#6829] opened 2024-10-03 07:30 UTC
### Description of the feature request:

Currently it is not possible to overwrite projectview files if you try to import a project which was previously imported

![image](https://github.com/user-attachments/assets/6501d5ea-bf70-4479-b5c3-f46fc709211b)

### Which category does this issue belong to?

Intellij

**Comment by tpasternak** [comment] 2024-10-03 07:34
Duplicate of #6454

**Comment by tpasternak** [comment] 2024-10-03 07:35
Duplicate of #434

**Closed** 2024-10-04 11:05 UTC
Labels: type: feature request, product: IntelliJ, awaiting-maintainer
