### ISSUE TITLE
NullPointerException on project sync in v2019.04.01

### ISSUE THREAD

**Issue by mjduijn** [bazelbuild/intellij#706] opened 2019-04-23 07:15 UTC
When syncing a project using Bazel > Sync > Sync project with Build files, a NullPointerException is thrown.
This occurs in version 2019.04.01 of the intellij bazel plugin and is fixed by downgrading to version 2019.03.18.0.2.
I've tried syncing in 2 different projects with the same result.

Config:
* Ubuntu 1804
* Intellij-ultimate 2018.3.6
* Intellij-bazel plugin v2019.04.01
* openjdk version "11.0.2" 2019-01-15

Stacktrace: 

    java.lang.NullPointerException: Null workingSet
    at com.google.idea.blaze.base.sync.AutoValue_BlazeSyncBuildResult$Builder.setWorkingSet(AutoValue_BlazeSyncBuildResult.java:249)
    at com.google.idea.blaze.base.sync.BlazeSyncTask.runBuildPhase(BlazeSyncTask.java:507)
    at com.google.idea.blaze.base.sync.BlazeSyncTask.doSyncProject(BlazeSyncTask.java:292)
    at com.google.idea.blaze.base.sync.BlazeSyncTask.syncProject(BlazeSyncTask.java:237)
    at com.google.idea.blaze.base.sync.BlazeSyncTask.lambda$run$0(BlazeSyncTask.java:196)
    at com.google.idea.blaze.base.scope.Scope.push(Scope.java:60)
    at com.google.idea.blaze.base.scope.Scope.root(Scope.java:52)
    at com.google.idea.blaze.base.sync.BlazeSyncTask.run(BlazeSyncTask.java:163)
    at com.google.idea.blaze.base.async.executor.ProgressiveTaskWithProgressIndicator.lambda$submitTask$0(ProgressiveTaskWithProgressIndicator.java:76)
    at com.google.idea.blaze.base.async.executor.ProgressiveTaskWithProgressIndicator.lambda$submitTaskWithResult$2(ProgressiveTaskWithProgressIndicator.java:110)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$3(CoreProgressManager.java:180)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:180)
    at com.google.idea.blaze.base.async.executor.ProgressiveTaskWithProgressIndicator.lambda$submitTaskWithResult$3(ProgressiveTaskWithProgressIndicator.java:110)
    at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
    at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
    at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

**Comment by brendandouglas** [comment] 2019-04-23 13:35
Closing as a dupe of https://github.com/bazelbuild/intellij/issues/682. This is fixed in the upcoming release, scheduled for April 26th.

**Closed by brendandouglas** 2019-04-23 13:35 UTC

**Comment by mjduijn** [comment] 2019-04-23 13:38
Ah sorry about the duplicate, thought I had searched for previous issues
