### ISSUE TITLE
Missing external libraries

### ISSUE THREAD

**Issue by libsamek** [bazelbuild/intellij#608] opened 2019-04-03 13:30 UTC
I'm using IntelliJ 2018.3.2 with latest Bazel plugin (v2019.01.02.0.2), Bazel 0.23.0 and bazel-deps (https://github.com/johnynek/bazel-deps) for help managing with external dependencies (this just helps with easier loading of maven packages).

For most external packages everything works as expected, source jars are automatically loaded under "External Libraries" in project view and code completion works normally. However, there are some libraries (eg. com_amazonaws_aws_java_sdk_bundle-sources.jar), where jar is not loaded, even though jar and source jar are present in bazel output directory.

Could you please point me in the right direction how to troubleshoot this? Why isn't source jar automatically loaded?

As a workaround I can always manually load source jar and then everything works as expected, but this is not a scalable solution. With every sync manual add is lost ...

**Comment by nvanderzwet** [comment] 2019-04-09 20:34
I've seen the same thing while using bazel-deps. I tried switching to the rules-jvm-external-maven and the problem appears worse - no sources are loading at all (I have fetch_sources = True), although this may be a separate issue

**Comment by jin** [comment] 2019-04-11 20:14
@nvanderzwet please file an issue on the rules_jvm_external repository about this; we want the ruleset to resolve all references correctly with fetch_sources = True or not.

**Comment by jin** [comment] 2019-04-11 22:35
Closing this a duplicate of #518: please continue discussions in that issue.

**Closed by jin** 2019-04-11 22:35 UTC

**Comment by libsamek** [comment] 2019-04-15 06:25
I have resolved problem by adding additional target to targets. Other targets were not using a library, meaning it was not actually used from IntelliJ point of view.
