### ISSUE TITLE
'bazel info' failing should not cause an exception in the IDE

### ISSUE THREAD

**Issue by hmemcpy** [bazelbuild/intellij#308] opened 2018-05-07 08:20 UTC
I imported a repo that had (probably) some bad configuration, which resulted in `bazel info` returning error 2. This was propagated to an exception within the IDE.
I don't believe this should be a visible exception to the user.

```
com.google.idea.blaze.base.command.info.BlazeInfoException: blaze info failed with exit code: 2
java.util.concurrent.ExecutionException: com.google.idea.blaze.base.command.info.BlazeInfoException: blaze info failed with exit code: 2
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:502)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:481)
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:78)
	at com.google.idea.blaze.base.async.FutureUtil$Builder.lambda$run$0(FutureUtil.java:96)
	at com.google.idea.blaze.base.scope.Scope.push(Scope.java:37)
	at com.google.idea.blaze.base.async.FutureUtil$Builder.run(FutureUtil.java:86)
	at com.google.idea.blaze.base.sync.BlazeSyncTask.doSyncProject(BlazeSyncTask.java:321)
	at com.google.idea.blaze.base.sync.BlazeSyncTask.syncProject(BlazeSyncTask.java:234)
	at com.google.idea.blaze.base.sync.BlazeSyncTask.lambda$run$0(BlazeSyncTask.java:190)
	at com.google.idea.blaze.base.scope.Scope.push(Scope.java:60)
	at com.google.idea.blaze.base.scope.Scope.root(Scope.java:52)
	at com.google.idea.blaze.base.sync.BlazeSyncTask.run(BlazeSyncTask.java:164)
	at com.google.idea.blaze.base.async.executor.ProgressiveTaskWithProgressIndicator.lambda$submitTask$0(ProgressiveTaskWithProgressIndicator.java:79)
	at com.google.idea.blaze.base.async.executor.ProgressiveTaskWithProgressIndicator.lambda$submitTaskWithResult$2(ProgressiveTaskWithProgressIndicator.java:113)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.google.idea.blaze.base.async.executor.ProgressiveTaskWithProgressIndicator.lambda$submitTaskWithResult$3(ProgressiveTaskWithProgressIndicator.java:113)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:111)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:58)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:75)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.google.idea.blaze.base.command.info.BlazeInfoException: blaze info failed with exit code: 2
	at com.google.idea.blaze.base.command.info.BlazeInfoRunnerImpl.runBlazeInfo(BlazeInfoRunnerImpl.java:102)
	at com.google.idea.blaze.base.command.info.BlazeInfoRunnerImpl.lambda$runBlazeInfo$2(BlazeInfoRunnerImpl.java:72)
	... 6 more
```

**Comment by mattnworb** [comment] 2018-10-24 21:03
I get the same error, but this part in the UI makes me think the problem is not configuration but something with the PATH used by the plugin:

 
![image](https://user-images.githubusercontent.com/113840/47461418-c1c51480-d7ae-11e8-8faa-3efe19f632b5.png)

```
[mattbrown@mattmbp spyglass]$ pwd
/Users/mattbrown/code/spyglass

[mattbrown@mattmbp spyglass]$ which bazel
/usr/local/bin/bazel
```

**Comment by alice-ks** [comment] 2021-02-04 09:52
As per the last comment, correcting the path to the Bazel binary in the configuration fixed this issue. Hence, I'm closing this issue.

**Closed by alice-ks** 2021-02-04 09:52 UTC
Labels: topic: bazel
