### ISSUE TITLE
Bazel CLion plugin has non-optional dependencies on Google Test, Catch and Boost Test plugins

### ISSUE THREAD

**Issue by odisseus** [bazelbuild/intellij#4664] opened 2023-03-30 17:49 UTC
### Description of the bug:

These are bundled plugins that come with CLion, but they cause a lot of overhead in some cases, so users which don't use the particular style of tests may want to disable some or all of these plugins. Unfortunately, this is not possible without disabling the Bazel plugin as well.

The Bazel plugin for Android studio has a similar problem with the Google Test plugin.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. Install Clion
2. Install Bazel plugin
3. Try to disable either of the three plugins in the title.

### Which Intellij IDE are you using? Please provide the specific version.

Clion, Android Studio

### What programming languages and tools are you using? Please provide specific versions.

C++, Android

**Comment by nikhil-marathe-skydio** [comment] 2023-03-31 18:23
This seems like a duplicate of #4481

**Closed as completed** 2023-05-12 11:04 UTC
Labels: type: bug, product: Android Studio, product: CLion, topic: testing, awaiting-maintainer
