### ISSUE TITLE
Read access is allowed from inside read-action only

### ISSUE THREAD

**Issue by kool79** [bazelbuild/intellij#6480] opened 2024-06-13 02:36 UTC
#### Description of the issue. Please be specific.
com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: Read access is allowed from inside read-action only (see Application.runReadAction()); see https://jb.gg/ij-platform-threading for details
Current thread: Thread[#59,DefaultDispatcher-worker-2,5,main] 1965169615 (EventQueue.isDispatchThread()=false)
SystemEventQueueThread: Thread[#89,AWT-EventQueue-0,6,main] 1634509137
	at com.intellij.util.concurrency.ThreadingAssertions.createThreadAccessException(ThreadingAssertions.java:177)
	at com.intellij.util.concurrency.ThreadingAssertions.softAssertReadAccess(ThreadingAssertions.java:129)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:908)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexDataImpl.ensureIsUpToDate(WorkspaceFileIndexDataImpl.kt:150)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexDataImpl.getFileInfo(WorkspaceFileIndexDataImpl.kt:91)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexImpl.getFileInfo(WorkspaceFileIndexImpl.kt:260)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexImpl.findFileSetWithCustomData(WorkspaceFileIndexImpl.kt:243)
	at com.intellij.openapi.roots.impl.ProjectFileIndexImpl.getModuleForFile(ProjectFileIndexImpl.java:100)
	at com.intellij.openapi.roots.impl.ProjectFileIndexImpl.getModuleForFile(ProjectFileIndexImpl.java:93)
	at com.google.idea.blaze.base.syncstatus.SyncStatusContributor.getSyncStatus(SyncStatusContributor.java:75)
	at com.google.idea.blaze.base.syncstatus.SyncStatusContributor.getSyncStatus(SyncStatusContributor.java:58)
	at com.google.idea.blaze.base.syncstatus.SyncStatusEditorTabTitleProvider.getEditorTabTitle(SyncStatusEditorTabTitleProvider.java:36)
	at com.intellij.openapi.fileEditor.impl.EditorTabPresentationUtil.getCustomEditorTabTitle(EditorTabPresentationUtil.kt:24)
	at com.intellij.openapi.fileEditor.impl.EditorTabPresentationUtil.getEditorTabTitle(EditorTabPresentationUtil.kt:15)
	at com.intellij.openapi.fileEditor.impl.EditorTabbedContainer$insertTab$2.invokeSuspend(EditorTabbedContainer.kt:288)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:608)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:873)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:763)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:750)

#### Version information
IdeaUltimate: 2024.2 EAP
Platform: Windows 10.0
Bazel for IntelliJ plugin: 2024.06.03.0.1-api-version-242
Bazel: 7.1.2

**Comment by sgowroji** [comment] 2024-06-13 04:07
Hi @kool79, Could you please provide complete steps to reproduce this issue?

**Comment by kool79** [comment] 2024-06-13 13:09
Platform: win 10
1. Install IntelliJ IDEA EAP with bazel plugin
3. Open bazel project: git@github.com:SeleniumHQ/selenium.git
Look into the notifications window of IntelliJ IDEA. This notification appears on every project opening

**Comment by tpasternak** [comment] 2024-06-17 08:08
Duplicate of #6473

**Closed by tpasternak** 2024-06-17 08:08 UTC
Labels: type: bug, product: IntelliJ, more-data-needed, awaiting-maintainer
