### ISSUE TITLE
On Windows target forward slashes turn into native backward slashes.

### ISSUE THREAD

**Issue by malkia** [bazelbuild/intellij#3380] opened 2022-03-25 04:39 UTC
#### Description of the issue. Please be specific.
On windows, bazel targets have the forward slashes turned into backward ones, hence they are not recognized, for example

Command: bazel query --tool_tag=ijwb:CLion --output=label_kind --keep_going same_pkg_direct_rdeps(\"//sdk\test\metrics:aggregation_test.cc\") 

#### What's the simplest set of steps to reproduce this issue? Please provide an example project, if possible.
Well, I know Windows is not officially supported, but all it takes is a repository with at least one sub-directory and target into it, and the IDE would show it with wrong slashes. Current workaround (in the IDE) only is to manually change them everytime, but certain operations cannot finish like the one above ^^^

#### Version information
CLion: 2021.3.4
Platform: Windows 10 10.0
Bazel plugin: 2022.03.08.0.1-api-version-213
Bazel: 5.0.0

**Comment by sgowroji** [comment] 2022-10-27 08:47
Hello @malkia, Can you provide a minimal steps to reproduce the above issue . Thanks!

**Comment by malkia** [comment] 2022-10-27 21:23
Sure. I've used https://github.com/open-telemetry/opentelemetry-cpp as example, did the defaults, and then went into

src/test/metrics/BUILD file

and selected the `aggregation_test`

![image](https://user-images.githubusercontent.com/51738/198400590-714a8666-ac23-41a5-aef5-74ab82552616.png)

right click, debug on it, and it shows this:

![image](https://user-images.githubusercontent.com/51738/198400680-484f811d-66ad-4d24-99ff-71ebc52f3ad6.png)

then I get

![image](https://user-images.githubusercontent.com/51738/198400759-bcc263f5-550c-493b-9b88-26a7f5b26996.png)

the workaround is to manually click on all backslashes, and make them into forward ones

![image](https://user-images.githubusercontent.com/51738/198400875-48a8829f-bd40-4340-8b6a-9b960cebf6e0.png)

then it can run bazel

![image](https://user-images.githubusercontent.com/51738/198400935-2a6c48fd-890a-40f2-8cdc-49a84de61b88.png)

**Comment by malkia** [comment] 2022-10-27 21:25
I've also checked the plugin version, it's `2022.10.04.0.1-api-version-222` Oct 20, 2022
and my CLion is right now at `2022.2.4`

Hope this helps.

**Comment by HaimingTian** [comment] 2022-12-16 03:29
@sgowroji Unfortunately I don't own any Windows devices so I can't reproduce/fix/verify, can we please reassign to those with Windows devices?

**Closed** 2023-06-05 23:02 UTC
Labels: P2, product: CLion, os: windows, type: user support, awaiting-maintainer
