### ISSUE TITLE
NPE caused by missing bazel path

### ISSUE THREAD

**Issue by hmemcpy** [bazelbuild/intellij#147] opened 2017-10-19 14:30 UTC
I opened a project, and was unable to sync it in IntelliJ - I got `Error:Could not run Bazel info`, and the exception bulb displayed the following:

    java.lang.NullPointerException
    java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:502)
        at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:481)
        at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:78)
        at com.google.idea.blaze.base.async.FutureUtil$Builder.lambda$run$0(FutureUtil.java:93)
        at com.google.idea.blaze.base.scope.Scope.push(Scope.java:37)
        at com.google.idea.blaze.base.async.FutureUtil$Builder.run(FutureUtil.java:83)
        at com.google.idea.blaze.base.sync.BlazeSyncTask.doSyncProject(BlazeSyncTask.java:269)
        at com.google.idea.blaze.base.sync.BlazeSyncTask.syncProject(BlazeSyncTask.java:199)
        at com.google.idea.blaze.base.sync.BlazeSyncTask.lambda$run$0(BlazeSyncTask.java:166)
        at com.google.idea.blaze.base.scope.Scope.push(Scope.java:60)
        at com.google.idea.blaze.base.scope.Scope.root(Scope.java:52)
        at com.google.idea.blaze.base.sync.BlazeSyncTask.run(BlazeSyncTask.java:143)
        at com.google.idea.blaze.base.async.executor.BlazeExecutor$2.run(BlazeExecutor.java:99)
        at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:170)
        at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:548)
        at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:493)
        at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
        at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
        at com.google.idea.blaze.base.async.executor.BlazeExecutor$3.call(BlazeExecutor.java:108)
        at com.google.idea.blaze.base.async.executor.BlazeExecutor$3.call(BlazeExecutor.java:105)
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:111)
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:58)
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:75)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
    Caused by: java.lang.NullPointerException
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770)
        at com.google.common.collect.ImmutableCollection$ArrayBasedBuilder.add(ImmutableCollection.java:477)
        at com.google.common.collect.ImmutableList$Builder.add(ImmutableList.java:758)
        at com.google.idea.blaze.base.command.BlazeCommand.toList(BlazeCommand.java:45)
        at com.google.idea.blaze.base.async.process.ExternalTask$Builder.addBlazeCommand(ExternalTask.java:87)
        at com.google.idea.blaze.base.command.info.BlazeInfoRunnerImpl.runBlazeInfo(BlazeInfoRunnerImpl.java:95)
        at com.google.idea.blaze.base.command.info.BlazeInfoRunnerImpl.lambda$runBlazeInfo$2(BlazeInfoRunnerImpl.java:72)
        ... 6 more

It was caused by an empty `Bazel binary location` setting.

This should be handled more gracefully.

**Comment by ittaiz** [comment] 2017-12-09 07:41
I think, not sure, that this [SO question](https://stackoverflow.com/q/47709018/170013) is caused by the same (or similar) issue, right?

**Comment by sgowroji** [comment] 2022-11-11 03:46
Hello @hmemcpy, Are you still seeing the issue with latest bazel and intellij plugin ?

**Comment by mai93** [comment] 2022-12-05 20:08
Closing this issue, please reopen it if you are still seeing this problem with newer plugin versions.

**Closed by mai93** 2022-12-05 20:08 UTC
Labels: type: bug, product: IntelliJ, topic: bazel, more-data-needed, awaiting-maintainer
