### ISSUE TITLE
Different behaviour for running vs debugging bazel target in Intelij

### ISSUE THREAD

**Issue by kriscfoster** [bazelbuild/intellij#3684] opened 2022-06-14 14:27 UTC
When I click run and debug for a target in Intelij, the behaviour is different. The main issue is that debug doesn't include the environment variables that are included with run.

Here's a repository with a basic reproduction: https://github.com/kriscfoster/bazel-intelij-debug-repro

Bazel plugin version: `2022.02.23.0.0-api-version-212`

This repository was created for the purpose of reproducing some behaviour to share with
https://github.com/bazelbuild/intellij. There is different behaviour when running versus
debugging a target.

## from commandline

```
bazel run //:demo
...
2022/06/14 15:16:47 MY_VARIABLE: hello world!
```

## from Intelij (clicking run on target)

```
...
2022/06/14 15:17:56 MY_VARIABLE: hello world!
```

## from Intelij (clicking debug on target)

```
...
2022/06/14 15:18:32 MY_VARIABLE:
```

**Comment by kriscfoster** [comment] 2022-06-16 07:58
This is probably due to https://github.com/bazelbuild/intellij/issues/2213

**Comment by sgowroji** [comment] 2022-10-21 05:34
Dupe of #2213

**Closed by sgowroji** 2022-10-21 05:34 UTC
