### ISSUE TITLE
Test results no longer should consider 'time' being 0.0 for being filtered

### ISSUE THREAD

**Issue by hmemcpy** [bazelbuild/intellij#239] opened 2018-02-15 13:13 UTC
It seems that https://github.com/bazelbuild/bazel/pull/4596 was merged, which means that bazel will no longer report filtered tests in the xml file. The plugin should no longer check for 0.0 time in the tests results.

**Comment by chaoren** [comment] 2018-02-15 20:16
Your fix only applies to the JUnit test runner. I'm gonna check other languages' behavior.

**Comment by hmemcpy** [comment] 2018-02-15 20:17
Oh right, there are others 😂

**Comment by chaoren** [comment] 2018-02-15 21:18
It seems go, cc, python all set `status="run"`, so looks like we're clear.

**Comment by chaoren** [comment] 2018-02-15 21:53
But we should probably wait until the next bazel release to commit our change.

**Comment by ittaiz** [comment] 2018-02-16 04:37
Any chance we can not wait?
If you commit now it will still take a good few weeks until it lands in
jetbrains repository, right?

**Comment by chaoren** [comment] 2018-02-16 16:29
@brendandouglas, thoughts?

**Comment by brendandouglas** [comment] 2018-02-16 18:05
Let's wait until we're confident a decent proportion of users are on a bazel release containing the fix.

https://github.com/bazelbuild/bazel/commit/3edf41b70de9bb1a8702d0342beeb2ad13898d71 hasn't been cherry-picked to 0.11, so I assume it won't be out until 0.12.

**Comment by chaoren** [comment] 2018-03-12 15:02
Looks like https://github.com/bazelbuild/bazel/pull/4596 has been rolled back. What's the plan for this change now?

**Comment by hmemcpy** [comment] 2018-03-12 15:04
Yeah, I'm sorry, I forgot to update. We found an issue where tests that were dynamically added by specs2 during execution were also filtered out for some reason. We asked to rollback the change to prevent releasing a buggy RC that we need to use.
We're committed to fixing it ASAP, so let's hold it for a few more days.

**Comment by hmemcpy** [comment] 2018-03-18 14:06
After further analysis, I pinpointed the source of the problem -- it has to do with the value used for `hashCode` in the `Description` objects that are produced by specs2, in case of tests generated in a loop (e.g. `Fragments.foreach` API). This causes bazel to incorrectly build the testMap (due to the hashCode being the same, only one test actually appears in the model).

I've sent a PR to the author of specs2, so it should be fixed in future versions. This PR is good to go as-is.
Can you please reapply the PR, or should I send a new one?

**Comment by brendandouglas** [comment] 2018-03-19 12:27
If you mean the Bazel PR, could you send another PR to bazelbuild/bazel, or post a comment on bazelbuild/bazel#4596?

Once that's landed again, and a decent proportion of users are on a bazel release containing that patch, we'll make the required plugin-side changes.

**Comment by hmemcpy** [comment] 2018-03-19 12:34
Oh jeez, I meant to reply on the original bazel thread :)
Sure, I'll have them reapply the commit, and will update here.

**Comment by hmemcpy** [comment] 2018-03-20 10:08
Alright, looks like the original PR will be in 0.12.0 releases. We'll wait until the specs2 PR was merged to use it.
After that, removing the 'time' based logic should be fine.

**Comment by chaoren** [comment] 2018-04-16 16:35
This is in bazel 0.13.0, but it's not public yet.

**Comment by ittaiz** [comment] 2018-04-16 16:48
Are you sure?
I seem to remember @philwo saying it will be in 0.12.0

**Comment by chaoren** [comment] 2018-04-16 16:51
Yes, I just tested and check the testlog XML with 0.12.0 and 0.13.0.

**Comment by ittaiz** [comment] 2018-04-16 17:01
Bummer.
Thanks for checking

**Comment by chaoren** [comment] 2018-05-04 17:08
Looks like 0.13.0 is out. The corresponding plugin changes should be in the next release.

**Closed by chaoren** 2018-05-04 17:08 UTC

**Comment by ittaiz** [comment] 2018-05-04 18:12
The one coming in 3 weeks?

**Comment by chaoren** [comment] 2018-05-04 18:16
Should be on the 18th.

**Comment by ittaiz** [comment] 2018-05-04 18:35
Awesome, thanks!

**Comment by hmemcpy** [comment] 2018-05-30 09:04
I just tested this with bazel 0.13.1 and plugin 2018.05.07.0.2, unfortunately I still see the one result:
![image](https://user-images.githubusercontent.com/601206/40710513-890508c4-6401-11e8-8e8a-6dac8994a3ec.png)

But the test.xml contains both:
```
<?xml version='1.0' encoding='UTF-8'?>
<testsuites>
  <testsuite name='Aggregate Specs2 Test Suite' timestamp='1970-01-03T16:23:00.768Z' hostname='localhost' tests='2' failures='0' errors='0' time='0.002' package='' id='0'>
    <properties />
    <system-out />
    <system-err />
  </testsuite>
  <testsuite name='MyTest' timestamp='1970-01-03T16:23:00.768Z' hostname='localhost' tests='2' failures='0' errors='0' time='0.002' package='' id='1'>
    <properties />
    <testcase name='myTest' classname='com.foo.MyTest' time='0.001' />
    <testcase name='myTest2' classname='com.foo.MyTest' time='0.0' />
    <system-out />
    <system-err />
  </testsuite>
</testsuites>
```

**Comment by chaoren** [comment] 2018-05-30 15:20
Odd. The change should have been included in that plugin release. I'll check.

**Comment by chaoren** [comment] 2018-05-30 15:53
Can't reproduce. I can see the 0 ms tests just fine.

```
$ bazel version
Build label: 0.13.1
```

Tried with plugin version 2018.05.07.0.2.

I can't think of anything that could cause what you're seeing. Please double check bazel and plugin versions?

![image](https://user-images.githubusercontent.com/10055601/40730842-9edec33c-63fd-11e8-87b8-66f99b2783c4.png)
```
<?xml version='1.0' encoding='UTF-8'?>
<testsuites>
  <testsuite name='Aggregate Specs2 Test Suite' timestamp='1970-02-24T18:19:04.368Z' hostname='localhost' tests='7' failures='0' errors='0' time='0.01' package='' id='0'>
    <properties />
    <system-out />
    <system-err />
  </testsuite>
  <testsuite name='ScalaSpecs2JunitTest' timestamp='1970-02-24T18:19:04.368Z' hostname='localhost' tests='7' failures='0' errors='0' time='0.01' package='' id='1'>
    <properties />
    <system-out />
    <system-err />
  </testsuite>
  <testsuite name='abstract test should' timestamp='1970-02-24T18:19:04.368Z' hostname='localhost' tests='1' failures='0' errors='0' time='0.002' package='' id='2'>
    <properties />
    <testcase name='abstract test should::succeed' classname='experimental.users.chaorenl.scala.ScalaSpecs2JunitTest' time='0.002' />
    <system-out />
    <system-err />
  </testsuite>
  <testsuite name='JavaImport should' timestamp='1970-02-24T18:19:04.372Z' hostname='localhost' tests='1' failures='0' errors='0' time='0.0' package='' id='3'>
    <properties />
    <testcase name='JavaImport should::have this name' classname='experimental.users.chaorenl.scala.ScalaSpecs2JunitTest' time='0.0' />
    <system-out />
    <system-err />
  </testsuite>
  <testsuite name='JavaExport should' timestamp='1970-02-24T18:19:04.373Z' hostname='localhost' tests='1' failures='0' errors='0' time='0.0' package='' id='4'>
    <properties />
    <testcase name='JavaExport should::have this name' classname='experimental.users.chaorenl.scala.ScalaSpecs2JunitTest' time='0.0' />
    <system-out />
    <system-err />
  </testsuite>
  <testsuite name='JavaLibrary should' timestamp='1970-02-24T18:19:04.375Z' hostname='localhost' tests='1' failures='0' errors='0' time='0.0' package='' id='5'>
    <properties />
    <testcase name='JavaLibrary should::have this name' classname='experimental.users.chaorenl.scala.ScalaSpecs2JunitTest' time='0.0' />
    <system-out />
    <system-err />
  </testsuite>
  <testsuite name='ScalaExport should' timestamp='1970-02-24T18:19:04.376Z' hostname='localhost' tests='1' failures='0' errors='0' time='0.0' package='' id='6'>
    <properties />
    <testcase name='ScalaExport should::have this name' classname='experimental.users.chaorenl.scala.ScalaSpecs2JunitTest' time='0.0' />
    <system-out />
    <system-err />
  </testsuite>
  <testsuite name='ScalaLibrary should' timestamp='1970-02-24T18:19:04.377Z' hostname='localhost' tests='1' failures='0' errors='0' time='0.0' package='' id='7'>
    <properties />
    <testcase name='ScalaLibrary should::have this name' classname='experimental.users.chaorenl.scala.ScalaSpecs2JunitTest' time='0.0' />
    <system-out />
    <system-err />
  </testsuite>
  <testsuite name='ScalaMacroLibrary should' timestamp='1970-02-24T18:19:04.378Z' hostname='localhost' tests='1' failures='0' errors='0' time='0.0' package='' id='8'>
    <properties />
    <testcase name='ScalaMacroLibrary should::have this name' classname='experimental.users.chaorenl.scala.ScalaSpecs2JunitTest' time='0.0' />
    <system-out />
    <system-err />
  </testsuite>
</testsuites>
```

**Comment by hmemcpy** [comment] 2018-05-31 07:35
Hmm, very odd. I updated everything (there was an IntelliJ update), re-ran my tests, and can indeed confirm I saw all tests!
Great work, thank you!
