### ISSUE TITLE
IDEA - scala tests - not possible to see logs of individual test runs

### ISSUE THREAD

**Issue by InvisibleDev** [bazelbuild/intellij#2414] opened 2021-03-04 12:20 UTC
Currently it is not possible to see logs of individual test runs. The only possible way to see logs is via top level which is inconvenient. Interestingly, it displays assertion failure details but that doesn't help much when you debug complex scenarios. As you can see from below screenshots successful runs don't show anything. Failed runs show assertion failure only.

![image](https://user-images.githubusercontent.com/5623430/109963130-f41e9f00-7ce3-11eb-8064-a353fdebd7be.png)

![image](https://user-images.githubusercontent.com/5623430/109962811-925e3500-7ce3-11eb-8f1e-05067f3b3d64.png)

**Comment by sgowroji** [comment] 2022-09-30 06:53
Duplicate of https://github.com/bazelbuild/intellij/issues/3425

**Closed by sgowroji** 2022-09-30 06:53 UTC
