### ISSUE TITLE
Symbol cannot be resolved properly in CLion 2017.1 on Mac OS

### ISSUE THREAD

**Issue by wangli1426** [bazelbuild/intellij#95] opened 2017-06-02 12:58 UTC
I imported my bazel project in CLion as instructed by https://ij.bazel.build/docs/import-project.html. However, the CLion cannot resolve the symbols such as ```std::cout``` properly. My bazel project compiles and runs well in a terminal command line.

**Comment by mkraft89** [comment] 2017-07-12 06:04
Same here. I am using CLion 2017.1.3 and had to disable the PyCharm package to make the Bazel plugin work. Now everything seems to be in order, but it does not resolve c++ symbols anymore.

**Comment by brendandouglas** [comment] 2017-07-17 12:48
Closing as a probable duplicate of #109. If you have an example project we could try loading, please let us know.

**Closed by brendandouglas** 2017-07-17 12:48 UTC
