### ISSUE TITLE
bazel report an exception: "cannot load from prebuilt icon cache" when start the IDE

### ISSUE THREAD

**Issue by Hotwill** [bazelbuild/intellij#4068] opened 2022-11-03 07:59 UTC
### Description of the bug:

when start clion, it report a "ide error" on the right button, click it and shows bazel throws an exception.
here is the stack:
cannot load from prebuilt icon cache

java.nio.file.NoSuchFileException: /home/huzhuang/opt/clion-2020.1.2/bin/icons/icons-v1-1.0.db
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:181)
	at java.base/java.nio.channels.FileChannel.open(FileChannel.java:298)
	at org.jetbrains.ikv.Ikv.doLoadIkv(Ikv.java:112)
	at org.jetbrains.ikv.Ikv.loadSizeUnawareIkv(Ikv.java:106)
	at com.intellij.ui.svg.SvgPrebuiltCacheManager$StoreContainer.getSynchronized(SvgPrebuiltCacheManager.kt:40)
	at com.intellij.ui.svg.SvgPrebuiltCacheManager$StoreContainer.getOrCreate(SvgPrebuiltCacheManager.kt:34)
	at com.intellij.ui.svg.SvgPrebuiltCacheManager.loadFromCache(SvgPrebuiltCacheManager.kt:52)
	at com.intellij.util.SVGLoader.loadFromClassResource(SVGLoader.kt:108)
	at com.intellij.util.SVGLoader.loadFromClassResource$default(SVGLoader.kt:90)
	at com.intellij.ui.RasterizedImageDataLoaderKt.loadRasterized(RasterizedImageDataLoader.kt:177)
	at com.intellij.ui.RasterizedImageDataLoaderKt.access$loadRasterized(RasterizedImageDataLoader.kt:1)
	at com.intellij.ui.RasterizedImageDataLoader.loadImage(RasterizedImageDataLoader.kt:40)
	at com.intellij.openapi.util.IconLoader$CachedImageIcon.loadImage(IconLoader.java:979)
	at com.intellij.openapi.util.IconLoader$ScaledIconCache.getOrScaleIcon(IconLoader.java:1048)
	at com.intellij.openapi.util.IconLoader$CachedImageIcon.getRealIcon(IconLoader.java:866)
	at com.intellij.openapi.util.IconLoader$CachedImageIcon.getIconWidth(IconLoader.java:794)
	at com.intellij.openapi.util.IconLoader.isGoodSize(IconLoader.java:547)
	at com.intellij.openapi.actionSystem.impl.ActionButton.updateIcon(ActionButton.java:356)
	at com.intellij.openapi.actionSystem.impl.ActionButton.addNotify(ActionButton.java:271)
	at java.desktop/java.awt.Container.addImpl(Container.java:1150)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.addImpl(ActionToolbarImpl.java:408)
	at java.desktop/java.awt.Container.add(Container.java:440)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.fillToolBar(ActionToolbarImpl.java:398)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.actionsUpdated(ActionToolbarImpl.java:1285)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.updateActionsImplFastTrack(ActionToolbarImpl.java:1236)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.updateActionsImpl(ActionToolbarImpl.java:1204)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl$1.updateActionsImpl(ActionToolbarImpl.java:198)
	at com.intellij.openapi.actionSystem.impl.ToolbarUpdater$MyUpdateRunnable.run(ToolbarUpdater.java:152)
	at com.intellij.openapi.actionSystem.impl.ToolbarUpdater.updateActions(ToolbarUpdater.java:68)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.updateActionsImmediately(ActionToolbarImpl.java:1183)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.updateActionsImmediately(ActionToolbarImpl.java:1168)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.addNotify(ActionToolbarImpl.java:254)
	at java.desktop/java.awt.Container.addImpl(Container.java:1150)
	at java.desktop/java.awt.Container.add(Container.java:493)
	at com.intellij.openapi.wm.impl.IdeRootPane.doUpdateToolbarWithoutDelegate(IdeRootPane.java:282)
	at com.intellij.openapi.wm.impl.IdeRootPane.updateToolbar(IdeRootPane.java:272)
	at com.intellij.openapi.wm.impl.ProjectFrameHelper.updateView(ProjectFrameHelper.java:329)
	at com.google.idea.blaze.base.actions.ProjectFrameUpdater.projectOpened(ProjectFrameUpdater.java:42)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeMethod(MessageBusImpl.kt:649)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:625)
	at com.intellij.util.messages.impl.MessageBusImplKt.executeOrAddToQueue(MessageBusImpl.kt:470)
	at com.intellij.util.messages.impl.ToDirectChildrenMessagePublisher.publish$intellij_platform_core(CompositeMessageBus.kt:292)
	at com.intellij.util.messages.impl.MessagePublisher.invoke(MessageBusImpl.kt:425)
	at jdk.proxy2/jdk.proxy2.$Proxy74.projectOpened(Unknown Source)
	at com.intellij.openapi.project.impl.ProjectManagerExImplKt$openProject$$inlined$useWithScope$lambda$1$2.run(ProjectManagerExImpl.kt:633)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.project.impl.ProjectManagerExImplKt$openProject$$inlined$useWithScope$lambda$1.run(ProjectManagerExImpl.kt:464)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:513)
	at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:95)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:75)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:118)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:779)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:749)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:918)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:766)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:450)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:791)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:449)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:624)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:447)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:493)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

### Which Intellij IDE are you using? Please provide the specific version.

clion

### What programming languages and tools are you using? Please provide specific versions.

c++

**Comment by sgowroji** [comment] 2022-11-03 09:18
Hello @Hotwill, Thanks for reaching out regarding the above error. Could you please share more details like plugin and clion version used in reproducing the above issue. And minimal steps followed in reproducing it.

**Comment by sgowroji** [comment] 2023-01-12 06:47
Due to lack of details on the above issue.  We are closing this issue now. Please feel free to reach us if you can provide above information. Thanks!

**Closed by sgowroji** 2023-01-12 06:47 UTC
Labels: type: bug, product: CLion, more-data-needed
