### ISSUE TITLE
Cant see Bazel plugin android studio

### ISSUE THREAD

**Issue by Kadanza** [bazelbuild/intellij#410] opened 2018-09-17 12:26 UTC
I try to install  this plugin on my android studio and run android bazel project. 
 

> **Installation**
> You can find our plugin in the Jetbrains plugin repository by going to Settings -> Browse Repositories, and searching for Bazel.

I can see only one plugins, updated 14.06.2016.

![2018-09-17 15 19 26](https://user-images.githubusercontent.com/35968229/45622610-4379a200-ba8d-11e8-9f5e-1fb408f2dc1e.png)

I can't run bazel  project and see action such as "Import Bazel Project"
How to run bazel project in android studio?

**Comment by Kadanza** [comment] 2018-09-17 12:36
I use Android Studio 3.3 Canary 8

**Comment by brendandouglas** [comment] 2018-09-17 13:15
We don't yet support Android Studio 3.3. The current workaround is to use 3.2 or earlier.

**Comment by brendandouglas** [comment] 2018-09-17 13:16
With our current release process, we don't release plugins compatible with AS canary branches. That might change in the future, but for now I don't expect 3.3 to be supported until ~ a month after it moves to beta.

**Comment by Kadanza** [comment] 2018-09-17 13:57
What is currently max version  of android studio has bazel plugin? I download 3.2 Beta 1  from https://developer.android.com/studio/archive   and don't see Bazel plugin. 

This is 181.4892.42 build.  From https://plugins.jetbrains.com/plugin/8609-bazel i see last plugin has compatibility with 181.5540—181.*

In version 3.0.0 i can see this plugin

**Comment by brendandouglas** [comment] 2018-09-17 14:05
The JetBrains plugin repo site you linked to has the definitive listing of supported versions (the 'compatibility' column).

It should be showing up for a 181.4892.42 build (since 181.4668 is the earliest 181 build we supported). There were some bugs with downloading plugins in 3.2, so perhaps try a newer 3.2 build? (e.g. 3.2 RC 3)

**Comment by Kadanza** [comment] 2018-09-18 09:28
In 3.2 RC 3 work now

**Comment by Kadanza** [comment] 2019-01-14 15:25
@brendandouglas 

In windows I can't see bazel plagin. I load different versions and cant see in search plugins bar.
In last year it work in mac and windows

![2](https://user-images.githubusercontent.com/35968229/51121692-0fd73a80-1829-11e9-8faa-e3e420e9a197.png)
![1](https://user-images.githubusercontent.com/35968229/51121693-0fd73a80-1829-11e9-9439-31f0b88d564a.png)

**Comment by jin** [comment] 2019-04-18 01:50
Just ran into this issue with Android Studio 3.4 on the Mac.

**Comment by jin** [comment] 2019-05-10 23:22
Closing this as a dupe of https://github.com/bazelbuild/intellij/issues/754 - added a JetBrains response there, and the search should work for the next plugin release.

**Closed by jin** 2019-05-10 23:22 UTC
Labels: product: Android Studio, type: bug
