### ISSUE TITLE
Bazel 6 `--incompatible_unambiguous_label_stringification` causes Go tests to not be considered under the same package as the code it's testing

### ISSUE THREAD

**Issue by JamyDev** [bazelbuild/intellij#4349] opened 2023-01-26 23:50 UTC
### Description of the bug:

After upgrading to Bazel 6.0 in our Go repo we started encountering warnings about using unexported variables from the main code:

<img width="717" alt="image" src="https://user-images.githubusercontent.com/1273267/214975629-ce48b059-86af-427c-ad0a-6b425f42d8c3.png">

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

In a go _test.go file, try to use an unexported const from the main package file. This is allowed, but the IDE inspection complains. Setting `--noincompatible_unambiguous_label_stringification` fixes it, but in all likelihood this won't be available for too much longer.

### Which Intellij IDE are you using? Please provide the specific version.

Goland 2022.3.1

### What programming languages and tools are you using? Please provide specific versions.

bazel, golang

### What Bazel plugin version are you using?

2023.01.10

### Have you found anything relevant by searching the web?

N/A root cause likely in how we set the `TargetIdeInfo` label (now it has an @ prefix in front of the //

**Comment by sgowroji** [comment] 2023-01-27 03:59
Hi @JamyDev, Could you please provide a sample example to reproduce the above issue. Thanks!

**Comment by JamyDev** [comment] 2023-01-27 23:52
Test repo: https://github.com/JamyDev/go-bazel-sample, just clone and use the .bazelproject file in the root.

Once opened, sync and navigate to `src/jamy.be/sample/sample_test.go`. You'll see that _variable has an error that say "Unexported cost"

Now go to .bazelrc and uncomment the first line, sync again. Now it does not have the error.

**Comment by JamyDev** [comment] 2023-01-28 00:17
Root cause seems to be https://github.com/bazelbuild/intellij/pull/3913 @Wyverald

**Comment by JamyDev** [comment] 2023-01-30 22:45
Dug a little deeper and the root cause of the inconsistency is [these labels using str()](https://github.com/bazelbuild/intellij/blob/master/aspect/intellij_info_impl.bzl#L414-L416) whereas [here](https://github.com/bazelbuild/intellij/blob/master/aspect/intellij_info_impl.bzl#L255) and [here](https://github.com/bazelbuild/intellij/blob/master/aspect/intellij_info_impl.bzl#L273) we use `stringify_label`.

Now I do want to argue that we shouldn't be using `stringify_label` now that bazel 6.0 is making this change to prefix all local paths with `@//`. It seems like the original addition of `stringify_label` was added in #3913 to avoid having to update the test cases to support this new label type. I propose we fix those test cases.

**Comment by Wyverald** [comment] 2023-01-31 14:33
Ah, thanks for digging. It might be more prudent to use the "stringify_label" trick everywhere, since inside Google `--incompatible_unambiguous_label_stringification` is disabled.

**Comment by JamyDev** [comment] 2023-01-31 18:27
@Wyverald can you clarify why we need to strip the `@` prefix for local labels? From what I could gather from your PR is that it was purely for the test cases.

**Comment by Wyverald** [comment] 2023-01-31 19:01
Yeah it is just for test cases. The problem is that the test cases ask for, for example, "give me the target `//foo:bar` from the test fixture" (without the leading `@`(s)), so we need to strip them in the fixture generation code.

Now we _could_ just have the test cases ask for `@//foo:bar` instead and change the fixture generation code to just use `str()`. *But* in Google internal code, `--incompatible_unambiguous_label_stringification` is disabled, so running the same test fixture generation code in Google would still yield `//foo:bar`, even if we switch to `str()`.

AFAIU a lot of code is shared between the Google version and the public version of the intellij plugin, and I don't know how easy it is to maintain a discrepancy here. So I'll leave it up to the maintainers to decide what to do.

**Comment by blorente** [comment] 2023-02-02 15:17
> AFAIU a lot of code is shared between the Google version and the public version of the intellij plugin, and I don't know how easy it is to maintain a discrepancy here. So I'll leave it up to the maintainers to decide what to do.

@mai93 I don't have insight into how much overlap there is, so I think your advice would be useful here.

**Comment by mai93** [comment] 2023-02-14 22:41
This should be fixed with 3ce133cc9e0bc4962671647b01e6514f95821612

**Closed by mai93** 2023-02-14 22:41 UTC
Labels: type: bug, lang: go, product: GoLand, topic: testing
