### ISSUE TITLE
No errors when using class which should not be accessible

### ISSUE THREAD

**Issue by MIOB** [bazelbuild/intellij#271] opened 2018-03-26 15:25 UTC
1. Clone project https://github.com/MIOB/bazel-idea-plugin-usage-sample
2. Import it into idea.
3. Go to java8/src/main/java/sample/java8/App.java
4. Add line ```new AppTest();``` in main method.
5. build project with command bazel build //...
6. Observe compilation error in console

Actual: No errors shown in idea
Expected: There should be error highlighted in idea about usage of class which is not accessible in this package.

**Comment by chaoren** [comment] 2018-03-26 20:12
Duplicate of https://github.com/bazelbuild/intellij/issues/179.

**Closed by chaoren** 2018-03-26 20:12 UTC
