### ISSUE TITLE
BUILD file formatting uses old buildifier

### ISSUE THREAD

**Issue by jwnimmer-tri** [bazelbuild/intellij#261] opened 2018-03-16 15:46 UTC
The automatic BUILD file formatting offered by this plug-in appears to use an old copy of `buildifier`, that doesn't support the `-add_tables` argument.  There are newer releases here: https://github.com/bazelbuild/buildtools/releases.

I'd like to request both that the binary gets updated, and that there is some way to supply my own `tables` file to customize the attribute order of my own rules.

Its a pain point at the moment because my builds enforce that BUILD files are unchanged by buildifier, but because I have a my own `buildifier-tables.json` for my custom rules, the CLion reformatting and and command-line reformatting are fighting.

**Comment by brendandouglas** [comment] 2018-03-16 16:38
I've updated to the latest version. There's no support yet for specifying your own customizations.

For now, perhaps you can work around this by turning off auto-formatting inside the IDE (Settings > Other Settings > Blaze Settings > Automatically format BUILD files on file save)

**Comment by jin** [comment] 2019-04-24 20:51
Closing this as a dupe of #477.

**Closed by jin** 2019-04-24 20:51 UTC
