### ISSUE TITLE
Regression when using docker rules

### ISSUE THREAD

**Issue by manuelnaranjo** [bazelbuild/intellij#2579] opened 2021-04-30 09:07 UTC
#### Description of the issue. Please be specific.

There seems to be a regression in the plugin, we can trigger this consistently, created a sample project to show the issue.

If I apply the following patch, then the problem gets resolved:
```
diff --git a/aspect/intellij_info_impl.bzl b/aspect/intellij_info_impl.bzl
index eede5dd9..05af90b9 100644
--- a/aspect/intellij_info_impl.bzl
+++ b/aspect/intellij_info_impl.bzl
@@ -912,6 +912,8 @@ def collect_java_toolchain_info(target, ide_info, ide_info_file, output_groups):
             for f in toolchain.tools.to_list()
             if f.basename.endswith(".jar")
         ]
+    if not hasattr(toolchain, 'source_version') or not hasattr(toolchain, 'target_version'):
+        return False
     ide_info["java_toolchain_ide_info"] = struct_omit_none(
         javac_jars = javac_jars,
         source_version = toolchain.source_version,
```

I could go ahead an create a PR, the buggy plugin already hit the beta channel.

#### What's the simplest set of steps to reproduce this issue? Please provide an example project, if possible.

https://github.com/manuelnaranjo/intellij-bazel-plugin-bugs-source-version

#### Version information
IdeaUltimate: 2020.3.3
Platform: Linux 3.10.0-1160.24.1.el7.x86_64
Bazel plugin: 2021.04.19.0.1
Bazel: 3.7.2

**Comment by AlexeyGy** [comment] 2021-05-25 21:42
Thank you very much for creating the issue. I've checked and could not reproduce (using the latest stable plugin version https://plugins.jetbrains.com/plugin/8609-bazel/versions/stable/119230). Is it possible that this has been fixed with #2545?

**Comment by manuelnaranjo** [comment] 2021-05-26 05:32
It was happening on the beta channel, I can try to see if there's any
update, stable channel is fine

**Comment by manuelnaranjo** [comment] 2021-05-26 08:53
@AlexeyGy I moved back to the stable channel, I see that the last update on the stable channel is newer than the beta one, I'll notify here if I encounter this problem again, so far so good

**Comment by AlexeyGy** [comment] 2021-05-26 09:51
Hey Manuel,

unfortunately, the error still persisting is on me: I've introduced the beta
channel <https://plugins.jetbrains.com/plugin/8609-bazel/versions/beta>
initially for a pre-release of 2020.3 compatibility. Back then I was not
aware that custom channels ALWAYS override the default stable channel even
if the version number is strictly greater
<https://plugins.jetbrains.com/docs/marketplace/plugin-upload.html#post>.
Since we did not do any uploads to beta afterwards, stable
<https://plugins.jetbrains.com/plugin/8609-bazel/versions/stable> is
actually ahead of beta by now (2021.04.27.0.0 vs 2021.04.19.0.1).
From Friday's release on we will also always drop the newest version into
the beta channel. Beta may then sometimes be more up-to-date if we want to
pre-release changes so you can remain subscribed to beta in the future if
you want.

**Closed** 2021-05-26 09:52 UTC
Labels: topic: bazel
