### ISSUE TITLE
NPE performing bazel sync

### ISSUE THREAD

**Issue by murray-stripe** [bazelbuild/intellij#3855] opened 2022-08-17 14:15 UTC
We've had several users at Stripe experience issues performing a bazel sync through:
  + __Bazel__ -> __Sync__ -> __Sync Project with BUILD Files__
  + __Bazel__ -> __Sync__ -> __Non-Incrementally Sync Project with BUILD Files__
  + Using the Project-View PopupMenu's "__Partially Sync FOLDER/...:all__"

The result is an exception is thrown and the sync is not completed. Stack traces are always from Swing with the error of `Null child not allowed`.
```text
java.lang.NullPointerException: Null child not allowed
	at java.desktop/javax.swing.tree.TreePath.pathByAddingChild(TreePath.java:330)
	at java.desktop/javax.swing.tree.FixedHeightLayoutCache$SearchInfo.getPath(FixedHeightLayoutCache.java:1468)
	at java.desktop/javax.swing.tree.FixedHeightLayoutCache.getPathForRow(FixedHeightLayoutCache.java:213)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI.getPathForRow(BasicTreeUI.java:670)
	at java.desktop/javax.swing.JTree.getPathForRow(JTree.java:2210)
	at com.intellij.util.ui.tree.TreeUtil.visitVisibleRows(TreeUtil.java:1898)
	at com.intellij.util.ui.tree.TreeUtil.visitVisibleRows(TreeUtil.java:1930)
	at com.intellij.util.ui.tree.TreeUtil.collectVisibleRows(TreeUtil.java:1950)
	at com.intellij.util.ui.tree.TreeUtil.collectExpandedObjects(TreeUtil.java:193)
	at com.intellij.util.ui.tree.TreeUtil.collectExpandedPaths(TreeUtil.java:174)
	at com.intellij.ide.util.treeView.TreeState.createOn(TreeState.java:159)
	at com.intellij.ide.util.treeView.TreeState.createOn(TreeState.java:153)
	at com.intellij.ide.projectView.impl.AbstractProjectViewPane.createTreeState(AbstractProjectViewPane.java:724)
	at com.intellij.ide.projectView.impl.AbstractProjectViewPane.saveExpandedPaths(AbstractProjectViewPane.java:730)
	at com.intellij.ide.scopeView.ScopeViewPane.updateFromRoot(ScopeViewPane.java:219)
	at com.intellij.ide.projectView.impl.ProjectViewImpl.refresh(ProjectViewImpl.java:1072)
	at com.google.idea.blaze.base.sync.autosync.ProjectTargetManagerImpl$TargetSyncListener.buildStarted(ProjectTargetManagerImpl.java:151)
	at com.google.idea.blaze.base.sync.BuildPhaseSyncTask.lambda$notifyBuildStarted$1(BuildPhaseSyncTask.java:139)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at com.google.idea.blaze.base.sync.BuildPhaseSyncTask.notifyBuildStarted(BuildPhaseSyncTask.java:139)
	at com.google.idea.blaze.base.sync.BuildPhaseSyncTask.doRun(BuildPhaseSyncTask.java:183)
	at com.google.idea.blaze.base.sync.BuildPhaseSyncTask.run(BuildPhaseSyncTask.java:128)
	at com.google.idea.blaze.base.sync.BuildPhaseSyncTask.runBuildPhase(BuildPhaseSyncTask.java:89)
	at com.google.idea.blaze.base.sync.SyncPhaseCoordinator.runSync(SyncPhaseCoordinator.java:432)
	at com.google.idea.blaze.base.sync.SyncPhaseCoordinator.lambda$syncProject$0(SyncPhaseCoordinator.java:258)
	at com.google.idea.blaze.base.scope.Scope.push(Scope.java:57)
	at com.google.idea.blaze.base.sync.SyncPhaseCoordinator.lambda$syncProject$1(SyncPhaseCoordinator.java:238)
	at com.google.idea.blaze.base.async.executor.ProgressiveTaskWithProgressIndicator.lambda$submitTask$0(ProgressiveTaskWithProgressIndicator.java:79)
	at com.google.idea.blaze.base.async.executor.ProgressiveTaskWithProgressIndicator.lambda$submitTaskWithResult$4(ProgressiveTaskWithProgressIndicator.java:127)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:57)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:624)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:698)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:646)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:623)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:57)
	at com.google.idea.blaze.base.async.executor.ProgressiveTaskWithProgressIndicator.lambda$submitTaskWithResult$5(ProgressiveTaskWithProgressIndicator.java:127)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

From our investigations so far, the problem seems to present itself randomly and without clear resolution. Some users have been able to get past this issue through a battery of fixes, usually after many attempts and it has been unclear what the exact solution has been. Other users have yet to resolve the issue.

Most of our users make use of project-views. While they vary somewhat, they are roughly equivalent to the following example:

__`.ijwb/.bazelproject`__
```yaml
import intellij/my-project.bazelproject

directories:
  .
  -out

derive_targets_from_directories: false

test_sources:
  src/test/*

additional_languages:
  scala
```

__`intellij/my-project.bazelproject`__
```yaml
directories:
  src
  -out

derive_targets_from_directories: false

targets:
  //src/main/java/com/stripe/my_project_api/...
  //src/test/java/com/stripe/my_project_api/...

test_sources:
  src/test/*
```

All of our users are running IntelliJ Ultimate 2021.3 (IU-213.7172.25) and we have noticed this issue across multiple versions of the bazel plugin. The latest report was noticed on __2022.06.28.0.0-api-version-213__. For that user we also attempted to downgrade to __2022.02.23.0.0-api-version-213__, but the issue persisted.

### Resolution Attempts So Far (mixed results):

  + Clean bazel cache `bazel clean --expunge`
  + Invalidate caches and restart
  + Uninstalling/Reinstalling the bazel plugin
  + Uninstalling IJ, cleaning all caches, and re-installing

### Reproduction

We have been unable to reproduce the issues our users are experiencing by replicating their environment. Overriding the experiment settings also doesn't appear to trigger the error, using the following configurations in `idea.properties`:
```properties
experiment.username.override=USER_HAVING_ISSUES
```

**Comment by sethobey-stripe** [comment] 2022-11-29 22:57
I just encountered this same issue today with 2021.3.3.

After numerous attempts to resolve by cleaning bazel caches, invalidate IDE caches, etc., I realized that I was only encountering this error upon having installed [Material Theme UI](https://plugins.jetbrains.com/plugin/8006-material-theme-ui). Once I uninstalled Material Theme UI, the issue appeared to resolve itself.

**Comment by sgowroji** [comment] 2022-11-30 04:39
It seems the issue is caused by Material Theme UI in your case. Not by bazel. @sethobey-stripe Thank you for the information. Could you please verify the same @murray-stripe.

**Comment by sgowroji** [comment] 2023-01-12 06:49
Due to lack of update on the above issue from the issue author.  We are closing this issue now. Please feel free to reach us if you can provide above information. Thanks!

**Closed by sgowroji** 2023-01-12 06:49 UTC
Labels: product: IntelliJ, type: user support, topic: sync, more-data-needed, awaiting-maintainer
