### ISSUE TITLE
Is it not working in the new IntelliJ 2018.2 for anyone else?

### ISSUE THREAD

**Issue by Jdban** [bazelbuild/intellij#375] opened 2018-07-25 18:26 UTC
```
7/25/18
11:14 AM	Required plugins weren't loaded
				Plugin 'Bazel' required for 'monorepo1' project is disabled.
```

I click `Enable Bazel`. Then:
```
11:18 AM	IDE and Plugin Updates: Restart IntelliJ IDEA to activate changes in plugins?
```

Restarting the IDE repeats the process

**Comment by miramar-labs** [comment] 2018-07-25 22:46
it's listed in build_defs.bzl though ..?  
I tried installing from 2017.1 .. it doesn't show up in the jetbrains repo... then tried with 2018.2, still not showing up in the jetbrains repo ... tried building the source .. got errors ... 
what's the trick to installing this?

**Comment by plumpy** [comment] 2018-07-26 00:01
2017.1 is too old. 2017.3 or 2018.1 will work.

**Comment by miramar-labs** [comment] 2018-07-26 02:14
from the docs:
Our plugins are compatible with IntelliJ 2016.1.4 and later (full compatibity details are listed on the JetBrains plugin repository).

are you not sticking to that now?

**Comment by plumpy** [comment] 2018-07-26 02:36
Oh, no, there were issues with the old versions of the plugins so we had to remove them from the repository. Now it's 2017.3 and later, sorry. I'll update the docs.

**Comment by miramar-labs** [comment] 2018-07-26 03:12
ok so I switched to 2018.2 (OS X) and when I import our bazel project i'm seeing an IDE error:

com.google.idea.blaze.base.command.info.BlazeInfoException: blaze info failed with exit code: -1

any idea what that is?

**Comment by plumpy** [comment] 2018-07-26 04:32
Most likely it can't find your bazel binary. Can you set the full path to the binary in Settings→Other Settings→Bazel Settings?

**Comment by miramar-labs** [comment] 2018-07-26 05:47
that was the problem ..
one more question, what are the new compatible min/max intellij versions of other IDE's? (eg CLion)
thanks for the help!

**Comment by jcayzac** [comment] 2018-07-26 06:33
Not showing up for me either in Android Studio 3.1.3 (base on 2017.3 I think).
Installing from disk fails, saying the plugin is not compatible.

**Comment by hsyed** [comment] 2018-07-26 11:31
On the subject of android studio (3.0.3), older versions of android studio paired with the recent plugins are unuseable. (Null pointer exceptions, src folders not being detected , sdk and jdk not being indexed).

The source code for these are not availble so the community cant contribute.

**Comment by hsyed** [comment] 2018-07-26 17:48
@brendandouglas I got the [tutorial](https://docs.bazel.build/versions/master/tutorial/android-app.html) building -- I used AS 3.0.1 and installed the plugin from the plugin tab (2018.06.11.0.3). I have tried bazel 0.14.1 and 0.15.2.  

<ANDROID API 27 Platform> shows up in the external libraries node.

Neither the JDK nor the Android SDK is indexed.

I cannot open the "project structure" view -- it either throws an NPE. Or it just doesn't open at all. So project structure likely doesn't have the SDK or JDK attached.

**Comment by hsyed** [comment] 2018-07-26 18:06
I noticed JDK9 was chosen as the default in "external libraries". I opened the "default project structure"  and provided the location of JDK8 this gets things indexing. 

The "external libraries" still shows JDK9 though and I also still  cannot open the project structure.

**Comment by brendandouglas** [comment] 2018-07-27 12:18
There's some brief discussion on AS 3.1 in #278. We aren't planning to build the plugin against 3.1, but are skipping straight to 3.2 (the release we're currently dogfooding is built against 3.2).

**Comment by lupino3** [comment] 2018-07-28 14:42
Will skipping to AS 3.2 make the plugin compatible with Intellij 2018.2? I had to revert to 2018.1 to get the Bazel plugin working, and am not proceeding with the update until the Bazel plugin is compatible with 2018.2. Thanks!

**Comment by brendandouglas** [comment] 2018-07-30 11:59
The Android Studio and IntelliJ plugins are built and released separately. We'll be releasing against AS 3.2 before IntelliJ (or CLion) 2018.2.

**Comment by jspawar** [comment] 2018-08-27 00:49
Is there any update on this? I'm a little confused by the closed PR above which was closed claiming support for building 2018.2 targets was already made by https://github.com/bazelbuild/intellij/pull/381 which appears to have been merged into master already.

However, building with `bazel build //ijwb:ijwb_bazel_zip --define=ij_product=intellij-2018.2` produces a target that my macOS IntelliJ CE installation (version `182.3684.101`) claims is still incompatible.

**Comment by miramar-labs** [comment] 2018-08-27 02:16
yes, why was this closed? it still does not work on 2018.2 ...

**Comment by brendandouglas** [comment] 2018-08-27 17:38
We're planning to move to 2018.2 in the release after next (3 weeks from now, scheduled to be uploaded on Friday September 14th).

At HEAD in this repo, intellij-2018.2 points to 2018.2.1 (182.3911.36), which is more recent than your version (182.3684.101). If you upgrade to the latest 2018.2, builds from HEAD should work.

We set the plugin XML 'since-build' field to the exact version we build against because the plugin API can change, even between dot releases.

**Comment by oswcab** [comment] 2018-08-29 12:40
I was able to build the plugin from HEAD for latest IntelliJ (2018.2.2, aka, 182.4129.33) and it is working fine.

**Comment by cgruber** [comment] 2018-09-18 00:35
at head, intellij-latest seems to be aliased to 2018.1.  so `--define=intellij-latest` fails.  However, `--define=intellij-2018.2` does seem to work.

**Comment by drichelson** [comment] 2018-09-26 20:21
Is the next release scheduled? If so when might we expect it?

**Comment by ittaiz** [comment] 2018-09-26 20:47
And will it mean 2018.1 won’t be supported?

**Comment by brendandouglas** [comment] 2018-10-08 18:25
It's uploaded now for IntelliJ (and pending JetBrains approval for CLion and AS).

We only upload plugins for a single version, so 2018.1 won't get any updates. It's still supported though, typically for ~2 months (until we stop seeing major performance regressions in the new IDE version internally).

**Closed by brendandouglas** 2018-10-08 18:25 UTC
Labels: Fixed pending release

**Comment by miramar-labs** [comment] 2018-10-08 19:03
we're on 2018.3 now....
