### ISSUE TITLE
Plugin doesn't install on IntelliJ IDEA 2019.1 (Community Edition)

### ISSUE THREAD

**Issue by rezafarzin** [bazelbuild/intellij#628] opened 2019-04-09 16:23 UTC
Bazel plugin doesn't show up on the list of plugins in the reposetory when query in IDE. 
Trying to install the plugin using zip results in error: "Plugin 'Bazel' is incompatible with this installation"

idea version info:
 - IntelliJ IDEA 2019.1 (Community Edition)
 - Build #IC-191.6183.87, built on March 27, 2019
 - JRE: 1.8.0_202-release-1483-b39 amd64
 - JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
 - Linux 4.15.0-47-generic

**Comment by brendandouglas** [comment] 2019-04-09 16:55
Closing as a dupe of https://github.com/bazelbuild/intellij/issues/465

**Closed by brendandouglas** 2019-04-09 16:55 UTC
