### ISSUE TITLE
Cannot debug a java_binary on Windows

### ISSUE THREAD

**Issue by hexaglow** [bazelbuild/intellij#372] opened 2018-07-24 12:43 UTC
When I try to run a java_binary target by clicking the "Debug selected configuration" button in IntelliJ on Windows, it fails to run properly. The Bazel Console indicates that the target built successfully but the program does not start and the following message appears in IntelliJ's event log:

    Error running 'Bazel run :example': Cannot run program "\bin\bash" (in directory "C:\path\to\workspace"): CreateProcess error=2, The system cannot find the file specified

Note that running targets using the "Run selected configuration" button works without issue.

I am using plugin version 2018.07.09.0.1 in IntelliJ version 2018.1.6

**Comment by RNabel** [comment] 2018-07-24 12:58
I believe this falls under https://github.com/bazelbuild/intellij/issues/113. Regarding the actual error: which version of Bazel are you running?

**Comment by hexaglow** [comment] 2018-07-24 13:00
Yes, my apologies, this seems to be a dupe of #113 and #229.

I'm using bazel 0.15.0

**Comment by RNabel** [comment] 2018-07-24 15:51
Ah, that's really unfortunate. I found only one a couple of references to `/bin/bash`, the main one is this: https://github.com/bazelbuild/intellij/blob/d5e4e5073473a4a66d869d40743a08f8846063d5/java/src/com/google/idea/blaze/java/run/BlazeJavaRunProfileState.java#L157.

**Comment by brendandouglas** [comment] 2018-07-24 16:19
Closing as a dupe of #113

**Closed by brendandouglas** 2018-07-24 16:19 UTC

**Comment by darthbinamira** [comment] 2018-09-04 18:18
Apologies in advance for commenting here, but I was able to get debug mode in windows working, although it's a hacky way and if you don't mind building the plugin yourself.

As @RNabel pointed out, it is the same place where I made the changes.

See here https://github.com/darthbinamira/bazel-intellij/commit/8095aeb863bf10e1889b2b27ff3df661e5b66f34
