### ISSUE TITLE
bazel plugin not found in marketplace when update to version 2019.2

### ISSUE THREAD

**Issue by Mycaster** [bazelbuild/intellij#1027] opened 2019-07-26 02:45 UTC
it's worked well at version 2019.1.3。
but bazel plugin shows not compatible  when  update to the newest version (2019.2) .
so I unistalled bazel plugin and try to uninstall , but not found bazel plugin.
as well as cannot rollback to old clion version !!

**Comment by jin** [comment] 2019-07-26 03:42
Duplicate of #731. 

Can you use the [intellij toolbox](https://www.jetbrains.com/toolbox/app/) to download an older version of your IDE?

**Closed by jin** 2019-07-26 03:42 UTC

**Comment by Mycaster** [comment] 2019-07-26 03:52
fine,  thank you.  I didn't find  the way to downgrade to old version

**Comment by Mycaster** [comment] 2019-07-26 03:52
> Duplicate of #731.
> 
> Can you use the [intellij toolbox](https://www.jetbrains.com/toolbox/app/) to download an older version of your IDE?

fine, thank you. I didn't find the way to downgrade to old version

**Comment by iKrushYou** [comment] 2021-04-27 16:58
<img width="1094" alt="image" src="https://user-images.githubusercontent.com/1500721/116282014-4b774380-a758-11eb-9d47-d94d040cfe1c.png">
Same issue on 
```
IntelliJ IDEA 2021.1 (Ultimate Edition)
Build #IU-211.6693.111, built on April 6, 2021
Licensed to Apple Inc. / Alex Krush
Subscription is active until August 30, 2021.
Runtime version: 11.0.10+9-b1341.35 x86_64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
macOS 11.3
GC: ParNew, ConcurrentMarkSweep
Memory: 3987M
Cores: 16
Non-Bundled Plugins: com.jinsihou.react.snippets (1.1.0), com.thvardhan.gradianto (4.4), CheckStyle-IDEA (5.48.0), de.kontext_e.idea.plugins.jqa (2.0), intellij.prettierJS (211.6693.111), org.jetbrains.plugins.go (211.6693.111)
Kotlin: 211-1.4.32-release-IJ6693.72
```
