### ISSUE TITLE
Project sync never finishes

### ISSUE THREAD

**Issue by bpeake13** [bazelbuild/intellij#888] opened 2019-06-05 07:52 UTC
When using the bazel plugin on clion 2019.1 with macos, doing a sync will never exit when a native target exists. It just continues to print out:

Analyzing: target //main:hello-world (0 packages loaded, 0 targets configured)

**Comment by bpeake13** [comment] 2019-06-09 01:51
Should note that this only happens in 2019.1, when going back to 2018.3 the problem doesn't exist.

**Comment by VVVFO** [comment] 2019-06-19 16:05
Experiencing this as well. CLion 2019.1.4 with Bazel 2019.05.13.0.2

**Comment by VVVFO** [comment] 2019-06-19 16:22
After manually running the bazel command:

```sh
/usr/local/bin/bazel build --tool_tag=ijwb:CLion --keep_going --build_event_binary_file=/var/folders/gx/bsstfn0d6_32r75ycyv19j8h0000gn/T/intellij-bep-7e823ae9-3e22-488f-ab9f-a1dd31ca71a0 --nobuild_event_binary_file_path_conversion --curses=no --color=yes --progress_in_terminal_title=no --aspects=@intellij_aspect//:intellij_info_bundled.bzl%intellij_info_aspect --override_repository=intellij_aspect=/Users/redacted/Library/Application Support/CLion2019.1/clwb/aspect --output_groups=intellij-info-cpp,intellij-info-generic,intellij-info-py,intellij-resolve-cpp,intellij-resolve-py -- //main:all
```

It fails due to:

```
ERROR: Skipping 'Support/CLion2019.1/clwb/aspect': couldn't determine target from filename 'Support/CLion2019.1/clwb/aspect'
```

I suppose this occurs due to the space in "Application Support" not being escaped, according to [this comment](https://github.com/bazelbuild/intellij/issues/502#issuecomment-484946699), plugin path could be changed to some path without a space in between, but it feels like more of a hack than a proper solution.

**Comment by chaoren** [comment] 2019-06-19 16:49
We should probably quote the `--override_repository` flag.

**Comment by chaoren** [comment] 2019-06-19 17:26
That's weird. The space doesn't cause a problem on Linux. Adding quotes causes a problem.
It appears the Java command line builder on Linux and Mac behave differently wrt tokenization.

**Comment by chaoren** [comment] 2019-06-19 17:26
Oh wait, I'm using 2018.3, let me try 2019.1.

**Comment by chaoren** [comment] 2019-06-19 18:10
Nope, not a problem in 2019.1 either.

**Comment by VVVFO** [comment] 2019-06-20 01:34
Thanks for looking into this @chaoren! I tried this again this morning and the sync inexplicably succeeded despite the same (incorrect) command was issued. I suspect there may be some other underlying issues, here's the things that I have done in the mean time:

1. Cloned this repo (bazelbuild/intellij) and loaded it into IntelliJ IDEA
2. Confirmed that IntelliJ with Bazel plugin also issues sync command with unescaped space in "Application Support" (but it syncs successfully with some other errors)
3. Hacked getAspectRepositoryOverrideFlag() in AspectStrategyBazel.java to add quotes around the path
4. Rebuilt plugin for CLion

And just before I installed the newly-built .zip in CLion, the sync for that project completed successfully in the background. (insert confused meme) Maybe the override_repository flag isn't the real issue? Also last night the error was not reported from Bazel console and only appeared when I tried to manually run it. But anyways, it works now...

**Comment by bpeake13** [comment] 2019-06-20 06:44
I went back and took a look, it seems on an empty project I can sync, but if I add any c++ target (library or executable) that is when I encounter the bug.

**Comment by chaoren** [comment] 2019-06-20 15:56
@VVVFO oh yes, if you just copy paste the command, it gets tokenized by your shell, so the result would be different from what the IDE did since it launches the process directly without going through a shell.

I'll try to reproduce with C++ targets.

**Comment by chaoren** [comment] 2019-06-20 21:35
Still can't reproduce. Can you share your .bazelproject file, or your entire project?

**Comment by sgowroji** [comment] 2022-09-27 04:36
I'll close the issue. If you still can reproduce it, please reopen.

**Closed by sgowroji** 2022-09-27 04:36 UTC
Labels: type: bug, product: CLion, os: macos, lang: c++, topic: sync, more-data-needed, type: regression
