### ISSUE TITLE
Can't open project in IntelliJ

### ISSUE THREAD

**Issue by solomatov** [bazelbuild/intellij#441] opened 2018-11-11 17:45 UTC
I created a .bazelrc in the root with the following content:

    build --define=ij_product=intellij-latest

But when I import it in IntelliJ I get this:

    ERROR: /home/kostik/Projects/intellij/aswb/BUILD:112:1: Configurable attribute "srcs" doesn't match this configuration: define an intellij product version, e.g. --define=ij_product=intellij-latest.
    ERROR: /home/kostik/Projects/intellij/aswb/BUILD:87:12: Configurable attribute "srcs" doesn't match this configuration: define an intellij product version, e.g. --define=ij_product=intellij-latest.
    ERROR: /home/kostik/Projects/intellij/aswb/BUILD:28:1: Configurable attribute "srcs" doesn't match this configuration: define an intellij product version, e.g. --define=ij_product=intellij-latest.
    ERROR: /home/kostik/Projects/intellij/aswb/BUILD:112:1: Configurable attribute "srcs" doesn't match this configuration: define an intellij product version, e.g. --define=ij_product=intellij-latest.
    ERROR: /home/kostik/Projects/intellij/aswb/BUILD:142:1: Configurable attribute "srcs" doesn't match this configuration: define an intellij product version, e.g. --define=ij_product=intellij-latest.
    ERROR: /home/kostik/Projects/intellij/aswb/BUILD:142:1: Configurable attribute "srcs" doesn't match this configuration: define an intellij product version, e.g. --define=ij_product=intellij-latest.

**Comment by chaoren** [comment] 2018-11-12 17:01
You can't build aswb with `intellij-latest`. You want `android-studio-latest`.

**Comment by chaoren** [comment] 2018-11-12 17:04
When you're importing, are you using the catch-all `//...` target expression? That doesn't work for this project, you have to choose one IDE target, and define the appropriate `ij_product` for that target.

**Comment by solomatov** [comment] 2018-11-12 17:36
But which target should I choose? I want to be able to run tests from the IDE.

**Comment by chaoren** [comment] 2018-11-12 18:10
You can import `ijwb/ijwb.bazelproject` that includes IJwB and all relevant tests, also sets the `--define` flag so you don't need it in your .bazelrc.

**Comment by solomatov** [comment] 2018-11-12 18:14
Everything worked. Thank you!

**Comment by hmemcpy** [comment] 2018-12-03 12:18
I have the same issue, after pulling the latest changes (copybara #460), I am unable to sync the project.
Importing regularly, `ijwb/ijwb.bazelproject`, it has `intellij-latest` defined, getting the same errors as above.
The previous commit (#451) is working fine.
Using bazel 0.19.0, if relevant

**Comment by mskonovalov** [comment] 2019-01-10 04:13
I found an issue but not sure how to fix it.
When you press Sync plugin gets the list of all changed or added files.
Then it tries to compose the build script trying to resolve what targets need to be rebuilt.
When you import the project IDEA creates some files in the root dir (e.g. .ijwb/... and some others). Plugin considers these files as needed to be rebuilt and tries to recognize the bazel target.
The closest target it can find is //:all
That's why the resulting command looks like
```
bazel build ... --output_groups=intellij-info-generic,intellij-info-java -- //ijwb:ijwb_bazel_dev //ijwb:ijwb_lib //:ijwb_tests //:ijwb_ue_tests //:all
```

So even if you have some targets ignored in your .bazelproject
```
directories:
  .
  -aswb
  -clwb
  -cpp
```
it will still try to build it with no luck

Probably need to figure out what exact change broke this but as long as this repository is not real it is not easy.

**Comment by mskonovalov** [comment] 2019-01-10 04:16
The workaround is to add all the added files to ignore so that IDEA would not consider them as new files.

**Comment by mskonovalov** [comment] 2019-01-17 13:37
The fix for the problem is in these 2 PRs

https://github.com/bazelbuild/intellij/pull/497
https://github.com/bazelbuild/intellij/pull/498

**Comment by brendandouglas** [comment] 2019-01-18 14:37
Thanks for the PRs @mskonovalov, I'm applying them upstream, so closing this in the meantime.

The fix will be out in the release after next (and on the github sync branch later today).

**Closed by brendandouglas** 2019-01-18 14:37 UTC
