### ISSUE TITLE
BlazeInfoRunnerImpl crashing @ bazel HEAD

### ISSUE THREAD

**Issue by pmbethe09** [bazelbuild/intellij#100] opened 2017-06-15 14:52 UTC
As a result, IDEA doesn't recognize any WORKSPACE deps or generated code (which all worked fine a few weeks ago).

IDEA: 2017.1.4
Plugin:  2017.05.08.1
bazel: from source @ 9eea05d068a06ab642dd9d86d46ee5fa2e36b02e

ssertion failed
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:168)
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:177)
	at com.google.idea.blaze.base.command.info.BlazeInfo.<init>(BlazeInfo.java:89)
	at com.google.idea.blaze.base.command.info.BlazeInfoRunnerImpl.lambda$runBlazeInfo$2(BlazeInfoRunnerImpl.java:79)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by pmbethe09** [comment] 2017-06-15 15:10
I randomly selected a commit from 1 month ago: a79015e696f163436244887085d3b8a05ec1b0b1
And with that bazel everything works fine.

I have not attempted to binary search and figure out where bazel begins to error.

**Comment by brendandouglas** [comment] 2017-06-15 15:43
Could you paste the results of 'bazel info', using the broken version?

In particular, is 'execution_root' a parent directory of 'bazel-bin' and 'bazel-genfiles'?

**Comment by brendandouglas** [comment] 2017-06-15 16:02
If not, this is a dupe of https://github.com/bazelbuild/bazel/issues/3055

**Comment by pmbethe09** [comment] 2017-06-15 17:12
Aha, as you suspected. bazel-bin and -genfiles are in
execroot/$workspace_name while execution_root is in execroot/$dir_name

**Comment by pmbethe09** [comment] 2017-06-15 23:14
So I guess this can be hacked around by making the workspace.name == the root dir?

**Comment by brendandouglas** [comment] 2017-06-16 12:38
That should be enough to work around it. In the meantime, I'll handle this case in the plugin.

**Comment by ulfjack** [comment] 2017-06-16 12:46
Even if I change the workspace name == root dir, I get a different exception:
```
java.lang.NullPointerException
	at com.google.idea.blaze.base.command.info.BlazeInfo.getGenfilesDirectory(BlazeInfo.java:118)
	at com.google.idea.blaze.python.resolve.BlazePyResolverUtils.resolveGenfilesPath(BlazePyResolverUtils.java:30)
	at com.google.idea.blaze.python.resolve.provider.PyThirdPartyGenfilesImportResolverStrategy.resolveToGoogle3Source(PyThirdPartyGenfilesImportResolverStrategy.java:22)
	at com.google.idea.blaze.python.resolve.PyDynamicImportResolverInitializer.lambda$registerImportResolvers$1(PyDynamicImportResolverInitializer.java:50)
	at com.google.idea.sdkcompat.python.PyImportResolverAdapter.resolveImportReference(PyImportResolverAdapter.java:20)
	at com.jetbrains.python.psi.resolve.PyResolveImportUtil$foreignResults$1.invoke(PyResolveImportUtil.kt:154)
	at com.jetbrains.python.psi.resolve.PyResolveImportUtil$foreignResults$1.invoke(PyResolveImportUtil.kt)
```

**Comment by ulfjack** [comment] 2017-06-16 12:48
It works after restarting IntelliJ.

**Comment by pmbethe09** [comment] 2017-06-16 13:50
Me too, works after a restart.

**Comment by brendandouglas** [comment] 2017-08-08 15:01
Fixed Bazel-side: https://github.com/bazelbuild/bazel/issues/3055

**Closed by brendandouglas** 2017-08-08 15:01 UTC
