### ISSUE TITLE
windows

### ISSUE THREAD

**Issue by wangzhichao-github** [bazelbuild/intellij#2998] opened 2021-10-09 02:30 UTC
#### Version information
IdeaUltimate: 2021.2.2
Platform: Windows 10 10.0
Bazel plugin: 2021.09.07.0.0-api-version-212
Bazel: 4.2.1

**Comment by sgowroji** [comment] 2022-09-29 07:39
We are closing this issue due to inadequate details! Please reopen if you can update with complete reproduce steps!

**Closed** 2022-09-29 07:39 UTC
Labels: product: IntelliJ, os: windows, more-data-needed
