### ISSUE TITLE
Import project failed in Android Studio ("Sync failed")

### ISSUE THREAD

**Issue by oferb** [bazelbuild/intellij#286] opened 2018-04-07 06:05 UTC
Hi,
I'm trying to import a project in Android Studio, and the plugin seems to have a problem running BazelInfo:
`com.google.idea.blaze.base.command.info.BlazeInfoException: blaze info failed with exit code: 2`
Full log: https://pastebin.com/K0JYK05y

I believe the command it's trying to run is a few lines above in the log:
`/home/oferb/opt/bazel_0_12/bazel-release-0.12.0/bazel-bin/src/bazel info --tool_tag=ijwb:AndroidStudio --curses=no --color=yes --experimental_ui=no --progress_in_terminal_title=no --`

Copying and running in the terminal works, with the following output: https://pastebin.com/di7dXf8v

Let me know if I can help repro or debug this issue more (you can reach me at oferb@ :) )

**Comment by jvoung** [comment] 2018-04-10 16:07
The "While parsing option --client_env=: Variable definitions must be in the form of a 'name=value' assignment" looks similar to https://github.com/bazelbuild/intellij/issues/108.

Can you try the workaround about 'GTK_MODULES' environment variable?

**Comment by oferb** [comment] 2018-04-11 19:17
Indeed, `unset GTK_MODULES` did the trick.
Any idea how this could be fixed 'out-of-the-box'?

**Comment by brendandouglas** [comment] 2018-04-11 19:26
The bazel-side issue is https://github.com/bazelbuild/bazel/issues/3196. Closing as a dupe of that.

The underlying JDK bug has already been fixed, so it will work out of the box once JetBrains update their bundled JDK past Java 8u161.

**Closed by brendandouglas** 2018-04-11 19:26 UTC
