### ISSUE TITLE
bazel intelij test runner output race condition (missing test entries for fast tests).

### ISSUE THREAD

**Issue by hsyed** [bazelbuild/intellij#122] opened 2017-08-15 19:50 UTC
Bazel Version: 0.5.3
Plugin Version: 2017.07.05.0.2
Intelij Version: 2017.2.1

Running extremely simple and fast unit test classes will result in tests entries missing in the intellij test runner. Adding a sleep(100) will result in the tests showing up again in the runner.

The tests are run by generating a unit test suite [via a rule](https://gist.github.com/hsyed/77e8e63e5d3ba8d91dfa566c15a271fa) .

**Comment by brendandouglas** [comment] 2017-08-15 20:26
That does sound strange. We don't parse the test results until the Bazel invocation returns. That shouldn't happen until the test runner has finished writing all test results, regardless of test execution time.

Can you check the output xml produced by the test runner? It should be written to [project root]/bazel-testlogs/[target-path]/[target_name]/test.xml

Does it contain data for all the test cases run?

**Comment by hsyed** [comment] 2017-08-16 01:31
@brendandouglas just checked, the xml files contains all the test cases.

**Comment by ittaiz** [comment] 2017-08-16 04:46
Could it be that you're hitting this Bazel issue?
https://github.com/bazelbuild/bazel/issues/3201

**Comment by brendandouglas** [comment] 2017-08-16 15:20
That is likely the cause @ittaiz.

To confirm, would you be able to paste a portion of the test xml containing a missed test case @hsyed?

**Comment by hsyed** [comment] 2017-08-21 20:33
Here is a run of a utility library. All the tests with time=0 don't show up.

```xml
<?xml version='1.0' encoding='UTF-8'?>
<testsuites>
  <testsuite name='cloud.modules.modules.common.util.AllTests' timestamp='1970-01-14T13:42:08.166Z' hostname='localhost' tests='19' failures='0' errors='0' time='0.21' package='' id='0'>
    <properties />
    <system-out />
    <system-err />
  </testsuite>
  <testsuite name='com.payliquid.common.util.ByteUtilsTest' timestamp='1970-01-14T13:42:08.166Z' hostname='localhost' tests='1' failures='0' errors='0' time='0.056' package='' id='1'>
    <properties />
    <testcase name='testBinaryStringFromByte' classname='com.payliquid.common.util.ByteUtilsTest' time='0.056' />
    <system-out />
    <system-err />
  </testsuite>
  <testsuite name='com.payliquid.common.util.PathTest' timestamp='1970-01-14T13:42:08.222Z' hostname='localhost' tests='1' failures='0' errors='0' time='0.001' package='' id='2'>
    <properties />
    <testcase name='testPath' classname='com.payliquid.common.util.PathTest' time='0.001' />
    <system-out />
    <system-err />
  </testsuite>
  <testsuite name='com.payliquid.common.util.RelativeDateParserTest' timestamp='1970-01-14T13:42:08.224Z' hostname='localhost' tests='1' failures='0' errors='0' time='0.095' package='' id='3'>
    <properties />
    <testcase name='testParse' classname='com.payliquid.common.util.RelativeDateParserTest' time='0.095' />
    <system-out />
    <system-err />
  </testsuite>
  <testsuite name='com.payliquid.common.util.StringUtilTest' timestamp='1970-01-14T13:42:08.320Z' hostname='localhost' tests='16' failures='0' errors='0' time='0.056' package='' id='4'>
    <properties />
    <testcase name='joinMultiValues' classname='com.payliquid.common.util.StringUtilTest' time='0.017' />
    <testcase name='testSerialization' classname='com.payliquid.common.util.StringUtilTest' time='0.027' />
    <testcase name='testUpperToCamelCase' classname='com.payliquid.common.util.StringUtilTest' time='0.0' />
    <testcase name='testEnd' classname='com.payliquid.common.util.StringUtilTest' time='0.0' />
    <testcase name='testReplaceSuffix' classname='com.payliquid.common.util.StringUtilTest' time='0.0' />
    <testcase name='testStem' classname='com.payliquid.common.util.StringUtilTest' time='0.0' />
    <testcase name='testConstToCamelCase' classname='com.payliquid.common.util.StringUtilTest' time='0.0' />
    <testcase name='testAdvancedFormat' classname='com.payliquid.common.util.StringUtilTest' time='0.006' />
    <testcase name='testShortest' classname='com.payliquid.common.util.StringUtilTest' time='0.0' />
    <testcase name='testObfuscate' classname='com.payliquid.common.util.StringUtilTest' time='0.0' />
    <testcase name='testFormatMonth' classname='com.payliquid.common.util.StringUtilTest' time='0.0' />
    <testcase name='testGetCommonCamelCaseSuffix' classname='com.payliquid.common.util.StringUtilTest' time='0.0' />
    <testcase name='testIsExpression' classname='com.payliquid.common.util.StringUtilTest' time='0.0' />
    <testcase name='testGetCommonPrefix' classname='com.payliquid.common.util.StringUtilTest' time='0.0' />
    <testcase name='testGetCommonSuffix' classname='com.payliquid.common.util.StringUtilTest' time='0.0' />
    <testcase name='testIsInteger' classname='com.payliquid.common.util.StringUtilTest' time='0.0' />
    <system-out />
    <system-err />
  </testsuite>
</testsuites>
```

**Comment by brendandouglas** [comment] 2017-09-10 17:04
Thanks, this is indeed bazelbuild/bazel#3201. This needs to be fixed in the test runner, with no plugin-side changes required, so closing this as a duplicate.

**Closed by brendandouglas** 2017-09-10 17:04 UTC
