### ISSUE TITLE
scala sub-directories do no appear in project view in "hide Empty Middle Packages"

### ISSUE THREAD

**Issue by nadavwe** [bazelbuild/intellij#276] opened 2018-03-28 14:44 UTC
I just upgraded my intellij to 2018.01 and my bazel plugin to 2018.01.02.0.1.
I see that all of my code sources are gone from project view!
each directory with main/scala or test/scala does not appear.
main/resources and test/resources do appear.

Thanks!

@ittaiz

**Comment by johnynek** [comment] 2018-04-03 05:44
Cc @gkk-stripe @andygscott

**Comment by nadavwe** [comment] 2018-04-03 08:56
Hey @chaoren,
did you see something similar?
what am I doing wrong?
Thanks...

**Comment by nadavwe** [comment] 2018-04-03 11:31
due to @natansil advice i removed the "hide Empty Middle Packages" checkbox and now I can see the files.
so this is a minor issue.

**Comment by brendandouglas** [comment] 2018-04-03 13:06
Closing as a dupe of #268. It is something I've been meaning to fix -- though as you found, there is a workaround.

**Closed by brendandouglas** 2018-04-03 13:06 UTC
