### ISSUE TITLE
Scala sources marked as "unsynced" in basic example project  

### ISSUE THREAD

**Issue by ittaiz** [bazelbuild/intellij#97] opened 2017-06-14 11:57 UTC
Hi,
I have a basic example [project](https://github.com/ittaiz/bazel-scala-getting-started) for bazel and scala.
When I try to import it to intellij all three sources are "unsynced".
If I click on one of the files IntelliJ asks to "setup a scala sdk" and when I do I see #96. 
Bazel console shows no errors and so does the problems view.
Versions:
rules_scala: 5d6ff512652b8b55f5d26f6ea69e05d86582d996 (this morning)  
Intellij bazel plugin: 2017.05.08.1
Bazel: 55f40c8ea4f1e7bf81552bfe4377e26768e85f2c (June 6th)
Intellij:
IntelliJ IDEA 2017.1.2
Build #IU-171.4249.39, built on April 25, 2017
JRE: 1.8.0_112-release-736-b16 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.11.6

**Comment by ittaiz** [comment] 2017-06-14 12:07
let's wait with this one. I might have been actually running with Bazel 0.4.5 in intellij (in terminal I have an alias).

**Comment by ittaiz** [comment] 2017-06-14 12:12
no. Updated bazel settings and re-imported. Still doesn't work.
`Command: /Users/ittaiz/workspace/bazel/bazel-bin/src/bazel info...`

**Comment by chaoren** [comment] 2017-06-14 20:22
Can you share your .bazelproject file? If your file isn't reachable from the targets specified in the `targets:` section, then it'll show up as unsynced'

**Comment by ittaiz** [comment] 2017-06-14 20:33
yes sorry, forgot.
```

directories:
  # Add the directories you want added as source here
  # By default, we've added your entire workspace ('.')
  .

targets:
  # Add targets that reach the source code that you want to resolve here
  # By default, we've added all targets in your workspace
  //...

additional_languages:
  # Uncomment any additional languages you want supported
  # android
  # dart
  # javascript
  scala
  # typescript
```

**Comment by chaoren** [comment] 2017-06-14 20:59
I'm getting this:

![image](https://user-images.githubusercontent.com/10055601/27154180-18bae5ea-5122-11e7-825a-1a06793d93e6.png)

And I know exactly why junit isn't resolving.
[This line](https://github.com/bazelbuild/rules_scala/blob/5d6ff512652b8b55f5d26f6ea69e05d86582d996/scala/scala.bzl#L864) was added after my work on the aspect. This kind of thing is probably going to keep happening every time you add a new implicit dependency to the rules. And we'll have to update [the aspect](https://github.com/bazelbuild/bazel/blob/0433a20572085b2a0cde756b65dbaebed154b18c/tools/ide/intellij_info_impl.bzl#L26) to follow them every time.

The java rules have `_java_toolchain` and C++ rules have `_cc_toolchain`, single implicit dependency that explicitly depends on everything else. If scala had something similar (one for each rule type is fine), then it would make everything much easier.

**Comment by ittaiz** [comment] 2017-06-14 21:10
I see. We have a ticket for creating a scala_toolchain but no has gotten
around to it yet :(
Also,
With specs2 this might be a bigger problem since it's dependency graph
changes more frequently. Don't have a better answer though for the time
being.

**Comment by ittaiz** [comment] 2017-06-25 14:50
@chaoren should this happen even if I explicitly declare the dependencies for my targets? In our internal repo we explicitly declare everything but still see these happen.
I suspect (but not sure) this is because we depend on the file target of external dependencies.
This is due to the fact that Bazel's ijar currently doesn't play well with Scala's macros.
In `third_party/aopalliance` we have a BUILD file with (license and load omitted for simplicity) :
```
package(default_visibility = ["//visibility:public"])

scala_library(
    name = "aopalliance",
    exports = ["@aopalliance_aopalliance//jar:file"],
)
```
And in the WORKSPACE file we have:
```
maven_jar(
    name = "aopalliance_aopalliance",
    artifact = "aopalliance:aopalliance:1.0",
)
```

**Comment by chaoren** [comment] 2017-06-25 14:52
> I suspect (but not sure) this is because we depend on the file target of
external dependencies.

This is exactly the reason. If blaze doesn't recognize the dependencies as
Java, then neither will the IDE.

On Jun 25, 2017 10:50, "Ittai Zeidman" <notifications@github.com> wrote:

@chaoren <https://github.com/chaoren> should this happen even if I
explicitly declare the dependencies for my targets? In our internal repo we
explicitly declare everything but still see these happen.
I suspect (but not sure) this is because we depend on the file target of
external dependencies.
This is due to the fact that Bazel's ijar currently doesn't play well with
Scala's macros.
In third_party/aopalliance we have a BUILD file with (license and load
omitted for simplicity) :

package(default_visibility = ["//visibility:public"])

scala_library(
    name = "aopalliance",
    exports = ["@aopalliance_aopalliance//jar:file"],
)

And in the WORKSPACE file we have:

maven_jar(
    name = "aopalliance_aopalliance",
    artifact = "aopalliance:aopalliance:1.0",
)

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/bazelbuild/intellij/issues/97#issuecomment-310906994>,
or mute the thread

**Comment by ittaiz** [comment] 2017-06-25 14:56
Wow. This is a serious blocker. 
cc @damienmg who was looped in a few times on both https://github.com/bazelbuild/bazel/issues/632 and on https://github.com/bazelbuild/rules_scala/issues/118
@chaoren is there any way to workaround this on the IDE side?

**Comment by chaoren** [comment] 2017-06-25 15:01
> @chaoren <https://github.com/chaoren> is there any way to workaround this
on the IDE side?

No, I don't think there is. Bazel is always the IDE's source of truth. We
only know what's passed to us by bazel via the aspect.

On Jun 25, 2017 10:56, "Ittai Zeidman" <notifications@github.com> wrote:

Wow. This is a serious blocker.
cc @damienmg <https://github.com/damienmg> who was looped in a few times on
both bazelbuild/bazel#632 <https://github.com/bazelbuild/bazel/issues/632>
and on bazelbuild/rules_scala#118
<https://github.com/bazelbuild/rules_scala/issues/118>
@chaoren <https://github.com/chaoren> is there any way to workaround this
on the IDE side?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/bazelbuild/intellij/issues/97#issuecomment-310907359>,
or mute the thread

**Comment by ittaiz** [comment] 2017-06-25 15:06
Maybe the aspect should also accept these kind of targets? They are auto
generated by Bazel, maybe you can notice when you're in something like this
and accept it (since we're still talking about a jar)

**Comment by damienmg** [comment] 2017-06-26 05:14
/cc @steren for prioritization.

IIUC bazelbuild/bazel#632 is basically the blocker? /cc @iirina because java

**Comment by ittaiz** [comment] 2017-06-27 13:55
https://github.com/bazelbuild/bazel/issues/632 is indeed the root issue but I think that it is a much harder problem to solve.
Seeing as these are synthetic targets generated from `maven_jar` then maybe a hint can be added to them and the plugin will be able to also pick up these targets as dependencies in intellij?

**Comment by ittaiz** [comment] 2017-06-29 19:55
Any update?

**Comment by chaoren** [comment] 2017-06-30 19:08
> maybe a hint can be added to them and the plugin will be able to also pick up these targets as dependencies in intellij

It's not as simple as just adding them and having them recognized. We need all the information that bazel provides for java targets (dependencies, exports, other aspects, etc).

Another way to fix this would be to add all of the jars to some unused implicit dep (while still using the files in the current implicit deps). We can followed the dummy implicit dep, while the rules just ignore them. This allows a single _scala_toolchain dep too, which can just depend on all the jars for us to follow and pickup.

**Comment by ittaiz** [comment] 2017-06-30 19:14
Do you mean to add another dummy target (maybe even under third party) that
is java_library which depends on the "//jar" target? Will this allow the
plugin to get access to the needed metadata?
Not sure what you meant by the toolchain part

**Comment by chaoren** [comment] 2017-06-30 19:16
I'm writing up a pull request.

**Comment by ittaiz** [comment] 2017-06-30 19:18
To rules_scala? Not sure it uses the "//jar:file" target. We use that
extensively in our repo.

**Comment by chaoren** [comment] 2017-06-30 19:30
I'll add an attr to all the rules, as long as your repo doesn't change the new attr I'm adding (which it shouldn't because it should only exist for the IDE), it should work.

**Comment by chaoren** [comment] 2017-06-30 20:52
Done: https://github.com/bazelbuild/rules_scala/pull/241
That change and a follow up change to the intellij aspect should fix this issue.

**Comment by ittaiz** [comment] 2017-07-04 19:26
@chaoren I might be confused so I want to verify- your rules scala PR isn't related to "//jar:file" problem at all (since we don't use that pattern there). Is the above problem only related to rules<->aspect mismatch?
If so I'll open a new ticket about imports not being recognized when using "//jar:file" so we can move the discussion about them elsewhere

**Comment by chaoren** [comment] 2017-07-04 19:35
> your rules scala PR isn't related to "//jar:file" problem at all (since we don't use that pattern there).

This PR avoids the problem for the IDE at least. Since we no longer have to care about the files when we have the equivalent jars that we can recognize in one neat place.

> Is the above problem only related to rules<->aspect mismatch?

I'm not sure what you mean by this. But it sounds like you're misunderstanding the purpose of the PR.

**Comment by ittaiz** [comment] 2017-07-04 19:46
I'll ask it in a different way-
Does rules_scala head have any problem of using file targets instead of jars? I think it doesn't. If I'm right then that means the problem solved by your PR is the neat grouping to the attribute and not a solution for everyone who need "//jar:file"

**Comment by chaoren** [comment] 2017-07-04 19:50
> Does rules_scala head have any problem of using file targets instead of jars? I think it doesn't.

Yes, you are correct. But you said your private repo uses "//jar:file" for the implicit libraries, it should help there.

> not a solution for everyone who need "//jar:file"

I'm afraid there won't be a general solution for "//jar:file" from the IDE side. It needs to be fixed from the bazel side so you can use "//jar" only.

**Comment by ittaiz** [comment] 2017-07-04 19:59
now I understand. My private repo uses it for everything so yes also for these but I think the real problem this solves (which you already commented on) is moving the duplication (and hence the chase) from the IDE side to rules_scala side. Since even without "//jar:file" we had a problem of going out of sync.
In any case, I'm trying to advance a solution on the Bazel side of things.
Ping me when you're ready on that PR and we'll merge it in

**Comment by helenalt** [comment] 2017-07-05 16:40
@dslomov please take a look at chaoren's comment whether this is a viable solution in Bazel

**Comment by dslomov** [comment] 2017-07-05 16:59
I have no clue. @chaoren or @ittaiz , maybe you can summarize the problem for me - this thread is long and winding. Thank you!

**Comment by chaoren** [comment] 2017-07-05 18:41
@dslomov The issue is that (for reason I don't fully understand) using ijars as libraries can break scala compilation, so they must sometimes use filegroup instead of java_import to compile against their libraries. When they do that, however, these libraries won't be visible to the IDE, since filegroups don't have java providers.

The one true fix is in bazel to fix whatever is causing them to need to use filegroups in the first place (the ijar issue that I don't fully understand). I'll continue to experiment if I can work around it on our end, but even then it'll be a hack on top of a hack.

The bazel issue in question: https://github.com/bazelbuild/bazel/issues/632

**Comment by dslomov** [comment] 2017-07-05 18:58
Thanks for explanations @chaoren. One cleaner workaround I can think of is: instead of using filegroups, one can write a java_import-equivalent rule (using java_common.create_provider) to propagate jars instead of ijars. Or figure out the resolution to https://github.com/bazelbuild/bazel/issues/632. 

Overall I think we should address this in Bazel preferably, not in IDE plugin (if we need to add attributes to rules just for IDE plugin, we have lost :()

**Comment by ittaiz** [comment] 2017-07-10 16:32
Back here.
Chaoren,
Any ideas why my latest version doesn't work?

**Comment by ittaiz** [comment] 2017-07-10 17:38
I'll cross post it here to revive the thread:
@chaoren Thanks!
I tried adding `scala` attribute, got into a bit of a fight with the aspect and what it wants but got to the same place at the end. Sync passes successfully but imports are still red.
```
def _scala_import_impl(ctx): 
    java_provider = java_common.create_provider(
        compile_time_jars = ctx.attr.jar_to_import.files,
        runtime_jars = ctx.attr.jar_to_import.files,
    )
    rule_outputs = struct(
          ijar = ctx.attr.jar_to_import.files.to_list()[0],
          class_jar = ctx.attr.jar_to_import.files.to_list()[0],
    )
    scalaattr = struct(
      outputs = rule_outputs,
      #does not seem to help or hurt IDE so I commented it out
      #compile_jars = depset(ctx.attr.jar_to_import.files), 
      #transitive_runtime_jars = depset(ctx.attr.jar_to_import.files),
    )
    return struct(
        scala = scalaattr,
        providers = [java_provider],
    )


scala_import = rule(
  implementation=_scala_import_impl,
  attrs={
      "jar_to_import": attr.label(allow_files=True),
      },
)
```
Implementation is pushed to this [repo](https://github.com/ittaiz/scala_macro_bazel_issue/tree/master) and of course is hacky to understand what's going on. End game shouldn't include ctx.attr.jar_to_import.files.to_list()[0]

**Comment by chaoren** [comment] 2017-07-10 22:12
@ittaiz yes, sorry we have to also update the plugin to recognize the new scala_import rule (we need to know which rules are expected to have sources vs just jars).
What you have here does work after changes on our side (basically just need scala.outputs).

**Comment by ittaiz** [comment] 2017-07-11 06:14
@chaoren thanks! 
Two questions:
1. Do you know what I should do instead of `ctx.attr.jar_to_import.files.to_list()[0]`? It didn't like it when I just gave it the `depset` and the above doesn't seem like a sustainable solution
2. How can I manually test this out? Asking since I want to add more features (like `runtime_deps`) and I want to test this works. To do it end-to-end I'll obviously need to do manual testing but that will also help me understand the contract I want to express in rules_scala. I'm guessing I'll need to test it against bazel HEAD and plugin HEAD, right? Any other changes/hints?

**Comment by chaoren** [comment] 2017-07-11 17:14
> 1. Do you know what I should do instead of `ctx.attr.jar_to_import.files.to_list()[0]`?

This should work too. This is what we look for in the java rules. You can also allow multiple jars if you do it this way. Though I would probably change `jar_to_import` to just `jars` or `jar` to match `java_import`.

    jars = [struct(
        ijar = jar,
        class_jar = jar,
    ) for jar in ctx.attr.jar_to_import.files]
    scalaattr = struct(
        outputs = struct(jars = jars),
    )

> 2. How can I manually test this out? ... I'm guessing I'll need to test it against bazel HEAD and plugin HEAD, right? Any other changes/hints?

We'll release the change to support `scala_import` this Friday, so yes you'll need bazel and plugin HEAD. You can probably compare the `<target>.intellij-info.txt` file under `bazel-bin` with a similar `java_import` rule after running bazel sync. They should be mostly identical except for the Java toolchain and the ijar.

**Comment by ittaiz** [comment] 2017-07-11 17:49
Sounds good.
Do I still need Bazel head because the aspect is there?
If you "whitelist" scala_import then I can later change its implementation
from exposing outputs with single jars to exposing depset without you
changing something right?

**Comment by chaoren** [comment] 2017-07-11 18:20
> Do I still need Bazel head because the aspect is there?

Actually, after bazel 5.0, the plugin should be using the aspect bundled in the plugin, instead of the one in bazel. So you probably don't need bazel head.

> If you "whitelist" scala_import then I can later change its implementation
from exposing outputs with single jars to exposing depset without you
changing something right?

Yes. That is correct, but the scalaattr will have to be similar to the other scala rules or like java rules. If you need to make it different, we can still handle it by changing the aspect.

**Comment by ittaiz** [comment] 2017-07-11 19:28
Awesome!
Waiting for the release.

**Comment by ittaiz** [comment] 2017-07-15 06:18
Hi,
Was it released?

**Comment by chaoren** [comment] 2017-07-15 16:32
Sorry, there was some delay. Should be available now.

**Comment by ittaiz** [comment] 2017-07-15 18:00
Great, thanks!
I'll try it out and update you.

**Comment by ittaiz** [comment] 2017-07-18 12:48
@chaoren Not sure if I'm doing something wrong but the import is still red in the reproduction repo.
I've of course upgraded my plugin.
Any chance you can try and load it and see why it's misbehaving?

**Comment by chaoren** [comment] 2017-07-18 14:55
Looks fine on my end:

![image](https://user-images.githubusercontent.com/10055601/28323511-09f121e2-6ba7-11e7-8e55-31e81292d523.png)

Bazel plugin version: 2017.07.05.0.2
![image](https://user-images.githubusercontent.com/10055601/28323532-26b9a1dc-6ba7-11e7-917c-92ae2f6617d7.png)

Scala plugin version: 2017.1.20
![image](https://user-images.githubusercontent.com/10055601/28323585-46f796a2-6ba7-11e7-9ed8-4c410e388b48.png)

$ /usr/bin/bazel version
Build label: 0.5.2
![image](https://user-images.githubusercontent.com/10055601/28323633-64b60fac-6ba7-11e7-963a-009fca65b1b3.png)

**Comment by ittaiz** [comment] 2017-07-18 15:49
:( strange.
AFK but I'll compare later tonight. I upgraded my scala plugin today as
well, is the version you wrote above if the scala plugin the latest?

**Comment by chaoren** [comment] 2017-07-18 16:27
> is the version you wrote above if the scala plugin the latest?

Yes. I tested with the public bazel plugin, so it should be the latest.

**Comment by ittaiz** [comment] 2017-08-06 07:40
Partial success.
I tweaked the above rule a bit more to support `runtime_deps`, `neverlink` and to not use `ijar` (which as you might remember was the reason not to use `java_library`) and am failing on a new problem.
```
Multiple entries with same key: javax.servlet-api-3.1.0_19a1b=javax.servlet-api-3.1.0_19a1b and javax.servlet-api-3.1.0_19a1b=javax.servlet-api-3.1.0_19a1b
java.lang.IllegalArgumentException: Multiple entries with same key: javax.servlet-api-3.1.0_19a1b=javax.servlet-api-3.1.0_19a1b and javax.servlet-api-3.1.0_19a1b=javax.servlet-api-3.1.0_19a1b
	at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:136)
	at com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:98)
	at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:84)
	at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:295)
	at com.google.idea.blaze.scala.sync.importer.BlazeScalaWorkspaceImporter.importWorkspace(BlazeScalaWorkspaceImporter.java:95)
	at com.google.idea.blaze.scala.sync.BlazeScalaSyncPlugin.lambda$updateSyncState$0(BlazeScalaSyncPlugin.java:111)
	at com.google.idea.blaze.base.scope.Scope.push(Scope.java:37)
	at com.google.idea.blaze.scala.sync.BlazeScalaSyncPlugin.updateSyncState(BlazeScalaSyncPlugin.java:107)
	at com.google.idea.blaze.base.sync.BlazeSyncTask.lambda$doSyncProject$2(BlazeSyncTask.java:395)
	at com.google.idea.blaze.base.scope.Scope.push(Scope.java:60)
	at com.google.idea.blaze.base.sync.BlazeSyncTask.doSyncProject(BlazeSyncTask.java:390)
	at com.google.idea.blaze.base.sync.BlazeSyncTask.syncProject(BlazeSyncTask.java:192)
	at com.google.idea.blaze.base.sync.BlazeSyncTask.lambda$run$0(BlazeSyncTask.java:159)
	at com.google.idea.blaze.base.scope.Scope.push(Scope.java:60)
	at com.google.idea.blaze.base.scope.Scope.root(Scope.java:52)
	at com.google.idea.blaze.base.sync.BlazeSyncTask.run(BlazeSyncTask.java:140)
	at com.google.idea.blaze.base.async.executor.BlazeExecutor$2.run(BlazeExecutor.java:99)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
	at com.google.idea.blaze.base.async.executor.BlazeExecutor$3.call(BlazeExecutor.java:108)
	at com.google.idea.blaze.base.async.executor.BlazeExecutor$3.call(BlazeExecutor.java:105)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

The use-case for such an issue are two un-related targets consuming the same maven jar where the first is using it as `neverlink` (for example a library) and the second as `runtime_deps` (for example a binary).


`scala_import.bzl`
```
def _scala_import_impl(ctx):
    runtime_jars = _collect(ctx.attr.runtime_deps)
    if not ctx.attr.neverlink:
      runtime_jars += ctx.attr.jar.files
    return struct(
        scala = struct(
          outputs = struct(
            ijar = None,
            class_jar = ctx.attr.jar.files.to_list()[0],
          ),
        ),
        providers = [
          java_common.create_provider(
            compile_time_jars = ctx.attr.jar.files,
            runtime_jars = runtime_jars,
          )
        ],
    )
def _collect(runtime_deps):
    transitive_runtime_jars = depset()
    for runtime_dep in runtime_deps:
        transitive_runtime_jars += runtime_dep[java_common.provider].transitive_runtime_jars
    return transitive_runtime_jars


scala_import = rule(
  implementation=_scala_import_impl,
  attrs={
      "jar": attr.label(),
      "runtime_deps": attr.label_list(),
      "neverlink": attr.bool(default=False, mandatory=False),
      },
)
```

repo: https://github.com/ittaiz/bazel-intellij-scala-neverlink/tree/master

**Comment by ittaiz** [comment] 2017-08-06 14:07
@chaoren If you think the above `scala_import` is reasonable then maybe we should move the discussion to #106 which is at least the same symptom?

**Comment by chaoren** [comment] 2017-08-11 16:24
Are there any other problems besides the one in #106?

**Comment by ittaiz** [comment] 2017-08-11 17:14
I think not.
We had the aspect/rule mismatch which you fixed and the ijar problem which
you helped me resolve.
The last thing standing currently is 106 (that means which isn't captured
in other issues).
Thanks!

**Comment by ittaiz** [comment] 2017-09-05 13:23
thanks @chaoren waiting for #106

**Closed** 2017-09-05 13:23 UTC

**Comment by johnynek** [comment] 2017-10-11 18:51
@ittaiz it seems that we need to have a scala_import / scala_jar in the scala rules. Have you thought of making a PR on this?

**Comment by ittaiz** [comment] 2017-10-11 19:03
Indeed.
The version I have out there is very very basic.
I fiddled with a better one which supports both deps and runtime deps and
will support neverlink but just yesterday I found a big bug in it.
I hope middle of next week I'll have a PR ready.

**Comment by ittaiz** [comment] 2017-12-04 04:09
This was indeed fixed, sorry for not closing sooner
