### ISSUE TITLE
IDE fatal error

### ISSUE THREAD

**Issue by ittaiz** [bazelbuild/intellij#184] opened 2017-12-11 19:08 UTC
No idea what happened
```
AWT events are not allowed inside write action: sun.awt.PeerEvent[INVOCATION_DEFAULT,runnable=sun.awt.SunToolkit$1@7133129e,notifier=null,catchExceptions=false,when=1513019263170] on sun.lwawt.macosx.LWCToolkit@17828bff
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:132)
	at com.intellij.openapi.application.impl.NoSwingUnderWriteAction.a(NoSwingUnderWriteAction.java:36)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:376)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
	at java.awt.Dialog.show(Dialog.java:1084)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:736)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:458)
	at com.intellij.openapi.ui.DialogWrapper.invokeShow(DialogWrapper.java:1686)
	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1635)
	at com.intellij.openapi.ui.DialogWrapper.showAndGet(DialogWrapper.java:1650)
	at com.intellij.openapi.fileEditor.impl.NonProjectFileWritingAccessProvider.a(NonProjectFileWritingAccessProvider.java:113)
	at com.intellij.openapi.fileEditor.impl.NonProjectFileWritingAccessProvider.requestWriting(NonProjectFileWritingAccessProvider.java:89)
	at com.intellij.openapi.vcs.readOnlyHandler.ReadonlyStatusHandlerImpl.ensureFilesWritable(ReadonlyStatusHandlerImpl.java:98)
	at com.intellij.openapi.vfs.ReadonlyStatusHandler.ensureFilesWritable(ReadonlyStatusHandler.java:30)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.requestWriting(FileDocumentManagerImpl.java:506)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor.d(AbstractLayoutCodeProcessor.java:320)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor.run(AbstractLayoutCodeProcessor.java:252)
	at com.google.idea.blaze.base.buildmodifier.FileSaveHandler.formatBuildFile(FileSaveHandler.java:51)
	at com.google.idea.blaze.base.buildmodifier.FileSaveHandler.beforeDocumentSaving(FileSaveHandler.java:39)
	at sun.reflect.GeneratedMethodAccessor369.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.a(FileDocumentManagerImpl.java:165)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.a(FileDocumentManagerImpl.java:132)
	at com.sun.proxy.$Proxy23.beforeDocumentSaving(Unknown Source)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.c(FileDocumentManagerImpl.java:428)
	at com.intellij.pom.core.impl.PomModelImpl.guardPsiModificationsIn(PomModelImpl.java:411)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.e(FileDocumentManagerImpl.java:427)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.d(FileDocumentManagerImpl.java:390)
	at com.intellij.openapi.application.WriteAction.run(WriteAction.java:91)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.a(FileDocumentManagerImpl.java:390)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.saveDocument(FileDocumentManagerImpl.java:344)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.saveDocument(FileDocumentManagerImpl.java:334)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.d(FileDocumentManagerImpl.java:283)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:314)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:416)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.b(IdeEventQueue.java:821)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:649)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```
says it happened 7 times since last clear

**Comment by brendandouglas** [comment] 2017-12-11 21:23
Which Bazel plugin version are you using?

**Comment by ittaiz** [comment] 2017-12-11 21:27
The one we built off of `29b78dd208cb942f480f6aa5c5f43acf174e3306`

**Comment by brendandouglas** [comment] 2017-12-11 21:51
OK, good. This should be fixed at head then (by the call to NonProjectFileWritingAccessProvider.isWriteAccessAllowed in FileSaveHandler).

**Comment by ittaiz** [comment] 2017-12-12 04:49
Awesome!
Any chance you also fixed a problem with a dialog of editing "non
workspace" projects?
If I have multiple windows opens or different Bazel workspaces and I'm
editing files I sometimes get a dialog saying I'm editing a file which
isn't part of the workspace and that is forbidden. Needles to say the file
is part of the workspace.

**Comment by brendandouglas** [comment] 2017-12-12 13:44
That dialog is coming from upstream IntelliJ. It will happen for files which are outside your IntelliJ project (but inside your Bazel workspace).

**Comment by ittaiz** [comment] 2017-12-12 16:18
But they're not. It's happening for ones which are inside my workspace.
And I didn't see it with non Bazel stuff

**Comment by chaoren** [comment] 2017-12-12 16:22
> dialog of editing "non workspace" projects

Could you please post a screenshot of what you're talking about?

**Comment by brendandouglas** [comment] 2017-12-12 17:09
I have noticed this happening in 2017.2. I don't expect it's fixed at HEAD.

Haven't had a chance to investigate what's causing this yet. Does running a bazel sync resolve this?

**Comment by ittaiz** [comment] 2017-12-21 11:36
I think the plugin has a serious problem of multi instance references.
The editing problem happens when you have multiple *bazel* intellij projects and additionally today I noticed that sometimes clicking the `sync` button pops up a different *bazel* intellij project than the one I clicked on.
The screenshot is when I edited a file *in the same project* but for some reason it thinks the project is different
<img width="1680" alt="screen shot 2017-12-14 at 6 33 36" src="https://user-images.githubusercontent.com/1378327/34254227-cbe73af8-e653-11e7-8255-dcb23f95cdbf.png">
cc @hmemcpy

**Comment by BrentDouglas** [comment] 2018-01-10 11:50
I would also like to note that I see the issue displayed in @ittaiz screenshot above when I have other IDEA instances open that are not bazel projects. I see it when I have one bazel instance open which I am editing the file in and one other maven instance open which the popup appears in.

**Comment by hmemcpy** [comment] 2018-01-25 12:52
This bug (the multi-instance thing) reproduced quite easily on 2017.2.6 - open a bazel project, then open another bazel project **from the Open menu** (so it doesn't actually open as a bazel project). Any attempt to modify and save a BUILD file in that second project will cause a popup to appear in the first.

HOWEVER, I was not able to reproduce this in 2017.3.3. Perhaps this is an IntelliJ bug that was already fixed!

**Comment by brendandouglas** [comment] 2018-04-26 16:36
Has anyone been able to reproduce this in 2017.3? If not, I'll assume it's fixed upstream and close this.

**Comment by BrentDouglas** [comment] 2018-04-26 16:40
I haven't seen it in a 2017.3 and it used to be very frequent

**Comment by brendandouglas** [comment] 2018-04-26 17:48
Thanks, that sounds promising. In that case, I'll close this.

**Closed by brendandouglas** 2018-04-26 17:48 UTC
