### ISSUE TITLE
Kotlin - cannot run a single test

### ISSUE THREAD

**Issue by dylanShark** [bazelbuild/intellij#2301] opened 2021-01-16 02:56 UTC
Hi Bazel Intelij Plugin team,

For Java tests, if I click the debug button next to a test method, it will only run that single test method in the entire test class (if I click Edit Configuration it has the bazel flag "--test_filter=\<test class name\>#\<test method name\>"). 
However, for Kotlin tests, when I click debug button next to a test method it will run the entire test suite. If I click Edit Configuration, it shows that "--test_filter=\<test class name\>". If I manually change configurations to "--test_filter=<test class name>#\<test method name\>" (\<test method name\> would be the kotlin test method name with all space removed), it will only run that single test method as expected. I think this is caused because of plugin not popping up correct Run Configuration for kotlin tests?

**Comment by nkoroste** [comment] 2021-01-28 20:29
What's the name of the kotlin test method? if it contains multiple words I think you might need to play around with quotes

**Comment by dylanShark** [comment] 2021-02-08 15:39
Hi @nkoroste , the test method name is in the format of "fun \`verify the following test case\`()". I noticed that the run configuration is actually `--test_filter="my.package.path.<class name>.verify the following test case"`.
I'm using Intellij 2020.2.4 and Bazel plugin 2021.01.29.11

**Comment by nkoroste** [comment] 2021-02-10 01:12
See https://discuss.kotlinlang.org/t/kapt-cannot-get-function-with-backtick-name-as-annotated-element/11547/2

I looked a bit deeper into this and it looks like the problem is with the TestAnnotationProcessor - the problem is that KAPT does not seem to collect annotations on methods with spaces in. If you annotate the whole class as follows it will work.
`@RunWith(JUnit4::class)`
Not sure if this is a bug in KAPT or a limitation in Java AP.

**Comment by kwu4** [comment] 2022-05-05 18:44
I'm also getting this issue as well in JUnit5 for non-backticked methods. 
It seems like when I try to run a single test it returns 
`--test_filter="my.package.path.<class name>.<method name>"`
instead of the expected 
`--test_filter="my.package.path.<class name>#<method name>"`

**Comment by nikunjy** [comment] 2022-08-25 21:12
Do you have any plans to support this ?

**Comment by sgowroji** [comment] 2022-11-08 12:50
@dylanShark We are closing this issue now as it is fixed. Can you please try with latest bazel plugin.

**Closed by sgowroji** 2022-11-08 12:50 UTC
Labels: type: bug, lang: kotlin, more-data-needed, topic: testing
