### ISSUE TITLE
Bazel plugin v2017.12.04.0.2 doesn't support CLion 2017.3 both in Ubuntu 16.04 and Windows 10

### ISSUE THREAD

**Issue by davidhopper2003** [bazelbuild/intellij#203] opened 2018-01-06 02:19 UTC
I installed the latest bazel plugin (version: 2017.12.04.0.2) in CLion 2017.3. But I have encountered the following problem both in Ubuntu 16.04 and Windows 10. Could you please accelerate the process of providing a plugin compatible with 2017.3? Thanks very much. 
```
Plugin 'com.google.idea.bazel.clwb' failed to initialize and will be disabled.  Please restart CLion.

java.lang.NoClassDefFoundError: com/jetbrains/cidr/modulemap/resolve/ModuleMapInitialBuildingActivity
    at com.google.idea.blaze.cpp.CidrSymbolBuilderSuppressor.<clinit>(CidrSymbolBuilderSuppressor.java:35)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:348)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.a(ComponentManagerImpl.java:385)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:96)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:406)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:392)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:203)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.idea.MainImpl$1$1.a(MainImpl.java:65)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
    at java.awt.EventQueue.access$500(EventQueue.java:98)
    at java.awt.EventQueue$3.run(EventQueue.java:715)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:346)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: com.jetbrains.cidr.modulemap.resolve.ModuleMapInitialBuildingActivity PluginClassLoader[com.google.idea.bazel.clwb, 2017.12.04.0.2] com.intellij.ide.plugins.cl.PluginClassLoader@503dfb1f
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:63)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 28 more
```

**Comment by brendandouglas** [comment] 2018-01-08 18:56
Closing as a duplicate of #175

**Closed by brendandouglas** 2018-01-08 18:56 UTC
