### ISSUE TITLE
Support CLion for Apple Silicon 2020.3.1

### ISSUE THREAD

**Issue by wengych** [bazelbuild/intellij#2275] opened 2021-01-02 10:17 UTC

**Comment by neakor** [comment] 2021-01-19 19:21
Upvote. I see a new version is released this week but it's still for the older version of IntelliJ.

**Comment by leoluk** [comment] 2021-01-24 20:19
Duplicate of #2102 - looks like there's good progress.

**Comment by AlexeyGy** [comment] 2021-03-19 20:04
Closed as duplicate, please subscribe to #2102

**Closed by AlexeyGy** 2021-03-19 20:04 UTC
Labels: product: CLion, topic: new IDE version support
