### ISSUE TITLE
Add Missing Gutter Icons for Runnable/Testable Targets

### ISSUE THREAD

**Issue by abhillman** [bazelbuild/intellij#3729] opened 2022-06-25 22:08 UTC
Example:

<img width="568" alt="image" src="https://user-images.githubusercontent.com/1097794/175791841-76cff735-e5af-4fd7-94d2-aba8f8694257.png">

Note that in this example, `intellij_integration_test_suite` is in fact runnable, despite missing gutter icons:

<img width="585" alt="image" src="https://user-images.githubusercontent.com/1097794/175791857-d54a001d-7e99-4b8c-8ead-e4e67d8711fa.png">

**Comment by sgowroji** [comment] 2022-09-27 04:33
I'll close the issue. If you still can reproduce it, please reopen.

**Comment by abhillman** [comment] 2022-09-29 11:09
The example above is from this repo, i.e. https://github.com/bazelbuild/intellij/blob/fe1c1e884cd8654aa90461cd941905116b301bef/aswb/BUILD#L166

**Comment by sgowroji** [comment] 2022-10-06 07:24
Dupe of https://github.com/bazelbuild/intellij/issues/3728

**Comment by mai93** [comment] 2022-10-14 22:57
Hello @abhillman I was able to see the run icon if I imported the project using [aswb.bazelproject](https://github.com/bazelbuild/intellij/blob/master/aswb/aswb.bazelproject) as in this case the `aswb` directory is included and this test target is included in the imported project view. 

<img width="896" alt="Screen Shot 2022-10-14 at 3 47 56 PM" src="https://user-images.githubusercontent.com/70515749/195955355-f9d584f5-c253-447c-a1b5-9cc5c60a3b7a.png">


While if you imported the plugin code using [ijwb.bazelproject](https://github.com/bazelbuild/intellij/blob/master/ijwb/ijwb.bazelproject) for example the `aswb` directory will be excluded (and highlighted with yellow) and the run icon will not show next to this target.

**Closed** 2022-11-01 22:20 UTC
Labels: type: bug, product: IntelliJ, more-data-needed, topic: testing
