### ISSUE TITLE
go_tool_library sources marked as unsynced

### ISSUE THREAD

**Issue by jschaf** [bazelbuild/intellij#2225] opened 2020-11-23 23:23 UTC
#### Description of the issue. Please be specific.

Go sources using the `go_tool_library` are marked as unsynced.  The `go_tool_library` is necessary for `nogo` rules to avoid a cycle in dependencies. The normal `go_library` uses `nogo`.

#### What's the simplest set of steps to reproduce this issue? Please provide an example project, if possible.

https://github.com/jschaf/bazel-bug-go-tool/tree/master/lint

![image](https://user-images.githubusercontent.com/22385/100026433-a2d74900-2d9f-11eb-8004-461e44d993d2.png)

#### Version information
IdeaUltimate: 2020.2.3
Platform: Linux 5.4.0-7642-generic
Bazel plugin: 9999
Bazel: 3.7.0

**Comment by sgowroji** [comment] 2022-11-17 08:29
Dupe of https://github.com/bazelbuild/intellij/issues/1265

**Comment by sgowroji** [comment] 2023-01-31 07:08
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.

**Closed by sgowroji** 2023-01-31 07:08 UTC
Labels: type: bug, lang: go, product: IntelliJ, os: linux, topic: sync, awaiting-maintainer
