### ISSUE TITLE
Alternative to jar cache for solving "red code"

### ISSUE THREAD

**Issue by ittaiz** [bazelbuild/intellij#1256] opened 2019-10-11 15:02 UTC
Bazel IJ plugin configures IJ libraries to point to outputs from bazel's execroot folder.
This is problematic since on every Bazel run (sync/build/test) the symlinks are recalculated and  *external binary* dependencies which aren't in the reach of the current execution are removed.
This is not true for outputs of source dependencies (same workspace or external workspaces).   

This causes "voodoo" red code/squigglies since suddenly IJ's libraries are misconfigured and pointing to a dangling symlink. The current recommendation is to use the jar-cache.  
The jar-cache is indeed much better than without it since sync will deterministically solve red code issues but red code happens more often (if you pull from upstream and have a partial view of the repo or if you build from command line) and additionally means double disk space.  

I'd like to suggest Bazel IJ plugin will traverse symlinks under `$execroot/$repo_name/external` and configure IJ libraries to where this symlinks points to since it's a transient location.  
This is preferable to the jar cache since it will eliminate red-code similarly to jar-cache but at a much smaller cost (only new nodes in the graph which are outside of the IJ sources will require a sync).

I'll try to publish a repro soon

**Comment by jin** [comment] 2019-10-18 20:18
https://github.com/bazelbuild/intellij/issues/884 may be related

**Comment by ittaiz** [comment] 2019-11-01 20:03
@brendandouglas wdyt about this issue? I think that for people who don't use remote execution this small change might make jar cache un-needed which is great (especially now that we've been bitten by #1336 )

**Comment by brendandouglas** [comment] 2019-11-05 14:21
Is the suggestion to resolve symlinks immediately after sync (since the symlinks, but not the files they point to, are transient)? If so, I don't see any problems with doing this if the jar cache is disabled.

I'd be curious to see some examples of the paths before and after (is this only a problem for external workspaces?).

Separately though, if you can reproduce jar cache bugs (or notice it happening more often) we'll be very interested in fixing them.

**Comment by ittaiz** [comment] 2019-11-06 05:09
The suggestion is indeed to resolve symlinks immediately after sync or even during sync (similarly to jar cache) since we know at that time those are there (again similarly to jar cache).
Can I send a PR? If so anything in particular you'd like to me pay attention to?

> I'd be curious to see some examples of the paths before and after (is this only a problem for external workspaces?).

One example:
```
/private/var/tmp/_bazel_ittaiz/c98f9042ba10a6c48fd4fdb03e36d7b0/execroot/io_bazel_rules_scala/external/io_bazel_rules_scala_guava/guava-21.0.jar 
-> 
/private/var/tmp/_bazel_ittaiz/c98f9042ba10a6c48fd4fdb03e36d7b0/external/io_bazel_rules_scala_guava/guava-21.0.jar
```
This is only a problem for external **binary** workspaces since symlinks for source outputs aren't re-planted (those exist under `$execroot/io_bazel_rules_scala/bazel-out/darwin-fastbuild/bin/external/` and are permanent)

> Separately though, if you can reproduce jar cache bugs (or notice it happening more often) we'll be very interested in fixing them.

Other than the one bug I opened (and haven't been able to reproduce yet) I haven't seen any bugs but rather built-in limitations of the jar cache approach (namely missing bazel changes from outside).

**Comment by ittaiz** [comment] 2019-11-13 06:52
@brendandouglas any thoughts?

**Comment by brendandouglas** [comment] 2019-11-13 08:46
Sorry for missing your earlier reply. I don't see any problems with resolving output artifact symlinks immediately after sync, though I'd want it to be optional, since it could cause performance problems internally.

Please do send a PR, and I'll take a look at applying it upstream.

**Comment by ittaiz** [comment] 2019-11-15 21:36
Thanks! Optional is definitely the right choice even if only because this might be a significant change in current behavior and people might be counting on it for some reason.

I've started making myself more aquainted in the sync codebase but as you know it's not small :)
Would you say [ProjectUpdateSyncTask](https://github.com/bazelbuild/intellij/blob/master/base/src/com/google/idea/blaze/base/sync/ProjectUpdateSyncTask.java) is a relevant place? Maybe even concretely around the area of [ProjectUpdateSyncTask#updateProjectStructure]( https://github.com/bazelbuild/intellij/blob/master/base/src/com/google/idea/blaze/base/sync/ProjectUpdateSyncTask.java#L371)?

Would appreciate any bones you can toss my way...

**Comment by ittaiz** [comment] 2019-11-22 12:44
@brendandouglas would really appreciate aligning on the direction so review will be easier

**Comment by brendandouglas** [comment] 2019-11-27 14:28
Sorry for the delay replying. At first glance, the best place to do this would be somewhere around our artifact handling (for example, OutputArtifactParser$LocalFileParser).

However this involves file system operations, so should be batched and run in parallel separately to BEP parsing, similar to our prefetching steps during sync.

Looking a bit closer, this particular use case is accessing files well after sync, so ArtifactLocation is the relevant data class. However that supports only execution-root-relative paths. Is that 'external' directory actually underneath the execution root? If not, this might be impractical, and I'd suggest finding a way to use the jar cache instead.

**Comment by ittaiz** [comment] 2019-11-30 05:52
yes it is. It's `$execRoot/$curws_name/external`.
Essentially what we want to do is resolve any artifact who's path starts with `$curws_name/external` (if indeed the path is relative to `$execRoot`).

**Comment by ittaiz** [comment] 2019-11-30 06:00
I'll debug it to verify but it sounds like maybe [ArtifactLocationDecoderImpl#outputArtifactFromExecRoot](https://github.com/bazelbuild/intellij/blob/master/base/src/com/google/idea/blaze/base/sync/workspace/ArtifactLocationDecoderImpl.java#L102) is where I want to resolve the symlinks.
Is that ok or do you still think batching is needed?
I'm mainly asking since if this needs to be centralized then there is the complexity of later on "updating" the relevant places which hold `BlazeArtifact`. If this will hurt performance then I'll do it but I'm uncertain.

**Comment by brendandouglas** [comment] 2019-12-02 15:40
The symlink is under the execution root (as are all reported output artifacts), but in your example it doesn't seem to resolve to a file under the exec root.

If that's the case, we can't resolve them all up front and store as ArtifactLocations (which require an exec-root-relative path). We can't rely on doing this on demand for performance reasons, ArtifactLocationDecoder#decode is called in performance sensitive code paths, and shouldn't be doing file system operations.

**Comment by ianoc** [comment] 2020-03-11 18:24
For this could we make the change in the `getFallbackFile` path in the `JarCache`, here we return the file that makes it to IntelliJ. We could unconditionally re-write paths that point at jars in external, but not in bazel out and map them outside the exec root? 

I think this would be always valid, and we wouldn't need to read the symlink since it goes to a fixed location?

**Comment by ianoc** [comment] 2020-05-07 17:29
@brendandouglas would you accept a PR/patch to do 
https://github.com/bazeltools/intellij/commit/3f39f3a7f82e6cd67ef71faa9c75ebd6df147733#diff-1e3c0f9e7d40e5a5f45dbaf50c2ae6bc

this eliminated the problem that I've seen

**Comment by brendandouglas** [comment] 2020-05-07 21:12
That patch looks safe, we can definitely accept a PR for that, thanks.

**Comment by ianoc** [comment] 2020-05-07 21:26
Opened https://github.com/bazelbuild/intellij/pull/1817

**Comment by ittaiz** [comment] 2020-05-08 04:09
Thanks @ianoc for picking this up!

**Comment by alice-ks** [comment] 2021-02-03 20:30
As #1819 was merged, I guess we can close this issue now. Please re-open if there's still something missing.

**Closed by alice-ks** 2021-02-03 20:30 UTC
Labels: topic: bazel, topic: java
