### ISSUE TITLE
NPE from the IntelliJ's Exception Tracker

### ISSUE THREAD

**Issue by ignatov** [bazelbuild/intellij#302] opened 2018-05-02 18:32 UTC
java.lang.RuntimeException: Error while applying com.google.idea.blaze.base.console.BlazeConsoleView$CompositeFilter@1cb081d0 to 'ERROR: Skipping '//src/test/docker/...': no targets found beneath 'src/test/docker'.
'

java.lang.RuntimeException: java.lang.RuntimeException: Error while applying com.google.idea.blaze.base.console.BlazeConsoleView$CompositeFilter@1cb081d0 to 'ERROR: Skipping '//src/test/docker/...': no targets found beneath 'src/test/docker'.
'
	at com.intellij.execution.impl.AsyncFilterRunner.isQuick(AsyncFilterRunner.java:88)
	at com.intellij.execution.impl.AsyncFilterRunner.highlightHyperlinks(AsyncFilterRunner.java:74)
	at com.intellij.execution.impl.EditorHyperlinkSupport.highlightHyperlinks(EditorHyperlinkSupport.java:257)
	at com.intellij.execution.impl.ConsoleViewImpl.highlightHyperlinksAndFoldings(ConsoleViewImpl.java:948)
	at com.intellij.execution.impl.ConsoleViewImpl.flushDeferredText(ConsoleViewImpl.java:742)
	at com.intellij.execution.impl.ConsoleViewImpl$FlushRunnable.doRun(ConsoleViewImpl.java:1560)
	at com.intellij.execution.impl.ConsoleViewImpl$FlushRunnable.run(ConsoleViewImpl.java:1556)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:230)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:405)
	at com.intellij.util.Alarm$Request.access$700(Alarm.java:330)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:371)
	at com.intellij.util.Alarm$Request.run(Alarm.java:382)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:228)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:775)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:716)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:381)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.RuntimeException: Error while applying com.google.idea.blaze.base.console.BlazeConsoleView$CompositeFilter@1cb081d0 to 'ERROR: Skipping '//src/test/docker/...': no targets found beneath 'src/test/docker'.
'
	at com.intellij.execution.filters.CompositeFilter.applyFilter(CompositeFilter.java:81)
	at com.intellij.execution.impl.AsyncFilterRunner$HighlighterJob.analyzeLine(AsyncFilterRunner.java:215)
	at com.intellij.execution.impl.AsyncFilterRunner$HighlighterJob.analyzeNextLine(AsyncFilterRunner.java:200)
	at com.intellij.execution.impl.AsyncFilterRunner.runTasks(AsyncFilterRunner.java:152)
	at com.intellij.openapi.application.ReadAction.lambda$nonBlocking$2(ReadAction.java:67)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:113)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$null$1(NonBlockingReadActionImpl.java:89)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1153)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:84)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$2(ProgressIndicatorUtils.java:140)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:138)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:84)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$transferToBgThread$2(NonBlockingReadActionImpl.java:89)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:218)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at com.google.idea.blaze.base.issueparser.BlazeIssueParser.projectViewFileWithSection(BlazeIssueParser.java:349)
	at com.google.idea.blaze.base.issueparser.BlazeIssueParser.access$100(BlazeIssueParser.java:40)
	at com.google.idea.blaze.base.issueparser.BlazeIssueParser$InvalidTargetProjectViewPackageParser.createIssue(BlazeIssueParser.java:295)
	at com.google.idea.blaze.base.issueparser.BlazeIssueParser$SingleLineParser.parse(BlazeIssueParser.java:85)
	at com.google.idea.blaze.base.issueparser.BlazeIssueParser$SingleLineParser.parse(BlazeIssueParser.java:79)
	at com.google.idea.blaze.base.issueparser.BlazeIssueParser.parseIssue(BlazeIssueParser.java:382)
	at com.google.idea.blaze.base.issueparser.IssueOutputFilter.applyFilter(IssueOutputFilter.java:97)
	at com.google.idea.blaze.base.console.BlazeConsoleView$CompositeFilter.lambda$applyFilter$0(BlazeConsoleView.java:215)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1376)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:479)
	at com.google.idea.blaze.base.console.BlazeConsoleView$CompositeFilter.applyFilter(BlazeConsoleView.java:217)
	at com.intellij.execution.filters.CompositeFilter.applyFilter(CompositeFilter.java:75)
	... 21 more

**Comment by brendandouglas** [comment] 2018-05-02 19:32
Could you include your IDE, and the IDE + bazel plugin versions?

**Comment by ignatov** [comment] 2018-05-02 19:40
@brendandouglas Sorry, I can't, that's exception from the plugin user, not me.

**Comment by brendandouglas** [comment] 2018-05-02 19:59
OK. Given the line numbers, they're almost certainly running bazel plugin version 2018.01.02.0.1, which implies they're on a 2018.1 IDE, which we don't yet support.

This particular exception is likely a symptom of that. Closing as a dupe of https://github.com/bazelbuild/intellij/issues/290

**Closed by brendandouglas** 2018-05-02 19:59 UTC

**Comment by brendandouglas** [comment] 2018-05-02 20:04
(I'm surprised the exception tracker doesn't record the IDE + IDE version the exception occurred in)

By the way, do you know if there's a way to remove old plugin versions? We recently started including an 'until-build' tag in the plugin xml to limit it to the given major version, but that just means a previous plugin version will be chosen instead (in this case, plugin version 2018.01.02.0.1 is treated as compatible with all future IDEs).
