### ISSUE TITLE
No `src` nor `test` subdirectories in Project pane

### ISSUE THREAD

**Issue by DimaLiah** [bazelbuild/intellij#197] opened 2018-01-03 10:42 UTC
![screen shot 2018-01-03 at 10 51 48](https://user-images.githubusercontent.com/29011806/34517375-6b88fb3a-f083-11e7-9324-8197a2dad25d.png)

No `src` nor `test` subdirectories in Project pane, though it exist definitely in the file system.

**Comment by ajrepp** [comment] 2018-01-03 13:56
@DimaLiah is this possibly a duplicate of #196?

**Comment by brendandouglas** [comment] 2018-01-10 17:21
It is a dupe, thanks. Closing in favor of #196

**Closed by brendandouglas** 2018-01-10 17:21 UTC
